# -*- coding: utf-8 -*-
"""“baseline_clf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUpI2o72B4JrJck2i20zOg9mGFKemm5Z
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import h5py
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from torch.utils.data import Dataset, DataLoader, random_split
from torch.optim.lr_scheduler import CosineAnnealingLR
from typing import Optional, Tuple
import json
from sklearn.metrics import (accuracy_score, precision_score, recall_score, 
                            f1_score, classification_report, average_precision_score,
                            confusion_matrix)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

from google.colab import drive
drive.mount('/content/drive')
BASE_DIR = "/content/drive/MyDrive/data/"

"""## Data Preprocessing

### Label
"""

def load_label_mapping(mapping_path):
    with open(mapping_path, 'r') as f:
        mapping = json.load(f)

    print(f"mapping: {mapping_path}")
    print(f"  classes: {mapping['n_classes']}")
    print(f"  labels: {list(mapping['label_to_idx'].items())[:]}")

    return mapping

label_mapping = load_label_mapping(BASE_DIR+'label_mapping.json')
n_classes = label_mapping['n_classes']

"""### Augmentation"""

class D4Augmentation:
    def apply_transform(image: torch.Tensor, transform_idx: int) -> torch.Tensor:
        if transform_idx == 0:
            return image
        elif transform_idx == 1:
            return torch.rot90(image, k=-1, dims=(-2, -1))
        elif transform_idx == 2:
            return torch.rot90(image, k=2, dims=(-2, -1))
        elif transform_idx == 3:
            return torch.rot90(image, k=1, dims=(-2, -1))
        elif transform_idx == 4:
            return torch.flip(image, dims=[-1])
        elif transform_idx == 5:
            return torch.flip(image, dims=[-2])
        elif transform_idx == 6:
            return torch.transpose(image, -2, -1)
        elif transform_idx == 7:
            transposed = torch.transpose(image, -2, -1)
            return torch.rot90(transposed, k=2, dims=(-2, -1))
        else:
            raise ValueError(f"Invalid transform_idx: {transform_idx}. Must be 0-7.")

class H5Dataset(Dataset):
    def __init__(self, h5_path: str):
        self.h5f = h5py.File(h5_path, 'r')
        self.images = self.h5f['images']
        self.labels = self.h5f['labels']
        self.valid_indices = self._filter_nan_samples()
        self.n_samples = len(self.valid_indices)

        print(f"H5Dataset initialized: {h5_path}")
        print(f"  Total samples: {len(self.labels)}")
        print(f"  Valid samples: {self.n_samples}")

    def _filter_nan_samples(self):
        valid_indices = []
        for idx in range(len(self.h5f['labels'])):
            img = self.images[idx].astype(np.float32)
            input_bands = img[1:3]  # VV, VH
            if not np.isnan(input_bands).any():
                valid_indices.append(idx)
        return valid_indices

    def __len__(self):
        return self.n_samples

    def __getitem__(self, idx):
        actual_idx = self.valid_indices[idx]
        img = self.images[actual_idx].astype(np.float32).copy()
        input_bands = img[1:3]  # VV, VH
        label = int(self.labels[actual_idx])

        vv = torch.from_numpy(input_bands[0])  # [H, W]
        vh = torch.from_numpy(input_bands[1])  # [H, W]
        image = torch.stack([vv, vh], dim=0)   # [2, H, W]

        label = torch.tensor(label, dtype=torch.long)
        return image, label

    def get_filename(self, idx):
        actual_idx = self.valid_indices[idx]
        return self.images.file['filenames'][actual_idx].decode('utf-8')

    def get_label_name(self, idx):
        actual_idx = self.valid_indices[idx]
        return self.images.file['label_names'][actual_idx].decode('utf-8')

    def close(self):
        if hasattr(self, 'h5f'):
            self.h5f.close()

    def __del__(self):
        self.close()

class ExplicitD4Dataset(Dataset):
    def __init__(self, base_dataset: Dataset):
        self.base_dataset = base_dataset
        self.n_transforms = 8
        self.original_size = len(base_dataset)
        self.total_size = self.original_size * self.n_transforms

        print(f"  原始样本数: {self.original_size:,}")
        print(f"  扩展后样本数: {self.total_size:,}")

    def __len__(self):
        return self.total_size

    def __getitem__(self, idx):
        original_idx = idx // self.n_transforms
        transform_idx = idx % self.n_transforms
        image, label = self.base_dataset[original_idx]
        image = D4Augmentation.apply_transform(image, transform_idx)
        return image, label

def create_dataloaders_with_explicit_d4(
    train_h5: str,
    test_h5: str,
    batch_size: int = 128,
    num_workers: int = 4,
    val_ratio: float = 0.1
):
    base_train_dataset = H5Dataset(train_h5)
    test_dataset = H5Dataset(test_h5)

    original_train_size = len(base_train_dataset)
    val_size = int(original_train_size * val_ratio)
    train_size = original_train_size - val_size

    print(f"  原始训练集: {original_train_size:,} samples")
    print(f"  验证集比例: {val_ratio:.1%}")
    print(f"  划分后训练集: {train_size:,} samples ({train_size/original_train_size:.1%})")
    print(f"  划分后验证集: {val_size:,} samples ({val_size/original_train_size:.1%})")

    random_seed = 42
    torch.manual_seed(random_seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(random_seed)
        torch.cuda.manual_seed_all(random_seed)

    train_indices, val_indices = random_split(
        range(original_train_size),
        [train_size, val_size]
    )

    train_subset_base = torch.utils.data.Subset(base_train_dataset, train_indices.indices)
    train_dataset_8x = ExplicitD4Dataset(train_subset_base)
    print(f"  扩展后训练集: {len(train_dataset_8x):,} samples")
    val_dataset = torch.utils.data.Subset(base_train_dataset, val_indices.indices)
    print(f"  验证集: {len(val_dataset):,} samples (无D4扩展)")

    train_loader = DataLoader(
        train_dataset_8x,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    # ============ 7. 打印摘要 ============
    print(f"\n{'='*70}")
    print("数据加载器创建完成！")
    print(f"{'='*70}")
    print(f"\n训练集:")
    print(f"  原始样本: {train_size:,}")
    print(f"  扩展后样本: {len(train_dataset_8x):,} (8x)")
    print(f"  批次数: {len(train_loader):,}")
    print(f"  增强方式: 显式D4扩展（每个样本→8个版本）")

    print(f"\n验证集:")
    print(f"  样本数: {len(val_dataset):,}")
    print(f"  批次数: {len(val_loader):,}")
    print(f"  增强方式: 无增强")

    print(f"\n测试集:")
    print(f"  样本数: {len(test_dataset):,}")
    print(f"  批次数: {len(test_loader):,}")
    print(f"  增强方式: 无增强")

    print(f"\n训练效率:")
    print(f"  每个epoch迭代次数: {len(train_loader):,}")
    print(f"  相比无增强提升: {len(train_dataset_8x) / train_size:.1f}x")
    print(f"  预计训练时间: 约为原来的 8 倍")

    print(f"\n{'='*70}\n")

    return train_loader, val_loader, test_loader

train_loader, val_loader, test_loader = create_dataloaders_with_explicit_d4(
        train_h5=BASE_DIR + 'train_data.h5',
        test_h5=BASE_DIR + 'test_data.h5',
        batch_size=128,
        num_workers=4,
        val_ratio=0.1  # 10%验证集，90%训练集
    )

"""### Dataloader"""

class H5Dataset(Dataset):
    def __init__(self, h5_path):
        self.h5f = h5py.File(h5_path, 'r')
        self.images = self.h5f['images']
        self.labels = self.h5f['labels']
        self.valid_indices = self._filter_nan_samples()
        self.n_samples = len(self.valid_indices)

    def _filter_nan_samples(self):
        valid_indices = []

        for idx in range(len(self.h5f['labels'])):
            img = self.images[idx].astype(np.float32)
            input_bands = img[1:3]  # vv, vh
            if not np.isnan(input_bands).any():
                valid_indices.append(idx)
        return valid_indices

    def __len__(self):
        return self.n_samples

    def __getitem__(self, idx):
        actual_idx = self.valid_indices[idx]
        img = self.images[actual_idx].astype(np.float32).copy()
        input_bands = img[1:3]  # vv, vh
        label = int(self.labels[actual_idx])
        return torch.from_numpy(input_bands), torch.tensor(label, dtype=torch.long)

    def get_filename(self, idx):
        actual_idx = self.valid_indices[idx]
        return self.images.file['filenames'][actual_idx].decode('utf-8')

    def get_label_name(self, idx):
        actual_idx = self.valid_indices[idx]
        return self.images.file['label_names'][actual_idx].decode('utf-8')

    def close(self):
        if hasattr(self, 'h5f'):
            self.h5f.close()

    def __del__(self):
        self.close()

def create_dataloaders(train_h5, test_h5, batch_size=32, num_workers=2, val_ratio=1.0):
    train_dataset = H5Dataset(train_h5)
    test_dataset = H5Dataset(test_h5)

    val_size = int(len(test_dataset) * val_ratio)
    train_size = len(train_dataset) - val_size

    # Set random seed for reproducible splits
    random_seed = 42
    torch.manual_seed(random_seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(random_seed)
        torch.cuda.manual_seed_all(random_seed)
    train_subset, val_dataset = random_split(train_dataset, [train_size, val_size])

    train_loader = DataLoader(
        train_subset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
    )

    print(f"dataLoaders:")
    print(f"  training set: {len(train_subset)} samples, {len(train_loader)} batches")
    print(f"  validation set: {len(val_dataset)} samples, {len(val_loader)} batches")
    print(f"  testing set: {len(test_dataset)} samples, {len(test_loader)} batches")

    return train_loader, val_loader, test_loader

train_loader, val_loader, test_loader = create_dataloaders(
    train_h5=BASE_DIR+'train_data.h5',
    test_h5=BASE_DIR+'test_data.h5',
    batch_size=128,
    num_workers=4
)

"""### Compute Class Weights from Label Distribution"""

def compute_class_weights(dataloader, num_classes, method='effective', beta=0.9999):
    """
    计算类别权重以处理不平衡数据
    
    Args:
        dataloader: 训练数据加载器
        num_classes: 类别数量
        method: 权重计算方法
            - 'inverse': 逆频率 weight = 1 / count
            - 'balanced': 平衡权重 weight = total / (n_classes * count)
            - 'effective': 有效样本数方法 weight = (1-beta) / (1-beta^count)
        beta: effective方法的超参数，默认0.9999
    
    Returns:
        torch.Tensor: 归一化的类别权重 [num_classes]
    """
    class_counts = torch.zeros(num_classes, dtype=torch.long)
    
    print(f"\n{'='*70}")
    print("统计训练集标签分布...")
    print(f"{'='*70}")
    
    for _, labels in tqdm(dataloader, desc="Counting labels"):
        for label in labels:
            class_counts[label.item()] += 1
    
    total_samples = class_counts.sum().item()
    
    # 计算权重
    if method == 'inverse':
        # 逆频率: w_i = 1 / count_i
        weights = 1.0 / class_counts.float()
    elif method == 'balanced':
        # 平衡权重: w_i = total / (n_classes * count_i)
        weights = total_samples / (num_classes * class_counts.float())
    elif method == 'effective':
        # 有效样本数: w_i = (1 - beta) / (1 - beta^count_i)
        effective_num = 1.0 - torch.pow(beta, class_counts.float())
        weights = (1.0 - beta) / effective_num
    else:
        raise ValueError(f"Unknown method: {method}")
    
    # 归一化权重，使平均权重为1
    weights = weights / weights.mean()
    
    # 打印标签分布和权重
    print(f"\n类别分布与权重统计:")
    print(f"{'Class':<6} {'Count':>10} {'Percentage':>12} {'Weight':>12}")
    print(f"{'-'*70}")
    
    for i in range(num_classes):
        count = class_counts[i].item()
        percentage = 100.0 * count / total_samples
        weight = weights[i].item()
        print(f"{i:<6} {count:>10,} {percentage:>11.2f}% {weight:>12.4f}")
    
    print(f"{'-'*70}")
    print(f"Total: {total_samples:>10,} {'100.00%':>12}")
    print(f"\n权重统计:")
    print(f"  Method: {method}")
    if method == 'effective':
        print(f"  Beta: {beta}")
    print(f"  Min weight: {weights.min().item():.4f}")
    print(f"  Max weight: {weights.max().item():.4f}")
    print(f"  Mean weight: {weights.mean().item():.4f}")
    print(f"  Weight ratio (max/min): {(weights.max() / weights.min()).item():.2f}x")
    print(f"{'='*70}\n")
    
    return weights

# 计算类别权重
class_weights = compute_class_weights(
    train_loader, 
    num_classes=n_classes,
    method='effective',  # 推荐使用有效样本数方法
    beta=0.9999
)

"""### Model"""

class CNN(nn.Module):
    def __init__(self, in_channels=2, num_classes=15, base_channels=64, dropout=0.1):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(in_channels, base_channels, 3, padding=1),
            nn.BatchNorm2d(base_channels),
            nn.ReLU(inplace=True),
            nn.Dropout2d(dropout),

            nn.Conv2d(base_channels, base_channels*2, 3, padding=1),
            nn.BatchNorm2d(base_channels*2),
            nn.ReLU(inplace=True),
            nn.Dropout2d(dropout),
            nn.MaxPool2d(2, 2),  # 6×6 → 3×3

            nn.Conv2d(base_channels*2, base_channels*4, 3, padding=1),
            nn.BatchNorm2d(base_channels*4),
            nn.ReLU(inplace=True),
            nn.Dropout2d(dropout),

            nn.Conv2d(base_channels*4, base_channels*8, 3, padding=0),
            nn.BatchNorm2d(base_channels*8),
            nn.ReLU(inplace=True),
            nn.AdaptiveAvgPool2d(1)
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(dropout),
            nn.Linear(base_channels*8, num_classes)
        )

    def forward(self, x):
        x = self.features(x)      # [B, base_channels*8, 1, 1]
        x = self.classifier(x)    # [B, num_classes]
        return x

"""### Loss Functions"""

class FocalLoss(nn.Module):
    """
    Focal Loss with per-class weights
    FL(p_t) = -α_t * w_c * (1 - p_t)^γ * log(p_t)
    
    Args:
        alpha: Per-class weights tensor [num_classes] or None
        gamma: Focusing parameter (default: 2.0)
               - gamma=0: equivalent to weighted CrossEntropyLoss
               - gamma=2: recommended (from RetinaNet paper)
        reduction: 'mean', 'sum', or 'none'
    """
    def __init__(self, alpha=None, gamma=2.0, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.reduction = reduction
        
        if alpha is None:
            self.alpha = None
        elif isinstance(alpha, (float, int)):
            self.alpha = torch.tensor([alpha])
        else:
            self.alpha = alpha if isinstance(alpha, torch.Tensor) else torch.tensor(alpha)

    def forward(self, inputs, targets):
        """
        Args:
            inputs: [B, C] logits
            targets: [B] class indices
        """
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        p_t = torch.exp(-ce_loss)
        focal_term = (1 - p_t) ** self.gamma
        
        if self.alpha is not None:
            if self.alpha.device != inputs.device:
                self.alpha = self.alpha.to(inputs.device)
            alpha_t = self.alpha[targets]
            focal_loss = alpha_t * focal_term * ce_loss
        else:
            focal_loss = focal_term * ce_loss
        
        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        else:
            return focal_loss


class PseudoHuberLoss(nn.Module):
    """
    Pseudo-Huber Loss for Classification
    PH(x) = δ² * (√(1 + (x/δ)²) - 1)
    
    更平滑、对异常值更鲁棒的损失函数
    
    Args:
        delta: 控制损失曲线形状的参数 (default: 1.0)
               - delta→0: 接近L1 loss (更鲁棒)
               - delta→∞: 接近L2 loss (更平滑)
        alpha: Per-class weights tensor [num_classes] or None
        reduction: 'mean', 'sum', or 'none'
    
    特性:
        - 在|x|<δ时类似L2 (平滑，易优化)
        - 在|x|>δ时类似L1 (鲁棒，对异常值不敏感)
        - 处处可微，优化友好
    """
    def __init__(self, delta=1.0, alpha=None, reduction='mean'):
        super(PseudoHuberLoss, self).__init__()
        self.delta = delta
        self.reduction = reduction
        
        if alpha is None:
            self.alpha = None
        elif isinstance(alpha, (float, int)):
            self.alpha = torch.tensor([alpha])
        else:
            self.alpha = alpha if isinstance(alpha, torch.Tensor) else torch.tensor(alpha)

    def forward(self, inputs, targets):
        """
        Args:
            inputs: [B, C] logits
            targets: [B] class indices
        """
        # 先计算交叉熵作为基础误差
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')  # [B]
        
        # 应用Pseudo-Huber变换: δ² * (√(1 + (x/δ)²) - 1)
        delta_sq = self.delta ** 2
        normalized_loss = ce_loss / self.delta
        ph_loss = delta_sq * (torch.sqrt(1 + normalized_loss ** 2) - 1)
        
        # 应用类别权重
        if self.alpha is not None:
            if self.alpha.device != inputs.device:
                self.alpha = self.alpha.to(inputs.device)
            alpha_t = self.alpha[targets]
            ph_loss = alpha_t * ph_loss
        
        # 应用reduction
        if self.reduction == 'mean':
            return ph_loss.mean()
        elif self.reduction == 'sum':
            return ph_loss.sum()
        else:
            return ph_loss


class CombinedLoss(nn.Module):
    """
    组合损失: Focal Loss + Pseudo-Huber Loss
    L = λ₁ * FocalLoss + λ₂ * PseudoHuberLoss
    
    结合两种损失的优势:
    - Focal Loss: 关注困难样本
    - Pseudo-Huber: 对异常值鲁棒
    
    Args:
        alpha: Per-class weights
        gamma: Focal loss focusing parameter
        delta: Pseudo-Huber delta parameter
        focal_weight: Focal loss权重 (default: 0.7)
        ph_weight: Pseudo-Huber权重 (default: 0.3)
    """
    def __init__(self, alpha=None, gamma=2.0, delta=1.0, 
                 focal_weight=0.7, ph_weight=0.3, reduction='mean'):
        super(CombinedLoss, self).__init__()
        self.focal_loss = FocalLoss(alpha=alpha, gamma=gamma, reduction=reduction)
        self.ph_loss = PseudoHuberLoss(delta=delta, alpha=alpha, reduction=reduction)
        self.focal_weight = focal_weight
        self.ph_weight = ph_weight
    
    def forward(self, inputs, targets):
        focal = self.focal_loss(inputs, targets)
        ph = self.ph_loss(inputs, targets)
        return self.focal_weight * focal + self.ph_weight * ph

"""### Functions"""

def warmup_lr_scheduler(optimizer, warmup_epochs, base_lr):
    def lr_lambda(epoch):
        if epoch < warmup_epochs:
            return (epoch + 1) / warmup_epochs
        return 1.0
    return optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)

def compute_accuracy(pred, target):
    pred_labels = torch.argmax(pred, dim=1)  # [B]
    correct = (pred_labels == target).float()  # [B]
    total = target.size(0)
    accuracy = correct.sum().item() / total if total > 0 else 0.0
    return accuracy

def compute_map(pred, target, num_classes):
    probs = torch.softmax(pred, dim=1).cpu().numpy()  # [B, num_classes]
    target_np = target.cpu().numpy()  # [B]
    if len(target_np) == 0:
        return 0.0
    target_onehot = np.eye(num_classes)[target_np]  # [B, num_classes]
    aps = []
    for i in range(num_classes):
        if target_onehot[:, i].sum() > 0:
            try:
                ap = average_precision_score(target_onehot[:, i], probs[:, i])
                aps.append(ap)
            except:
                continue
    return np.mean(aps) if len(aps) > 0 else 0.0

def train_classification(model, train_loader, criterion, optimizer, device, epoch=0):
    model.train()
    total_loss = 0
    total_acc = 0
    n_batches = 0

    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}")

    for batch_idx, batch_data in enumerate(pbar):
        data, target = batch_data
        data = data.to(device)
        target = target.to(device)

        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        with torch.no_grad():
            acc = compute_accuracy(output, target)

        total_loss += loss.item()
        total_acc += acc
        n_batches += 1

        pbar.set_postfix({
            'Loss': f'{loss.item():.4f}',
            'Acc': f'{acc*100:.1f}%'
        })

    avg_loss = total_loss / n_batches
    avg_acc = total_acc / n_batches

    return avg_loss, avg_acc

def evaluate_classification(model, loader, criterion, device, num_classes):
    model.eval()

    total_loss = 0
    total_acc = 0
    all_preds = []
    all_targets = []
    n_batches = 0

    with torch.no_grad():
        pbar = tqdm(loader, desc="Evaluating")
        for batch_data in pbar:
            data, target = batch_data
            data = data.to(device)
            target = target.to(device)

            output = model(data)
            loss = criterion(output, target)
            acc = compute_accuracy(output, target)
            total_loss += loss.item()
            total_acc += acc
            n_batches += 1

            all_preds.append(output)
            all_targets.append(target)
            pbar.set_postfix({
                'Loss': f'{loss.item():.4f}',
                'Acc': f'{acc*100:.1f}%'
            })

    avg_loss = total_loss / n_batches
    avg_acc = total_acc / n_batches

    all_preds = torch.cat(all_preds, dim=0)
    all_targets = torch.cat(all_targets, dim=0)
    mAP = compute_map(all_preds, all_targets, num_classes)

    return avg_loss, avg_acc, mAP

"""### Train"""

model = CNN(in_channels=2, num_classes=n_classes, base_channels=128, dropout=0.3).to(device)
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\n模型信息:")
print(f"  Total parameters: {total_params:,}")
print(f"  Trainable parameters: {trainable_params:,}")

# ========== 损失函数配置 ==========
# 可选三种损失函数:

# 选项1: Focal Loss (推荐) - 关注困难样本
criterion = FocalLoss(alpha=class_weights, gamma=2.0)
loss_name = "Focal Loss"
loss_config = f"gamma=2.0, alpha=class_weights"

# 选项2: Pseudo-Huber Loss - 对异常值鲁棒
# criterion = PseudoHuberLoss(delta=1.0, alpha=class_weights)
# loss_name = "Pseudo-Huber Loss"
# loss_config = f"delta=1.0, alpha=class_weights"

# 选项3: Combined Loss - 结合两者优势
# criterion = CombinedLoss(alpha=class_weights, gamma=2.0, delta=1.0, 
#                          focal_weight=0.7, ph_weight=0.3)
# loss_name = "Combined Loss (Focal + Pseudo-Huber)"
# loss_config = f"focal_weight=0.7, ph_weight=0.3"

print(f"\n损失函数配置:")
print(f"  Loss: {loss_name}")
print(f"  Config: {loss_config}")
print(f"  Class Weights: 基于训练集分布 (effective number method)")

optimizer = optim.AdamW(
    model.parameters(),
    lr=1e-4,              # Base learning rate
    betas=(0.9, 0.999),
    weight_decay=1e-4     # Weight decay
)

num_epochs = 50
warmup_epochs = int(num_epochs * 0.2)  # 20% warmup
final_div_factor = 1e4
scheduler = CosineAnnealingLR(
    optimizer,
    T_max=num_epochs - warmup_epochs,
    eta_min=1e-5 / final_div_factor
)
warmup_scheduler = warmup_lr_scheduler(optimizer, warmup_epochs, 1e-5)

best_val_loss = float('inf')
best_val_acc = 0.0
best_val_map = 0.0
patience_counter = 0
early_stop_patience = 10

history = {
    'train_loss': [], 'train_acc': [],
    'val_loss': [], 'val_acc': [], 'val_map': [], 'lr': []
}

for epoch in range(num_epochs):
    train_loss, train_acc = train_classification(
        model, train_loader, criterion, optimizer, device, epoch
    )
    val_loss, val_acc, val_map = evaluate_classification(
        model, val_loader, criterion, device, n_classes
    )

    current_lr = optimizer.param_groups[0]['lr']
    if epoch < warmup_epochs:
        warmup_scheduler.step()
    else:
        scheduler.step()

    history['train_loss'].append(train_loss)
    history['train_acc'].append(train_acc)
    history['val_loss'].append(val_loss)
    history['val_acc'].append(val_acc)
    history['val_map'].append(val_map)
    history['lr'].append(current_lr)

    print(f"  Train Loss: {train_loss:.4f} | Train Acc: {train_acc*100:.2f}%")
    print(f"  Val Loss:   {val_loss:.4f} | Val Acc:   {val_acc*100:.2f}% | Val mAP: {val_map:.4f} | LR: {current_lr:.2e}")

    if val_map > best_val_map:
        best_val_map = val_map
        best_val_acc = val_acc
        best_val_loss = val_loss
        patience_counter = 0

        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'val_loss': val_loss,
            'val_acc': val_acc,
            'val_map': val_map,
            'history': history
        }, 'best_classification_model.pth')

        print(f" *Best model | mAP: {best_val_map:.4f}, Acc: {best_val_acc*100:.2f}%, Loss: {best_val_loss:.4f}\n")
    else:
        patience_counter += 1
        print(f"Patience: {patience_counter}/{early_stop_patience}\n")

    if patience_counter >= early_stop_patience:
        print(f"Early stopping triggered at epoch {epoch+1}")
        print(f"Best validation mAP: {best_val_map:.4f}")
        break

def plot_training_history(history):
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))

    axes[0, 0].plot(history['train_loss'], label='Train Loss')
    axes[0, 0].plot(history['val_loss'], label='Val Loss')
    axes[0, 0].set_xlabel('Epoch')
    axes[0, 0].set_ylabel('Loss')
    axes[0, 0].set_title('Training and Validation Loss')
    axes[0, 0].legend()
    axes[0, 0].grid(True)

    axes[0, 1].plot([x*100 for x in history['train_acc']], label='Train Acc')
    axes[0, 1].plot([x*100 for x in history['val_acc']], label='Val Acc')
    axes[0, 1].set_xlabel('Epoch')
    axes[0, 1].set_ylabel('Accuracy (%)')
    axes[0, 1].set_title('Training and Validation Accuracy')
    axes[0, 1].legend()
    axes[0, 1].grid(True)

    axes[1, 0].plot(history['val_map'], label='Val mAP', color='green')
    axes[1, 0].set_xlabel('Epoch')
    axes[1, 0].set_ylabel('mAP')
    axes[1, 0].set_title('Validation mAP')
    axes[1, 0].legend()
    axes[1, 0].grid(True)

    axes[1, 1].plot(history['lr'], label='Learning Rate', color='orange')
    axes[1, 1].set_xlabel('Epoch')
    axes[1, 1].set_ylabel('Learning Rate')
    axes[1, 1].set_title('Learning Rate Schedule')
    axes[1, 1].set_yscale('log')
    axes[1, 1].legend()
    axes[1, 1].grid(True)

    plt.tight_layout()
    plt.show()

plot_training_history(history)

"""### Test"""

def evaluate_classification(model, loader, criterion, device, detailed=False, label_mapping=None):
    model.eval()
    total_loss = 0
    total_acc = 0
    n_batches = 0

    all_preds = []
    all_labels = []

    with torch.no_grad():
        pbar = tqdm(loader, desc="Evaluating")
        for data, target in pbar:
            data, target = data.to(device), target.to(device)
            output = model(data)

            loss = criterion(output, target)
            acc = compute_accuracy(output, target)

            total_loss += loss.item()
            total_acc += acc
            n_batches += 1

            if detailed:
                preds = torch.argmax(output, dim=1)
                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(target.cpu().numpy())

            pbar.set_postfix({
                'Loss': f'{loss.item():.4f}',
                'Acc': f'{acc*100:.1f}%'
            })

    avg_loss = total_loss / n_batches
    avg_acc = total_acc / n_batches

    if not detailed:
        return avg_loss, avg_acc

    # Detailed evaluation
    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)

    # Print results
    print(f"\n{'='*70}")
    print(f"CLASSIFICATION TEST RESULTS")
    print(f"{'='*70}")
    print(f"Loss: {avg_loss:.4f}")
    print(f"Accuracy: {avg_acc*100:.2f}%")

    # Get label names
    if label_mapping and 'idx_to_label' in label_mapping:
        idx_to_label = label_mapping['idx_to_label']
        # Convert string keys to int if needed
        if isinstance(list(idx_to_label.keys())[0], str):
            idx_to_label = {int(k): v for k, v in idx_to_label.items()}
        target_names = [idx_to_label.get(i, f'Class_{i}') for i in range(len(idx_to_label))]
    else:
        target_names = None

    # Confusion Matrix
    cm = confusion_matrix(all_labels, all_preds)

    fig, ax = plt.subplots(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=target_names if target_names else 'auto',
                yticklabels=target_names if target_names else 'auto')
    ax.set_title('Confusion Matrix')
    ax.set_ylabel('True Label')
    ax.set_xlabel('Predicted Label')
    if target_names:
        plt.xticks(rotation=45, ha='right')
        plt.yticks(rotation=0)
    plt.tight_layout()
    plt.savefig('classification_confusion_matrix.png', dpi=300, bbox_inches='tight')
    plt.show()

    # Classification Report
    print(f"\n{'='*70}")
    print("DETAILED CLASSIFICATION REPORT")
    print(f"{'='*70}")
    print(classification_report(all_labels, all_preds,
                                target_names=target_names,
                                zero_division=0))

    # Per-class Accuracy
    class_acc = cm.diagonal() / cm.sum(axis=1)
    print(f"\n{'='*70}")
    print("PER-CLASS ACCURACY")
    print(f"{'='*70}")
    for i, acc in enumerate(class_acc):
        count = cm.sum(axis=1)[i]
        label_name = target_names[i] if target_names else f'Class {i}'
        print(f"{label_name:20s}: {acc*100:5.2f}% ({int(count):4d} samples)")

    # Summary
    print(f"\n{'='*70}")
    print("SUMMARY")
    print(f"{'='*70}")
    print(f"Overall Accuracy: {avg_acc*100:.2f}%")
    print(f"Mean Per-Class Acc: {class_acc.mean()*100:.2f}%")

    if target_names:
        print(f"Best Class: {target_names[class_acc.argmax()]} ({class_acc.max()*100:.2f}%)")
        print(f"Worst Class: {target_names[class_acc.argmin()]} ({class_acc.min()*100:.2f}%)")
    else:
        print(f"Best Class: {class_acc.argmax()} ({class_acc.max()*100:.2f}%)")
        print(f"Worst Class: {class_acc.argmin()} ({class_acc.min()*100:.2f}%)")

    # Check for never predicted classes
    unique_preds = set(all_preds)
    unique_labels = set(all_labels)
    never_predicted = unique_labels - unique_preds
    if never_predicted:
        print(f"\n⚠️ WARNING: Classes never predicted: {sorted(never_predicted)}")
        if target_names:
            never_pred_names = [target_names[i] for i in sorted(never_predicted)]
            print(f"   ({', '.join(never_pred_names)})")

    return avg_loss, avg_acc, all_preds, all_labels

# ✓ 添加 weights_only=False
model.load_state_dict(torch.load('best_classification_model.pth', weights_only=False))

evaluate_classification(
    model, test_loader, criterion, device,
    detailed=True, label_mapping=label_mapping
)

