# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DOMeJgTLSyh4S8RONVwL1dn_yhJf2uH
"""

import torch
import torch.nn as nn
import h5py
import numpy as np
import json
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from torch.utils.data import Dataset, DataLoader, random_split, WeightedRandomSampler
import torch.optim as optim
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

from google.colab import drive
drive.mount('/content/drive')
BASE_DIR = "/content/drive/MyDrive/data/"

"""## Dataloader"""

class H5Dataset(Dataset):
    def __init__(self, h5_path, task='regression', stats=None):
        """
        Dataset for regression, classification, or multitask learning

        Args:
            h5_path: Path to H5 file
            task: 'regression', 'classification', or 'multitask'
            stats: Pre-computed statistics (optional)
        """
        self.task = task
        self.h5f = h5py.File(h5_path, 'r')
        self.images = self.h5f['images']

        # Load labels for classification/multitask
        if task in ['classification', 'multitask']:
            self.labels = self.h5f['labels']
            print(f"Loaded labels with shape: {self.labels.shape}")

        self.valid_indices = self._filter_valid_samples()
        self.stats = stats if stats else self._compute_stats()

        print(f"\nDataset: {h5_path.split('/')[-1]}")
        print(f"Task: {task}")
        print(f"Samples: {len(self.valid_indices)} (filtered {self.images.shape[0] - len(self.valid_indices)} NaN)")
        if not stats:
            self._print_stats()

    def _filter_valid_samples(self):
        return [i for i in range(self.images.shape[0])
                if not np.isnan(self.images[i][1:4].astype(np.float32)).any()]

    def _normalize_inputs(self, inputs):
        normalized = np.empty_like(inputs)
        for c in range(3):
            normalized[..., c, :, :] = (2.0 * (inputs[..., c, :, :] - self.stats['input_min'][c])
                                       / self.stats['input_range'][c] - 1.0)
        return normalized

    def _compute_stats(self):
        n_sample = min(1000, len(self.valid_indices))
        indices = np.random.choice(self.valid_indices, n_sample, replace=False)

        raw_inputs = np.array([self.images[i][1:4].astype(np.float32) for i in indices])
        raw_targets = np.array([self.images[i][0:1].astype(np.float32) for i in indices])
        input_min = np.nanmin(raw_inputs, axis=(0, 2, 3))
        input_max = np.nanmax(raw_inputs, axis=(0, 2, 3))

        temp_stats = {
            'input_min': input_min,
            'input_max': input_max,
            'input_mean': np.nanmean(raw_inputs, axis=(0, 2, 3)),
            'input_std': np.nanstd(raw_inputs, axis=(0, 2, 3)),
            'input_range': input_max - input_min
        }
        self.stats = temp_stats
        norm_inputs = self._normalize_inputs(raw_inputs)
        norm_mean = np.nanmean(norm_inputs, axis=(0, 2, 3))
        norm_std = np.nanstd(norm_inputs, axis=(0, 2, 3))
        norm_min = np.nanmin(norm_inputs, axis=(0, 2, 3))
        norm_max = np.nanmax(norm_inputs, axis=(0, 2, 3))

        return {
            **temp_stats,
            'target_mean': np.nanmean(raw_targets),
            'target_std': np.nanstd(raw_targets),
            'target_min': np.nanmin(raw_targets),
            'target_max': np.nanmax(raw_targets),
            'norm_mean': norm_mean,
            'norm_std': norm_std,
            'norm_min': norm_min,
            'norm_max': norm_max
        }

    def _print_stats(self):
        s = self.stats
        channels = ['VV', 'VH', 'VV/VH']

        print("\nRaw Input Statistics:")
        for i, ch in enumerate(channels):
            print(f"  {ch}: mean={s['input_mean'][i]:.4f}, std={s['input_std'][i]:.4f}, {ch}: min={s['input_min'][i]:.2f}, max={s['input_max'][i]:.2f}")

        if self.task in ['regression', 'multitask']:
            print(f"  CHM: mean={s['target_mean']:.2f}, std={s['target_std']:.2f}, CHM: min={s['target_min']:.2f}, max={s['target_max']:.2f}")

        print("\nNormalized Statistics:")
        for i, ch in enumerate(channels):
            print(f"  {ch}: mean={s['norm_mean'][i]:.4f}, std={s['norm_std'][i]:.4f}, min={s['norm_min'][i]:.4f}, max={s['norm_max'][i]:.4f}")

        # Print label distribution for classification/multitask
        if self.task in ['classification', 'multitask']:
            print("\nLabel Distribution:")
            label_array = np.array([self.labels[i] for i in self.valid_indices])
            unique_labels, counts = np.unique(label_array, return_counts=True)
            for label, count in zip(unique_labels, counts):
                print(f"  Class {label}: {count} samples ({count/len(label_array)*100:.1f}%)")

    def __len__(self):
        return len(self.valid_indices)

    def __getitem__(self, idx):
        real_idx = self.valid_indices[idx]
        img = self.images[real_idx].astype(np.float32)
        inputs = self._normalize_inputs(img[1:4])

        if self.task == 'regression':
            # Regression: return (inputs, CHM target)
            target = img[0:1].copy()
            target[target < 1.0] = np.nan
            return torch.from_numpy(inputs), torch.from_numpy(target)

        elif self.task == 'classification':
            # Classification: return (inputs, label)
            label = torch.tensor(self.labels[real_idx], dtype=torch.long)
            return torch.from_numpy(inputs), label

        elif self.task == 'multitask':
            # Multitask: return (inputs, (CHM target, label))
            target = img[0:1].copy()
            target[target < 1.0] = np.nan
            label = torch.tensor(self.labels[real_idx], dtype=torch.long)
            return torch.from_numpy(inputs), (torch.from_numpy(target), label)

        else:
            raise ValueError(f"Unknown task: {self.task}. Must be 'regression', 'classification', or 'multitask'.")

    def get_stats(self):
        return self.stats

    def close(self):
        if hasattr(self, 'h5f'):
            self.h5f.close()

    def __del__(self):
        self.close()

def create_dataloaders(train_h5, test_h5, task='regression', batch_size=32, num_workers=2,
                       val_ratio=0.1, use_weighted_sampler=False):
    train_dataset = H5Dataset(train_h5, task=task)
    train_stats = train_dataset.get_stats()
    test_dataset = H5Dataset(test_h5, task=task, stats=train_stats)

    val_size = int(len(train_dataset) * val_ratio)
    train_size = len(train_dataset) - val_size

    torch.manual_seed(42)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(42)
        torch.cuda.manual_seed_all(42)

    train_subset, val_subset = random_split(train_dataset, [train_size, val_size])
    shuffle = True
    sampler = None
    if use_weighted_sampler and task in ['classification', 'multitask']:
        print("\n" + "="*70)
        print("Creating WeightedRandomSampler for oversampling rare classes")
        print("="*70)

        # Collect labels from training subset
        train_labels = []
        for idx in train_subset.indices:
            if task == 'classification':
                _, label = train_dataset[idx]
                train_labels.append(label.item())
            elif task == 'multitask':
                _, (_, label) = train_dataset[idx]
                train_labels.append(label.item())

        train_labels = np.array(train_labels)

        class_counts = np.bincount(train_labels)
        sample_weights = 1.0 / class_counts[train_labels]

        print(f"\nClass sampling weights:")
        print(f"  Max upsampling ratio: {sample_weights.max() / sample_weights.min():.1f}x")
        print(f"  Rare classes will appear ~{class_counts.max() / class_counts.min():.1f}x more per epoch")

        sampler = WeightedRandomSampler(
            weights=torch.DoubleTensor(sample_weights),
            num_samples=len(sample_weights),
            replacement=True
        )
        shuffle = False  # Disable shuffle when using sampler

        print(f"✓ WeightedRandomSampler created")
        print("="*70)

    # create dataloaders
    train_loader = DataLoader(
        train_subset,
        batch_size=batch_size,
        shuffle=shuffle,
        sampler=sampler,
        num_workers=num_workers,
        pin_memory=True if device == 'cuda' else False
    )

    val_loader = DataLoader(
        val_subset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True if device == 'cuda' else False
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True if device == 'cuda' else False
    )

    print(f"\nDataLoaders created:")
    print(f"  Training set: {len(train_subset)} samples, {len(train_loader)} batches")
    print(f"  Validation set: {len(val_subset)} samples, {len(val_loader)} batches")
    print(f"  Test set: {len(test_dataset)} samples, {len(test_loader)} batches")

    return train_loader, val_loader, test_loader

"""## Model Definition"""

class BaseUNet(nn.Module):
    """
    Base UNet optimized for 6×6 small patches

    Architecture (3-layer encoder):
    Input:  [B, 3, 6, 6]
    enc1:   [B, 32, 6, 6]   # No pooling
    enc2:   [B, 64, 3, 3]   # After MaxPool(2,2)
    enc3:   [B, 128, 1, 1]  # After AdaptivePool(1,1)
    bottleneck: [B, 256, 1, 1]

    For 6×6 input, this prevents over-downsampling and maintains
    meaningful spatial information at each level.
    """

    def __init__(self, in_channels=3, base_channels=32, dropout=0.1):
        super(BaseUNet, self).__init__()
        self.base_channels = base_channels

        # ============ Encoder (3 layers) ============
        # Optimized for 6×6 input - removed redundant enc4
        self.enc1 = self._conv_block(in_channels, base_channels, dropout)        # 6×6
        self.enc2 = self._conv_block(base_channels, base_channels*2, dropout)    # 3×3
        self.enc3 = self._conv_block(base_channels*2, base_channels*4, dropout)  # 1×1
        self.bottleneck = self._conv_block(base_channels*4, base_channels*8, dropout)  # 1×1

        # Pooling layers
        self.pool1 = nn.MaxPool2d(2, 2)              # 6×6 → 3×3
        self.pool2 = nn.AdaptiveMaxPool2d((1, 1))    # 3×3 → 1×1

    def _conv_block(self, in_ch, out_ch, dropout):
        """Convolutional block with BatchNorm and ReLU"""
        return nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=False),
            nn.Dropout2d(dropout) if dropout > 0 else nn.Identity(),
            nn.Conv2d(out_ch, out_ch, 3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=False)
        )

    def _up_block(self, in_ch, out_ch, kernel, stride, padding):
        """Upsampling block for decoder"""
        if kernel == 1:
            return nn.Sequential(
                nn.Conv2d(in_ch, out_ch, 1),
                nn.BatchNorm2d(out_ch),
                nn.ReLU(inplace=False)
            )
        return nn.Sequential(
            nn.ConvTranspose2d(in_ch, out_ch, kernel, stride, padding),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=False)
        )

    def encode(self, x):
        """
        Forward pass through encoder, returns features at different scales

        Returns:
            e1: [B, 32, 6, 6]   - Low-level features (textures)
            e2: [B, 64, 3, 3]   - Mid-level features (patterns)
            e3: [B, 128, 1, 1]  - High-level features (semantics)
            b:  [B, 256, 1, 1]  - Bottleneck (most abstract)
        """
        e1 = self.enc1(x)                   # [B, 32, 6, 6]
        e2 = self.enc2(self.pool1(e1))      # [B, 64, 3, 3]
        e3 = self.enc3(self.pool2(e2))      # [B, 128, 1, 1]
        b = self.bottleneck(e3)             # [B, 256, 1, 1]
        return e1, e2, e3, b

"""### Regression"""

"""### Regression"""

class RegressionUNet(BaseUNet):
    """
    UNet for regression tasks (e.g., CHM prediction)
    Optimized for 6×6 input patches

    Decoder path:
    bottleneck [256, 1, 1] → up1 → d1 [64, 1, 1]
                                    ↓
    e3 [128, 1, 1] ─────────────────┘

    d1 [64, 1, 1] → up2 → d2 [32, 3, 3]
                          ↓
    e2 [64, 3, 3] ────────┘

    d2 [32, 3, 3] → up3 → d3 [32, 6, 6]
                          ↓
    e1 [32, 6, 6] ────────┘

    d3 [32, 6, 6] + residual → final → [1, 6, 6]
    """

    def __init__(self, in_channels=3, out_channels=1, base_channels=32, dropout=0.1):
        super(RegressionUNet, self).__init__(in_channels, base_channels, dropout)

        # Residual connection from input
        self.input_proj = nn.Conv2d(in_channels, base_channels, 1)

        # ============ Decoder (3 stages, matching 3-layer encoder) ============

        # Stage 1: 1×1 → 1×1 (channel reduction)
        self.up1 = self._up_block(base_channels*8, base_channels*4, 1, 1, 0)  # 256→128
        # After concat with e3 (128): 256 channels total
        self.dec1 = self._conv_block(base_channels*8, base_channels*2, dropout)  # 256→64

        # Stage 2: 1×1 → 3×3 (upsample)
        self.up2 = self._up_block(base_channels*2, base_channels*2, 3, 3, 0)  # 64→64, 1×1→3×3
        # After concat with e2 (64): 128 channels total
        self.dec2 = self._conv_block(base_channels*4, base_channels, dropout)  # 128→32

        # Stage 3: 3×3 → 6×6 (upsample)
        self.up3 = self._up_block(base_channels, base_channels, 2, 2, 0)  # 32→32, 3×3→6×6
        # After concat with e1 (32): 64 channels total
        self.dec3 = self._conv_block(base_channels*2, base_channels, dropout)  # 64→32

        # Regression head
        self.final = nn.Sequential(
            nn.Conv2d(base_channels, base_channels//2, 3, padding=1),
            nn.BatchNorm2d(base_channels//2),
            nn.ReLU(inplace=False),
            nn.Conv2d(base_channels//2, out_channels, 1)
        )

    def forward(self, x):
        """
        Forward pass

        Args:
            x: [B, 3, 6, 6] - Input SAR data (VV, VH, VV/VH)

        Returns:
            output: [B, 1, 6, 6] - Predicted CHM (non-negative due to Softplus)
        """
        input_res = self.input_proj(x)  # [B, 32, 6, 6]

        # Encoder
        e1, e2, e3, b = self.encode(x)
        # e1: [B, 32, 6, 6]
        # e2: [B, 64, 3, 3]
        # e3: [B, 128, 1, 1]
        # b:  [B, 256, 1, 1]

        # Decoder with skip connections
        d1 = self.dec1(torch.cat([self.up1(b), e3], dim=1))    # [B, 64, 1, 1]
        d2 = self.dec2(torch.cat([self.up2(d1), e2], dim=1))   # [B, 32, 3, 3]
        d3 = self.dec3(torch.cat([self.up3(d2), e1], dim=1))   # [B, 32, 6, 6]

        # Final output with residual connection
        output = self.final(d3 + input_res)  # [B, 1, 6, 6]

        # ✨ Ensure non-negative output (CHM cannot be negative)
        # output = nn.functional.softplus(output, beta=1)

        return output

"""### Classification"""

class ClassificationUNet(BaseUNet):
    """
    UNet for classification tasks (tree species recognition)
    Optimized for 6×6 input patches
    
    Architecture:
    ┌─────────────────────────────────────────────────────────────┐
    │                    INPUT [B, 3, 6×6]                        │
    │                  (VV, VH, VV/VH bands)                      │
    └────────────────────┬────────────────────────────────────────┘
                         │
                         ↓
    ┌────────────────────────────────────────────────────────────┐
    │              ENCODER (Shared with BaseUNet)                │
    ├────────────────────────────────────────────────────────────┤
    │  enc1:  Conv→BN→ReLU→Dropout→Conv→BN→ReLU                 │
    │         [B, 3, 6×6] → [B, 32, 6×6]                         │
    │         ↓ MaxPool(2×2)                                     │
    │  enc2:  Conv→BN→ReLU→Dropout→Conv→BN→ReLU                 │
    │         [B, 32, 3×3] → [B, 64, 3×3]                        │
    │         ↓ AdaptivePool(1×1)                                │
    │  enc3:  Conv→BN→ReLU→Dropout→Conv→BN→ReLU                 │
    │         [B, 64, 1×1] → [B, 128, 1×1]                       │
    │         ↓                                                   │
    │  bottleneck: Conv→BN→ReLU→Dropout→Conv→BN→ReLU            │
    │         [B, 128, 1×1] → [B, 256, 1×1]                      │
    └────────────────────┬───────────────────────────────────────┘
                         │
                         ↓
    ┌────────────────────────────────────────────────────────────┐
    │              CLASSIFICATION HEAD                           │
    ├────────────────────────────────────────────────────────────┤
    │  Global Pooling: [B, 256, 1×1] → [B, 256]                 │
    │         ↓                                                   │
    │  FC1:   Linear(256, 128) → BN → ReLU → Dropout            │
    │         ↓                                                   │
    │  FC2:   Linear(128, 64) → BN → ReLU → Dropout             │
    │         ↓                                                   │
    │  FC3:   Linear(64, num_classes)                            │
    └────────────────────┬───────────────────────────────────────┘
                         │
                         ↓
                  [B, num_classes]
                  (Tree species logits)
    
    Key Design Choices:
    - Uses bottleneck features (most abstract) for classification
    - No decoder needed (global pooling aggregates spatial info)
    - 3-layer FC head for sufficient non-linearity
    - Dropout for regularization
    
    Parameters (base_channels=32):
    - Encoder: ~173K (shared with regression)
    - Classification Head: ~41K
    - Total: ~214K parameters
    """

    def __init__(self, in_channels=3, num_classes=10, base_channels=32, dropout=0.1):
        super(ClassificationUNet, self).__init__(in_channels, base_channels, dropout)

        # Global pooling - reduces spatial dimensions to 1×1
        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))

        # Classification head - 3 fully connected layers
        # Input: base_channels*8 = 256 (from bottleneck)
        self.classifier = nn.Sequential(
            nn.Flatten(),
            # Layer 1: 256 → 128
            nn.Linear(base_channels*8, base_channels*4),
            nn.BatchNorm1d(base_channels*4),
            nn.ReLU(inplace=False),
            nn.Dropout(dropout),
            # Layer 2: 128 → 64
            nn.Linear(base_channels*4, base_channels*2),
            nn.BatchNorm1d(base_channels*2),
            nn.ReLU(inplace=False),
            nn.Dropout(dropout),
            # Layer 3: 64 → num_classes
            nn.Linear(base_channels*2, num_classes)
        )

    def forward(self, x):
        """
        Forward pass
        
        Args:
            x: [B, 3, 6, 6] - Input SAR data (VV, VH, VV/VH)
        
        Returns:
            logits: [B, num_classes] - Class logits (not probabilities)
        """
        # Encoder - extract hierarchical features
        _, _, _, b = self.encode(x)
        # b: [B, 256, 1×1] - Bottleneck features (most abstract)

        # Global pooling - already 1×1, but ensures consistency
        pooled = self.global_pool(b)  # [B, 256, 1, 1]
        
        # Classification head
        logits = self.classifier(pooled)  # [B, num_classes]
        
        return logits

"""### Multi"""

# class MultitaskUNet(BaseUNet):
#     """UNet for multitask learning (regression + classification)"""

#     def __init__(self, in_channels=3, out_channels=1, num_classes=10, base_channels=32, dropout=0.1):
#         super(MultitaskUNet, self).__init__(in_channels, base_channels, dropout)

#         # Residual connection for regression
#         self.input_proj = nn.Conv2d(in_channels, base_channels, 1)

#         # Regression decoder
#         self.up1 = self._up_block(base_channels*16, base_channels*8, 1, 1, 0)
#         self.up2 = self._up_block(base_channels*4, base_channels*2, 3, 1, 0)
#         self.up3 = self._up_block(base_channels*2, base_channels, 2, 2, 0)

#         self.dec1 = self._conv_block(base_channels*12, base_channels*4, dropout)
#         self.dec2 = self._conv_block(base_channels*4, base_channels*2, dropout)
#         self.dec3 = self._conv_block(base_channels*2, base_channels, dropout)

#         # Regression head
#         self.regression_head = nn.Sequential(
#             nn.Conv2d(base_channels, base_channels//2, 3, padding=1),
#             nn.BatchNorm2d(base_channels//2),
#             nn.ReLU(inplace=False),
#             nn.Conv2d(base_channels//2, out_channels, 1)
#         )

#         # Classification head
#         self.global_pool = nn.AdaptiveAvgPool2d((1, 1))
#         self.classification_head = nn.Sequential(
#             nn.Flatten(),
#             nn.Linear(base_channels*16, base_channels*8),
#             nn.BatchNorm1d(base_channels*8),
#             nn.ReLU(inplace=False),
#             nn.Dropout(dropout),
#             nn.Linear(base_channels*8, base_channels*4),
#             nn.BatchNorm1d(base_channels*4),
#             nn.ReLU(inplace=False),
#             nn.Dropout(dropout),
#             nn.Linear(base_channels*4, num_classes)
#         )

#     def forward(self, x):
#         input_res = self.input_proj(x)

#         # Shared encoder
#         e1, e2, e3, b = self.encode(x)

#         # Regression branch
#         d1 = self.dec1(torch.cat([self.up1(b), e3], dim=1))
#         d2 = self.dec2(torch.cat([self.up2(d1), e2], dim=1))
#         d3 = self.dec3(torch.cat([self.up3(d2), e1], dim=1))
#         regression_output = self.regression_head(d3 + input_res)

#         # Classification branch
#         pooled = self.global_pool(b)
#         classification_output = self.classification_head(pooled)

#         return regression_output, classification_output

class MultitaskUNet(BaseUNet):
    """UNet for multitask learning (regression + classification)

    Improved version with multi-scale features for classification.
    """

    def __init__(self, in_channels=3, out_channels=1, num_classes=10, base_channels=32, dropout=0.1,
                 use_multiscale_cls=True):
        super(MultitaskUNet, self).__init__(in_channels, base_channels, dropout)

        self.use_multiscale_cls = use_multiscale_cls

        # Residual connection for regression
        self.input_proj = nn.Conv2d(in_channels, base_channels, 1)

        # Regression decoder
        self.up1 = self._up_block(base_channels*16, base_channels*8, 1, 1, 0)
        self.up2 = self._up_block(base_channels*4, base_channels*2, 3, 1, 0)
        self.up3 = self._up_block(base_channels*2, base_channels, 2, 2, 0)

        self.dec1 = self._conv_block(base_channels*12, base_channels*4, dropout)
        self.dec2 = self._conv_block(base_channels*4, base_channels*2, dropout)
        self.dec3 = self._conv_block(base_channels*2, base_channels, dropout)

        # Regression head
        self.regression_head = nn.Sequential(
            nn.Conv2d(base_channels, base_channels//2, 3, padding=1),
            nn.BatchNorm2d(base_channels//2),
            nn.ReLU(inplace=False),
            nn.Conv2d(base_channels//2, out_channels, 1)
        )

        # Improved Classification head with multi-scale features
        if use_multiscale_cls:
            # Pool different encoder layers to same spatial size
            self.cls_pool1 = nn.AdaptiveAvgPool2d((4, 4))   # e1: 32 channels → 32*16
            self.cls_pool2 = nn.AdaptiveAvgPool2d((4, 4))   # e2: 64 channels → 64*16
            self.cls_pool3 = nn.AdaptiveAvgPool2d((4, 4))   # e3: 128 channels → 128*16
            self.cls_pool4 = nn.AdaptiveAvgPool2d((2, 2))   # b:  512 channels → 512*4

            # Total features: 32*16 + 64*16 + 128*16 + 512*4 = 5632
            # Note: e3 is base_channels*4 (128), not base_channels*8 (256)
            total_features = (base_channels * 16) + (base_channels*2 * 16) + \
                           (base_channels*4 * 16) + (base_channels*16 * 4)

            self.classification_head = nn.Sequential(
                nn.Flatten(),
                nn.Linear(total_features, base_channels*16),
                nn.BatchNorm1d(base_channels*16),
                nn.ReLU(inplace=False),
                nn.Dropout(dropout),
                nn.Linear(base_channels*16, base_channels*8),
                nn.BatchNorm1d(base_channels*8),
                nn.ReLU(inplace=False),
                nn.Dropout(dropout),
                nn.Linear(base_channels*8, num_classes)
            )
        else:
            # Original: only use bottleneck
            self.global_pool = nn.AdaptiveAvgPool2d((1, 1))
            self.classification_head = nn.Sequential(
                nn.Flatten(),
                nn.Linear(base_channels*16, base_channels*8),
                nn.BatchNorm1d(base_channels*8),
                nn.ReLU(inplace=False),
                nn.Dropout(dropout),
                nn.Linear(base_channels*8, base_channels*4),
                nn.BatchNorm1d(base_channels*4),
                nn.ReLU(inplace=False),
                nn.Dropout(dropout),
                nn.Linear(base_channels*4, num_classes)
            )

    def forward(self, x):
        input_res = self.input_proj(x)

        # Shared encoder
        e1, e2, e3, b = self.encode(x)

        # Regression branch
        d1 = self.dec1(torch.cat([self.up1(b), e3], dim=1))
        d2 = self.dec2(torch.cat([self.up2(d1), e2], dim=1))
        d3 = self.dec3(torch.cat([self.up3(d2), e1], dim=1))
        regression_output = self.regression_head(d3 + input_res)

        # Classification branch
        if self.use_multiscale_cls:
            # Use multi-scale features from all encoder layers
            f1 = self.cls_pool1(e1).flatten(1)  # (B, 32*16)
            f2 = self.cls_pool2(e2).flatten(1)  # (B, 64*16)
            f3 = self.cls_pool3(e3).flatten(1)  # (B, 256*16)
            f4 = self.cls_pool4(b).flatten(1)   # (B, 512*4)

            # Concatenate all features
            cls_features = torch.cat([f1, f2, f3, f4], dim=1)
            classification_output = self.classification_head(cls_features)
        else:
            # Original: only use bottleneck
            pooled = self.global_pool(b)
            classification_output = self.classification_head(pooled)

        return regression_output, classification_output

"""## Loss Function

### Regression
"""

def create_mask(pred, target):
    """Create mask for valid pixels (for regression)"""
    return ~torch.isnan(target) & ~torch.isnan(pred)

class MaskedRMSELoss(nn.Module):
    """RMSE loss that handles NaN values in target (for regression)"""

    def __init__(self):
        super(MaskedRMSELoss, self).__init__()

    def forward(self, pred, target):
        """RMSE loss computed only on valid pixels"""
        mask = create_mask(pred, target)
        if mask.sum() == 0:
            return torch.tensor(0.0, device=pred.device, requires_grad=True)
        mse = ((pred[mask] - target[mask]) ** 2).mean()
        rmse = torch.sqrt(mse + 1e-8)
        return rmse

def compute_r2(pred, target):
    """Compute R² score for regression"""
    mask = create_mask(pred, target)

    if mask.sum() == 0:
        return 0.0

    pred_valid = pred[mask]
    target_valid = target[mask]

    ss_res = ((target_valid - pred_valid) ** 2).sum()
    ss_tot = ((target_valid - target_valid.mean()) ** 2).sum()
    r2 = (1 - (ss_res / ss_tot)).item() if ss_tot > 0 else 0.0

    return r2

class RobustRegressionLoss(nn.Module):
    """
    鲁棒回归损失函数 - 专为小patch设计，处理NaN、长尾分布、异常值

    基于以下论文思想：
    1. Huber Loss - 对异常值鲁棒
    2. Balanced MSE (BMSE) - 处理长尾分布 (Yang et al. 2021)
    3. Adaptive Wing Loss - 小目标自适应权重 (Wang et al. 2019)
    4. Focal Loss for Regression - 聚焦难样本 (Lin et al. 2017 思想扩展)
    5. Gradient Preservation - 保持空间结构

    适用场景：
    - 6×6 小patch CHM回归
    - Target含NaN值（自动mask）
    - 长尾高度分布
    - 包含测量异常值
    """

    def __init__(self,
                 base_loss='huber',                # 'mse', 'mae', 'huber', 'smooth_l1'
                 use_balanced=True,                # 平衡长尾分布
                 use_adaptive_weight=True,         # 自适应权重（难样本）
                 use_gradient_loss=False,          # 梯度保持（小patch效果有限）
                 use_variance_loss=True,           # ✨ 方差保持损失（防止过度平滑）
                 use_distribution_loss=False,      # 分布匹配损失（更强的方差约束）
                 huber_delta=1.0,                  # Huber loss 阈值
                 focal_alpha=0.5,                  # Focal 权重
                 focal_gamma=2.0,                  # Focal 聚焦参数
                 gradient_weight=0.1,              # 梯度损失权重
                 variance_weight=0.3,              # ✨ 方差损失权重
                 distribution_weight=0.2):         # 分布损失权重
        super(RobustRegressionLoss, self).__init__()

        self.base_loss = base_loss
        self.use_balanced = use_balanced
        self.use_adaptive_weight = use_adaptive_weight
        self.use_gradient_loss = use_gradient_loss
        self.use_variance_loss = use_variance_loss
        self.use_distribution_loss = use_distribution_loss
        self.huber_delta = huber_delta
        self.focal_alpha = focal_alpha
        self.focal_gamma = focal_gamma
        self.gradient_weight = gradient_weight
        self.variance_weight = variance_weight
        self.distribution_weight = distribution_weight

        # 基础损失函数
        if base_loss == 'mse':
            self.criterion = nn.MSELoss(reduction='none')
        elif base_loss == 'mae':
            self.criterion = nn.L1Loss(reduction='none')
        elif base_loss == 'huber':
            self.criterion = nn.HuberLoss(reduction='none', delta=huber_delta)
        elif base_loss == 'smooth_l1':
            self.criterion = nn.SmoothL1Loss(reduction='none', beta=huber_delta)

    def forward(self, pred, target):
        """
        Args:
            pred: (B, 1, H, W) 预测CHM
            target: (B, 1, H, W) 真实CHM（可能包含NaN）
        Returns:
            loss: scalar tensor
        """
        # 1. 创建有效像素mask（处理NaN）
        mask = create_mask(pred, target)

        if mask.sum() == 0:
            return torch.tensor(0.0, device=pred.device, requires_grad=True)

        # 2. 创建安全的target副本（用0填充NaN，后面会被mask掉）
        target_safe = torch.where(mask, target, torch.zeros_like(target))

        # 3. 计算基础损失（逐像素）
        base_loss = self.criterion(pred, target_safe)  # (B, 1, H, W)

        # 4. 应用Balanced MSE（处理长尾分布）
        if self.use_balanced:
            # 根据目标值大小动态调整权重
            # 对稀有的高值区域给予更大权重
            balance_weights = self._compute_balanced_weights(target_safe, mask)
            base_loss = base_loss * balance_weights

        # 5. 应用自适应权重（聚焦难样本）
        if self.use_adaptive_weight:
            # Focal-like weighting: 难预测的像素权重更大
            adaptive_weights = self._compute_adaptive_weights(pred, target_safe, mask)
            base_loss = base_loss * adaptive_weights

        # 6. Mask并归一化
        masked_loss = (base_loss * mask).sum() / mask.sum()

        total_loss = masked_loss

        # 7. ✨ 方差保持损失（防止预测过度平滑）
        if self.use_variance_loss:
            var_loss = self._variance_preservation_loss(pred, target_safe, mask)
            total_loss = total_loss + self.variance_weight * var_loss

        # 8. 分布匹配损失（更强的统计约束）
        if self.use_distribution_loss:
            dist_loss = self._distribution_matching_loss(pred, target_safe, mask)
            total_loss = total_loss + self.distribution_weight * dist_loss

        # 9. 添加梯度保持损失（可选，对小patch可能帮助有限）
        if self.use_gradient_loss:
            grad_loss = self._gradient_preservation_loss(pred, target_safe, mask)
            total_loss = total_loss + self.gradient_weight * grad_loss

        return total_loss

    def _compute_balanced_weights(self, target, mask):
        """
        Balanced MSE: 根据目标值分布计算平衡权重

        思想来自：Yang et al. "Delving into Deep Imbalanced Regression" (ICML 2021)

        对于长尾分布的回归任务：
        - 稀有的高值/低值区域权重更大
        - 常见的中等值区域权重较小
        """
        target_valid = target[mask]

        if len(target_valid) < 10:
            # 样本太少，返回均匀权重
            return torch.ones_like(target)

        # 将目标值分桶（bins）
        n_bins = 10
        target_min = target_valid.min()
        target_max = target_valid.max()

        if target_max - target_min < 1e-6:
            return torch.ones_like(target)

        # 只对有效区域计算bin
        # 先创建一个临时的bins tensor，无效位置设为0
        bins = torch.zeros_like(target, dtype=torch.long)
        bins_valid = ((target_valid - target_min) / (target_max - target_min + 1e-8) * (n_bins - 1)).long()
        bins_valid = torch.clamp(bins_valid, 0, n_bins - 1)
        bins[mask] = bins_valid

        # 统计每个bin的样本数（只统计有效样本）
        bin_counts = torch.bincount(bins[mask].flatten(), minlength=n_bins).float()
        bin_counts = torch.clamp(bin_counts, min=1.0)  # 避免除零

        # 计算逆频率权重（稀有bin权重大）
        total_samples = mask.sum().float()
        bin_weights = total_samples / (bin_counts * n_bins)

        # 平滑权重（避免极端值）
        bin_weights = torch.clamp(bin_weights, min=0.5, max=5.0)

        # 为每个像素分配权重（无效位置保持1.0）
        weights = torch.ones_like(target, dtype=torch.float32)
        for i in range(n_bins):
            weights[bins == i] = bin_weights[i]

        return weights

    def _compute_adaptive_weights(self, pred, target, mask):
        """
        自适应权重：对难预测的像素给予更大权重

        思想来自：
        1. Focal Loss (Lin et al. 2017) - 分类任务的难样本聚焦
        2. Adaptive Wing Loss (Wang et al. 2019) - 关键点检测的自适应权重

        难度定义：预测误差大的像素更难
        """
        # 只计算有效区域的误差
        error_valid = torch.abs(pred[mask] - target[mask])

        if len(error_valid) == 0:
            return torch.ones_like(pred)

        # 归一化到 [0, 1]
        error_max = error_valid.max() + 1e-8
        error_min = error_valid.min()

        # 创建完整的error tensor（无效位置设为0）
        error = torch.zeros_like(pred)
        error[mask] = error_valid

        # 归一化误差
        normalized_error = torch.clamp(error / error_max, 0, 1)

        # Focal-style权重: (1 - pt)^gamma
        # pt可以理解为"正确性"，error大则pt小
        pt = 1.0 - normalized_error

        # 计算权重
        focal_weight = self.focal_alpha * ((1 - pt) ** self.focal_gamma)

        # ✨ 减少归一化的影响（避免过度平滑）
        # 只对有效区域计算均值
        weight_mean = focal_weight[mask].mean()

        # 温和的归一化：不除以均值，而是除以较小的值
        # 这样保持权重的动态范围，避免过度平滑
        normalization_factor = torch.clamp(weight_mean, min=0.5, max=2.0)
        focal_weight = focal_weight / (normalization_factor + 1e-8)

        # 无效区域权重设为1.0（会被mask掉，不影响结果）
        focal_weight = torch.where(mask, focal_weight, torch.ones_like(focal_weight))

        return focal_weight

    def _gradient_preservation_loss(self, pred, target, mask):
        """
        梯度保持损失：保持空间结构

        对于6×6小patch，空间梯度信息很重要
        但由于尺寸小，效果可能有限
        """
        # 水平梯度
        pred_grad_x = pred[:, :, :, 1:] - pred[:, :, :, :-1]
        target_grad_x = target[:, :, :, 1:] - target[:, :, :, :-1]
        mask_x = mask[:, :, :, 1:] & mask[:, :, :, :-1]

        # 垂直梯度
        pred_grad_y = pred[:, :, 1:, :] - pred[:, :, :-1, :]
        target_grad_y = target[:, :, 1:, :] - target[:, :, :-1, :]
        mask_y = mask[:, :, 1:, :] & mask[:, :, :-1, :]

        grad_loss = 0.0
        if mask_x.sum() > 0:
            grad_loss += ((pred_grad_x - target_grad_x) ** 2 * mask_x).sum() / mask_x.sum()
        if mask_y.sum() > 0:
            grad_loss += ((pred_grad_y - target_grad_y) ** 2 * mask_y).sum() / mask_y.sum()

        return grad_loss / 2.0

    def _variance_preservation_loss(self, pred, target, mask):
        """
        方差保持损失：防止预测过度平滑

        问题：鲁棒损失（Huber）+ 加权机制 → 预测方差 << 目标方差
        解决：显式惩罚方差差异

        思想来自：
        - "Improving Distributional Similarity for Image-to-Image Translation"
        - 保持预测的统计特性与目标一致
        """
        pred_valid = pred[mask]
        target_valid = target[mask]

        if len(pred_valid) < 10:  # 样本太少，跳过
            return torch.tensor(0.0, device=pred.device)

        # 计算方差
        pred_var = pred_valid.var()
        target_var = target_valid.var()

        # 方差比率（避免除零）
        var_ratio = pred_var / (target_var + 1e-8)

        # 惩罚方差不匹配
        # 如果 pred_var < target_var，则 var_ratio < 1，loss > 0
        # 目标是 var_ratio ≈ 1
        var_loss = (var_ratio - 1.0) ** 2

        return var_loss

    def _distribution_matching_loss(self, pred, target, mask):
        """
        分布匹配损失：匹配预测和目标的完整统计分布

        比方差损失更强：同时匹配均值、方差、偏度

        用于：严重的预测过平滑问题
        """
        pred_valid = pred[mask]
        target_valid = target[mask]

        if len(pred_valid) < 10:
            return torch.tensor(0.0, device=pred.device)

        # 1. 均值差异
        mean_loss = (pred_valid.mean() - target_valid.mean()) ** 2

        # 2. 标准差差异
        std_loss = (pred_valid.std() - target_valid.std()) ** 2

        # 3. 分位数差异（鲁棒的分布匹配）
        # 匹配 10%, 50%, 90% 分位数
        quantiles = [0.1, 0.5, 0.9]
        quantile_loss = 0.0

        for q in quantiles:
            pred_q = torch.quantile(pred_valid, q)
            target_q = torch.quantile(target_valid, q)
            quantile_loss += (pred_q - target_q) ** 2

        quantile_loss = quantile_loss / len(quantiles)

        # 组合损失（标准差权重更大，因为这是主要问题）
        dist_loss = 0.2 * mean_loss + 0.6 * std_loss + 0.2 * quantile_loss

        return dist_loss


class QuantileLoss(nn.Module):
    """
    分位数损失：对异常值极度鲁棒

    论文：Koenker & Bassett (1978) "Regression Quantiles"

    优点：
    - 不受异常值影响
    - 可以预测不确定性（多个分位数）
    - 适合长尾分布

    用法：预测多个分位数（如0.1, 0.5, 0.9），0.5为中位数预测
    """

    def __init__(self, quantiles=[0.1, 0.5, 0.9]):
        super(QuantileLoss, self).__init__()
        self.quantiles = quantiles

    def forward(self, pred, target):
        """
        Args:
            pred: (B, C, H, W) 其中 C = len(quantiles)
            target: (B, 1, H, W)
        """
        mask = create_mask(pred, target)

        if mask.sum() == 0:
            return torch.tensor(0.0, device=pred.device, requires_grad=True)

        # 创建安全的target副本
        target_safe = torch.where(mask, target, torch.zeros_like(target))

        total_loss = 0.0

        for i, q in enumerate(self.quantiles):
            if pred.shape[1] > 1:
                pred_q = pred[:, i:i+1]
            else:
                pred_q = pred

            errors = target_safe - pred_q

            # 分位数损失：max(q * e, (q-1) * e)
            loss = torch.max(q * errors, (q - 1) * errors)
            loss = (loss * mask).sum() / mask.sum()
            total_loss += loss

        return total_loss / len(self.quantiles)

"""### Classification"""

class ClassificationLoss(nn.Module):
    """Cross-entropy loss for classification (no NaN handling needed)"""

    def __init__(self, weight=None):
        super(ClassificationLoss, self).__init__()
        self.criterion = nn.CrossEntropyLoss(weight=weight)

    def forward(self, pred, target):
        """
        Args:
            pred: (B, num_classes) - logits
            target: (B,) - class indices
        """
        return self.criterion(pred, target)

def compute_accuracy(pred, target):
    """Compute classification accuracy"""
    pred_labels = torch.argmax(pred, dim=1)
    correct = (pred_labels == target).sum().item()
    total = target.size(0)
    return correct / total if total > 0 else 0.0

def compute_class_weights(labels, power=1.5):
    labels = np.array(labels)
    class_counts = np.bincount(labels)
    n_classes = len(class_counts)

    # Simple inverse frequency: weight_i = max_count / count_i
    max_count = class_counts.max()
    weights = (max_count / class_counts) ** power

    print(f"\nClass weights (power={power}):")
    for i, (count, weight) in enumerate(zip(class_counts, weights)):
        print(f"  Class {i:2d}: samples={count:4d}, weight={weight:6.2f}")

    return torch.FloatTensor(weights)

class FocalLoss(nn.Module):
    """
    Focal Loss for handling class imbalance
    Reference: Lin et al. "Focal Loss for Dense Object Detection" (ICCV 2017)

    FL(p_t) = -α_t * (1 - p_t)^γ * log(p_t)
    """

    def __init__(self, alpha=None, gamma=2.0):
        """
        Args:
            alpha: Class weights (tensor of shape [num_classes]) or None
            gamma: Focusing parameter (default: 2.0)
                   γ=0 → standard cross-entropy
                   γ=2 → strongly down-weight easy examples
            reduction: 'mean' or 'sum'
        """
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, pred, target):
        """
        Args:
            pred: (B, num_classes) - logits
            target: (B,) - class indices
        """
        # Get probabilities
        logpt = nn.functional.log_softmax(pred, dim=1)
        pt = torch.exp(logpt)

        # Get log probability of correct class
        logpt = logpt.gather(1, target.view(-1, 1)).view(-1)
        pt = pt.gather(1, target.view(-1, 1)).view(-1)

        # Apply focal term: (1 - pt)^gamma
        focal_term = (1 - pt) ** self.gamma

        # Apply class weights if provided
        if self.alpha is not None:
            if self.alpha.device != pred.device:
                self.alpha = self.alpha.to(pred.device)
            alpha_t = self.alpha.gather(0, target)
            focal_term = alpha_t * focal_term

        # Compute loss
        loss = -focal_term * logpt

        return loss.mean()

"""### Multitask"""

class MultitaskLoss(nn.Module):
    """Combined loss for multitask learning"""

    def __init__(self, reg_weight=1.0, cls_weight=1.0):
        super(MultitaskLoss, self).__init__()
        self.regression_loss = MaskedRMSELoss()
        self.classification_loss = FocalLoss(alpha=class_weights, gamma=2.0).to(device)
        self.reg_weight = reg_weight
        self.cls_weight = cls_weight

    def forward(self, reg_pred, cls_pred, reg_target, cls_target):
        reg_loss = self.regression_loss(reg_pred, reg_target)
        cls_loss = self.classification_loss(cls_pred, cls_target)
        total_loss = self.reg_weight * reg_loss + self.cls_weight * cls_loss
        return total_loss, reg_loss, cls_loss

"""## Functions

### Regression
"""

def train_regression(model, train_loader, criterion, optimizer, device, epoch=0):
    model.train()
    total_loss = 0
    total_valid_ratio = 0
    n_batches = 0

    pbar = tqdm(train_loader, desc=f"Training {epoch+1}")
    for data, target in pbar:
        data, target = data.to(device), target.to(device)

        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        mask = create_mask(output, target)
        valid_ratio = mask.sum().item() / target.numel() if target.numel() > 0 else 0.0

        total_loss += loss.item()
        total_valid_ratio += valid_ratio
        n_batches += 1

        pbar.set_postfix({
            'RMSE': f'{loss.item():.4f}',
            'valid': f'{valid_ratio*100:.1f}%'
        })

    return total_loss / n_batches, total_valid_ratio / n_batches

def evaluate_regression(model, loader, criterion, device):
    """Evaluate regression model with comprehensive metrics"""
    model.eval()
    total_rmse = 0
    n_batches = 0

    # 收集所有预测值和真实值用于计算全局 R²
    all_preds = []
    all_targets = []

    with torch.no_grad():
        pbar = tqdm(loader, desc="Evaluating")
        for data, target in pbar:
            data, target = data.to(device), target.to(device)
            output = model(data)

            rmse = criterion(output, target)  # loss就是RMSE
            total_rmse += rmse.item()
            n_batches += 1

            # 收集有效的预测值和目标值
            mask = create_mask(output, target)
            if mask.sum() > 0:
                all_preds.append(output[mask].cpu())
                all_targets.append(target[mask].cpu())

            pbar.set_postfix({
                'RMSE': f'{rmse.item():.4f}'
            })

    # 在整个数据集上计算 R²
    if len(all_preds) > 0:
        all_preds = torch.cat(all_preds)
        all_targets = torch.cat(all_targets)

        ss_res = ((all_targets - all_preds) ** 2).sum()
        ss_tot = ((all_targets - all_targets.mean()) ** 2).sum()
        global_r2 = (1 - (ss_res / ss_tot)).item() if ss_tot > 0 else 0.0
    else:
        global_r2 = 0.0

    return total_rmse / n_batches, global_r2

"""### Classification"""

def train_classification(model, train_loader, criterion, optimizer, device, epoch=0):
    """Train classification model"""
    model.train()
    total_loss = 0
    total_acc = 0
    n_batches = 0

    pbar = tqdm(train_loader, desc=f"Training {epoch+1}")
    for data, target in pbar:
        data, target = data.to(device), target.to(device)

        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        acc = compute_accuracy(output, target)
        total_loss += loss.item()
        total_acc += acc
        n_batches += 1

        pbar.set_postfix({
            'Loss': f'{loss.item():.4f}',
            'Acc': f'{acc*100:.1f}%'
        })

    return total_loss / n_batches, total_acc / n_batches

def evaluate_classification(model, loader, criterion, device):
    """Evaluate classification model"""
    model.eval()
    total_loss = 0
    total_acc = 0
    n_batches = 0

    with torch.no_grad():
        pbar = tqdm(loader, desc="Evaluating")
        for data, target in pbar:
            data, target = data.to(device), target.to(device)
            output = model(data)

            loss = criterion(output, target)
            acc = compute_accuracy(output, target)

            total_loss += loss.item()
            total_acc += acc
            n_batches += 1

            pbar.set_postfix({
                'Loss': f'{loss.item():.4f}',
                'Acc': f'{acc*100:.1f}%'
            })

    return total_loss / n_batches, total_acc / n_batches

def evaluate_classification(model, loader, criterion, device, detailed=False, label_mapping=None):
    model.eval()
    total_loss = 0
    total_acc = 0
    n_batches = 0

    all_preds = []
    all_labels = []

    with torch.no_grad():
        pbar = tqdm(loader, desc="Evaluating")
        for data, target in pbar:
            data, target = data.to(device), target.to(device)
            output = model(data)

            loss = criterion(output, target)
            acc = compute_accuracy(output, target)

            total_loss += loss.item()
            total_acc += acc
            n_batches += 1

            if detailed:
                preds = torch.argmax(output, dim=1)
                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(target.cpu().numpy())

            pbar.set_postfix({
                'Loss': f'{loss.item():.4f}',
                'Acc': f'{acc*100:.1f}%'
            })

    avg_loss = total_loss / n_batches
    avg_acc = total_acc / n_batches

    if not detailed:
        return avg_loss, avg_acc

    # Detailed evaluation
    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)

    # Print results
    print(f"\n{'='*70}")
    print(f"CLASSIFICATION TEST RESULTS")
    print(f"{'='*70}")
    print(f"Loss: {avg_loss:.4f}")
    print(f"Accuracy: {avg_acc*100:.2f}%")

    # Get label names
    if label_mapping and 'idx_to_label' in label_mapping:
        idx_to_label = label_mapping['idx_to_label']
        # Convert string keys to int if needed
        if isinstance(list(idx_to_label.keys())[0], str):
            idx_to_label = {int(k): v for k, v in idx_to_label.items()}
        target_names = [idx_to_label.get(i, f'Class_{i}') for i in range(len(idx_to_label))]
    else:
        target_names = None

    # Confusion Matrix
    cm = confusion_matrix(all_labels, all_preds)

    fig, ax = plt.subplots(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=target_names if target_names else 'auto',
                yticklabels=target_names if target_names else 'auto')
    ax.set_title('Confusion Matrix')
    ax.set_ylabel('True Label')
    ax.set_xlabel('Predicted Label')
    if target_names:
        plt.xticks(rotation=45, ha='right')
        plt.yticks(rotation=0)
    plt.tight_layout()
    plt.savefig('classification_confusion_matrix.png', dpi=300, bbox_inches='tight')
    plt.show()

    # Classification Report
    print(f"\n{'='*70}")
    print("DETAILED CLASSIFICATION REPORT")
    print(f"{'='*70}")
    print(classification_report(all_labels, all_preds,
                                target_names=target_names,
                                zero_division=0))

    # Per-class Accuracy
    class_acc = cm.diagonal() / cm.sum(axis=1)
    print(f"\n{'='*70}")
    print("PER-CLASS ACCURACY")
    print(f"{'='*70}")
    for i, acc in enumerate(class_acc):
        count = cm.sum(axis=1)[i]
        label_name = target_names[i] if target_names else f'Class {i}'
        print(f"{label_name:20s}: {acc*100:5.2f}% ({int(count):4d} samples)")

    # Summary
    print(f"\n{'='*70}")
    print("SUMMARY")
    print(f"{'='*70}")
    print(f"Overall Accuracy: {avg_acc*100:.2f}%")
    print(f"Mean Per-Class Acc: {class_acc.mean()*100:.2f}%")

    if target_names:
        print(f"Best Class: {target_names[class_acc.argmax()]} ({class_acc.max()*100:.2f}%)")
        print(f"Worst Class: {target_names[class_acc.argmin()]} ({class_acc.min()*100:.2f}%)")
    else:
        print(f"Best Class: {class_acc.argmax()} ({class_acc.max()*100:.2f}%)")
        print(f"Worst Class: {class_acc.argmin()} ({class_acc.min()*100:.2f}%)")

    # Check for never predicted classes
    unique_preds = set(all_preds)
    unique_labels = set(all_labels)
    never_predicted = unique_labels - unique_preds
    if never_predicted:
        print(f"\n⚠️ WARNING: Classes never predicted: {sorted(never_predicted)}")
        if target_names:
            never_pred_names = [target_names[i] for i in sorted(never_predicted)]
            print(f"   ({', '.join(never_pred_names)})")

    return avg_loss, avg_acc, all_preds, all_labels

"""### Multitask"""

def train_multitask(model, train_loader, criterion, optimizer, device, epoch=0):
    """Train multitask model"""
    model.train()
    total_loss = 0
    total_reg_loss = 0
    total_cls_loss = 0
    total_r2 = 0
    total_acc = 0
    n_batches = 0

    pbar = tqdm(train_loader, desc=f"Training {epoch+1}")
    for data, (reg_target, cls_target) in pbar:
        data = data.to(device)
        reg_target = reg_target.to(device)
        cls_target = cls_target.to(device)

        optimizer.zero_grad()
        reg_output, cls_output = model(data)
        loss, reg_loss, cls_loss = criterion(reg_output, cls_output, reg_target, cls_target)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        r2 = compute_r2(reg_output, reg_target)
        acc = compute_accuracy(cls_output, cls_target)

        total_loss += loss.item()
        total_reg_loss += reg_loss.item()
        total_cls_loss += cls_loss.item()
        total_r2 += r2
        total_acc += acc
        n_batches += 1

        pbar.set_postfix({
            'Loss': f'{loss.item():.4f}',
            'R²': f'{r2:.3f}',
            'Acc': f'{acc*100:.1f}%'
        })

    return (total_loss / n_batches, total_reg_loss / n_batches,
            total_cls_loss / n_batches, total_r2 / n_batches, total_acc / n_batches)

def evaluate_multitask(model, loader, criterion, device):
    """Evaluate multitask model"""
    model.eval()
    total_loss = 0
    total_reg_loss = 0
    total_cls_loss = 0
    total_r2 = 0
    total_acc = 0
    n_batches = 0

    with torch.no_grad():
        pbar = tqdm(loader, desc="Evaluating")
        for data, (reg_target, cls_target) in pbar:
            data = data.to(device)
            reg_target = reg_target.to(device)
            cls_target = cls_target.to(device)

            reg_output, cls_output = model(data)
            loss, reg_loss, cls_loss = criterion(reg_output, cls_output, reg_target, cls_target)

            r2 = compute_r2(reg_output, reg_target)
            acc = compute_accuracy(cls_output, cls_target)

            total_loss += loss.item()
            total_reg_loss += reg_loss.item()
            total_cls_loss += cls_loss.item()
            total_r2 += r2
            total_acc += acc
            n_batches += 1

            pbar.set_postfix({
                'Loss': f'{loss.item():.4f}',
                'R²': f'{r2:.3f}',
                'Acc': f'{acc*100:.1f}%'
            })

    return (total_loss / n_batches, total_reg_loss / n_batches,
            total_cls_loss / n_batches, total_r2 / n_batches, total_acc / n_batches)

"""## Regression

### Train
"""

train_loader, val_loader, test_loader = create_dataloaders(
    train_h5=BASE_DIR + 'train_data.h5',
    test_h5=BASE_DIR + 'test_data.h5',
    batch_size=16,
    num_workers=4,
    val_ratio=0.1,
    )

model = RegressionUNet(
    in_channels=3,
    out_channels=1,
    base_channels=32,
    dropout=0.01
    ).to(device)
criterion = MaskedRMSELoss()  # Masked RMSE loss (handles NaN in target)
optimizer = optim.Adam(model.parameters(), lr=0.0001)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=3
)

print(f"\nModel Configuration:")
print(f"  Input channels: 3 (VV, VH, VV/VH)")
print(f"  Output channels: 1 (CHM)")
print(f"  Total parameters: {sum(p.numel() for p in model.parameters()):,}")

patience_counter = 0
early_stop_patience = 5
history = {
    'train_loss': [], 'val_loss': [], 'val_r2': [],
    'train_valid_ratio': [], 'learning_rate': []
}

num_epochs = 50
best_val_loss = float('inf')

print(f"\nTraining for {num_epochs} epochs...")

for epoch in range(num_epochs):
    train_loss, train_valid_ratio = train_regression(
        model, train_loader, criterion, optimizer, device, epoch
    )

    val_loss, val_r2 = evaluate_regression(model, val_loader, criterion, device)

    # Record history
    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['val_r2'].append(val_r2)
    history['train_valid_ratio'].append(train_valid_ratio)
    history['learning_rate'].append(optimizer.param_groups[0]['lr'])

    # Update learning rate
    scheduler.step(val_loss)

    print(f"Epoch {epoch+1}/{num_epochs}:")
    print(f"  Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}")
    print(f"  Val R²: {val_r2:.4f}, LR: {optimizer.param_groups[0]['lr']:.6f}")

    # Save best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), 'best_regression_model.pth')
        print(f"  ✓ Best model saved (val_loss: {best_val_loss:.4f})")
        patience_counter = 0
    else:
        patience_counter += 1

    if patience_counter >= early_stop_patience:
        print(f"Early stopping at epoch {epoch+1}")
        break

# Plot training history
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

# Loss plot
axes[0].plot(history['train_loss'], label='Train Loss', color='blue')
axes[0].plot(history['val_loss'], label='Val Loss', color='red')
axes[0].set_title('Training and Validation Loss')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')
axes[0].legend()
axes[0].grid(True)

# Learning rate plot
axes[1].plot(history['learning_rate'], label='Learning Rate', color='orange')
axes[1].set_title('Learning Rate Schedule')
axes[1].set_title('Learning Rate Schedule')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Learning Rate')
axes[1].set_yscale('log')
axes[1].legend()
axes[1].grid(True)

plt.tight_layout()
plt.show()

"""### Test"""

model.load_state_dict(torch.load('best_regression_model.pth'))
test_rmse, test_r2 = evaluate_regression(model, test_loader, criterion, device)

print(f"\nTest Results:")
print(f"  RMSE: {test_rmse:.4f}")
print(f"  R2: {test_r2:.4f}")

def visualize_test_samples(model, test_loader, device, num_samples=4, start_index=0):

    model.eval()
    samples = []

    with torch.no_grad():
        for i, (inputs, targets) in enumerate(test_loader):
            batch_start = i * test_loader.batch_size
            batch_end = batch_start + inputs.shape[0]

            if batch_end <= start_index or batch_start >= start_index + num_samples:
                continue

            inputs, targets = inputs.to(device), targets.to(device)
            preds = model(inputs)

            for j in range(inputs.shape[0]):
                idx = batch_start + j
                if start_index <= idx < start_index + num_samples:
                    samples.append({
                        'idx': idx,
                        'input': inputs[j].cpu().numpy(),  # (3, H, W)
                        'target': targets[j, 0].cpu().numpy(),
                        'pred': preds[j, 0].cpu().numpy()
                    })

            if len(samples) >= num_samples:
                break

    viridis_nan = cm.get_cmap('viridis').copy()
    viridis_nan.set_bad(color='red')

    fig, axes = plt.subplots(num_samples, 5, figsize=(10, 2*num_samples))
    if num_samples == 1:
        axes = axes.reshape(1, -1)

    for i, s in enumerate(samples):
        # inputs
        for j, name in enumerate(['VV', 'VH', 'VV/VH']):
            axes[i, j].imshow(s['input'][j], cmap='gray', aspect='auto')
            axes[i, j].set_title(f"Sample {s['idx']}: {name}", fontsize=8)
            axes[i, j].axis('off')

        # target
        valid_mask = ~np.isnan(s['target'])
        valid_pct = valid_mask.sum() / valid_mask.size * 100
        im_target = axes[i, 3].imshow(s['target'], cmap=viridis_nan, aspect='auto')
        fig.colorbar(im_target, ax=axes[i, 3], fraction=0.046, pad=0.04)
        axes[i, 3].set_title(f"Sample {s['idx']}: True CHM", fontsize=6)
        axes[i, 3].axis('off')

        pred_masked = s['pred'].copy()
        pred_masked[~valid_mask] = np.nan
        im_pred = axes[i, 4].imshow(pred_masked, cmap=viridis_nan, aspect='auto')
        fig.colorbar(im_pred, ax=axes[i, 4], fraction=0.046, pad=0.04)
        axes[i, 4].set_title(f"Sample {s['idx']}: Predicted CHM", fontsize=8)

        if valid_mask.any():
            rmse = np.sqrt(np.mean((s['target'][valid_mask] - s['pred'][valid_mask]) ** 2))
            axes[i, 4].text(0.5, -0.1, f"RMSE: {rmse:.2f}m",
                           transform=axes[i, 4].transAxes, ha='center', fontsize=6, color='red')
        axes[i, 4].axis('off')

    plt.tight_layout()
    plt.suptitle(f'Test Predictions (Index {start_index}-{start_index+num_samples-1})',
                 fontsize=10, y=1.002)
    plt.show()

    return samples

_ = visualize_test_samples(model, test_loader, device, num_samples=4, start_index=105)

def plot_scatter_prediction(model, loader, device, loader_name="Train"):
    model.eval()
    y_true = []
    y_pred = []

    with torch.no_grad():
        for inputs, targets in tqdm(loader, desc=f"Collecting {loader_name} predictions"):
            inputs, targets = inputs.to(device), targets.to(device)
            preds = model(inputs)

            mask = create_mask(preds, targets)
            y_true.append(targets[mask].cpu().numpy())
            y_pred.append(preds[mask].cpu().numpy())

    # combine all batches
    y_true = np.concatenate(y_true)
    y_pred = np.concatenate(y_pred)

    plt.figure(figsize=(5, 5))
    plt.scatter(y_true, y_pred, s=1, alpha=0.3)
    plt.xlabel("True CHM", fontsize=8)
    plt.ylabel("Predicted CHM", fontsize=8)
    plt.title(f"{loader_name} Set: True vs Predicted CHM", fontsize=10)

    min_val, max_val = y_true.min(), y_true.max() # opt
    plt.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2)

    plt.legend(fontsize=10)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(f'scatter_plot_{loader_name.lower()}.png', dpi=300, bbox_inches='tight')
    plt.show()

    print(f"\n{loader_name} Set stats:")
    print(f"  True: [{y_true.min():.2f}, {y_true.max():.2f}]")
    print(f"  Pred: [{y_pred.min():.2f}, {y_pred.max():.2f}]")
    print(f"  STD: {y_pred.std():.2f}")
    print(f"  Mean: {y_pred.mean():.2f}")

    return y_true, y_pred

y_true_train, y_pred_train = plot_scatter_prediction(model, train_loader, device, "Train")

"""### check"""

def plot_gradients(model, save_path='gradients.png'):
    """
    简洁的梯度可视化 - 一张图看清所有层的梯度

    用法：
        loss.backward()
        plot_gradients(model)
        optimizer.step()
    """
    grads = []
    names = []

    for name, param in model.named_parameters():
        if param.grad is not None and param.requires_grad:
            grad = param.grad.abs().mean().item()
            grads.append(grad)
            names.append(name.split('.')[-1][:15])  # 只取最后一部分，截断过长名字

    if len(grads) == 0:
        print("No gradients found!")
        return

    # 绘制
    plt.figure(figsize=(12, 4))
    plt.bar(range(len(grads)), grads, color='steelblue', alpha=0.7)
    plt.xticks(range(len(grads)), names, rotation=45, ha='right', fontsize=8)
    plt.ylabel('Mean |Gradient|')
    plt.title(f'Gradient Flow (mean={np.mean(grads):.2e}, max={np.max(grads):.2e})')
    plt.yscale('log')
    plt.grid(True, alpha=0.3, axis='y')
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()
    plt.close()
    print(f"✓ Gradient plot saved to {save_path}")


def check_gradients(model):
    """
    快速检查梯度健康状态 - 一行打印所有信息

    用法：
        loss.backward()
        check_gradients(model)
    """
    grads = [p.grad.abs() for p in model.parameters() if p.grad is not None]

    if len(grads) == 0:
        print("❌ No gradients!")
        return False

    all_grads = torch.cat([g.flatten() for g in grads])
    mean_g = all_grads.mean().item()
    max_g = all_grads.max().item()
    min_g = all_grads.min().item()

    has_nan = torch.isnan(all_grads).any().item()
    has_inf = torch.isinf(all_grads).any().item()

    status = "❌" if (has_nan or has_inf or mean_g < 1e-8) else "✓"
    print(f"{status} Gradients: mean={mean_g:.2e}, max={max_g:.2e}, min={min_g:.2e}, "
          f"NaN={has_nan}, Inf={has_inf}")

    return not (has_nan or has_inf)


def diagnose_regression_performance(model, loader, device, num_samples=100):
    """
    诊断回归性能，分析 R² 低的可能原因
    """
    model.eval()

    all_preds = []
    all_targets = []
    sample_count = 0

    print("\n" + "="*70)
    print("REGRESSION PERFORMANCE DIAGNOSTICS")
    print("="*70)

    with torch.no_grad():
        for data, target in loader:
            data, target = data.to(device), target.to(device)
            output = model(data)

            mask = create_mask(output, target)
            if mask.sum() > 0:
                all_preds.append(output[mask].cpu().numpy())
                all_targets.append(target[mask].cpu().numpy())
                sample_count += mask.sum().item()

            if sample_count >= num_samples:
                break

    if len(all_preds) == 0:
        print("No valid predictions found!")
        return

    all_preds = np.concatenate(all_preds)
    all_targets = np.concatenate(all_targets)

    # 基本统计
    print(f"\n1. Data Statistics (n={len(all_preds)} pixels):")
    print(f"   Target CHM:")
    print(f"     Mean:   {all_targets.mean():.2f} m")
    print(f"     Std:    {all_targets.std():.2f} m")
    print(f"     Range:  [{all_targets.min():.2f}, {all_targets.max():.2f}] m")
    print(f"   Predicted CHM:")
    print(f"     Mean:   {all_preds.mean():.2f} m")
    print(f"     Std:    {all_preds.std():.2f} m")
    print(f"     Range:  [{all_preds.min():.2f}, {all_preds.max():.2f}] m")

    # 误差分析
    errors = all_targets - all_preds
    print(f"\n2. Error Analysis:")
    print(f"   MAE:  {np.abs(errors).mean():.2f} m")
    print(f"   RMSE: {np.sqrt((errors**2).mean()):.2f} m")
    print(f"   Error range: [{errors.min():.2f}, {errors.max():.2f}] m")

    # R² 分析
    ss_res = ((all_targets - all_preds) ** 2).sum()
    ss_tot = ((all_targets - all_targets.mean()) ** 2).sum()
    r2 = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0.0

    print(f"\n3. R² Analysis:")
    print(f"   R² = {r2:.4f}")
    print(f"   SS_res (残差平方和):  {ss_res:.2f}")
    print(f"   SS_tot (总平方和):    {ss_tot:.2f}")
    print(f"   Ratio (SS_res/SS_tot): {ss_res/ss_tot:.4f}")

    # 可能的问题诊断
    print(f"\n4. Possible Issues:")
    if all_preds.std() < all_targets.std() * 0.3:
        print(f"   ⚠️  Predictions are too smooth (std_pred << std_target)")
        print(f"      Model may be under-predicting variance")

    if abs(all_preds.mean() - all_targets.mean()) > all_targets.std() * 0.5:
        print(f"   ⚠️  Large bias: mean prediction differs from mean target")
        print(f"      Bias: {all_preds.mean() - all_targets.mean():.2f} m")

    if r2 < 0:
        print(f"   ⚠️  Negative R²: Model performs worse than mean prediction!")
        print(f"      The model is not learning effectively")
    elif r2 < 0.3:
        print(f"   ⚠️  Very low R²: Model explains < 30% of variance")
        print(f"      Consider: 1) More training, 2) Better architecture, 3) Data quality")

    # 相关性检查
    correlation = np.corrcoef(all_targets, all_preds)[0, 1]
    print(f"\n5. Correlation Analysis:")
    print(f"   Pearson correlation: {correlation:.4f}")
    if correlation < 0.5:
        print(f"   ⚠️  Low correlation: Model predictions poorly match targets")

    print("="*70 + "\n")

    return {
        'r2': r2,
        'mae': np.abs(errors).mean(),
        'rmse': np.sqrt((errors**2).mean()),
        'correlation': correlation,
        'target_stats': {'mean': all_targets.mean(), 'std': all_targets.std()},
        'pred_stats': {'mean': all_preds.mean(), 'std': all_preds.std()}
    }

diagnose_regression_performance(model, test_loader, device)

"""## Classification

### Train
"""

def load_label_mapping(mapping_path):
    """Load label mapping from JSON file"""
    with open(mapping_path, 'r') as f:
        mapping = json.load(f)

    print(f"\nLabel mapping: {mapping_path.split('/')[-1]}")
    print(f"  Number of classes: {mapping['n_classes']}")
    print(f"  Example labels: {list(mapping['label_to_idx'].items())[:5]}")

    return mapping

label_mapping = load_label_mapping(BASE_DIR + 'label_mapping.json')
n_classes = label_mapping['n_classes']

train_loader, val_loader, test_loader = create_dataloaders(
    train_h5=BASE_DIR + 'train_data.h5',
    test_h5=BASE_DIR + 'test_data.h5',
    task='classification',
    batch_size=64,
    num_workers=4,
    val_ratio=0.1
    )

train_labels = []
for _, labels in train_loader:
    train_labels.extend(labels.numpy())
train_labels = np.array(train_labels)

class_weights = compute_class_weights(train_labels, power=1.0)
print(f"Class weights: {class_weights.numpy()}")

model = ClassificationUNet(
    in_channels=3,
    num_classes=n_classes,
    base_channels=32,
    dropout=0.1
).to(device)

# criterion = ClassificationLoss(weight=class_weights).to(device)
criterion = FocalLoss(alpha=cls_weights, gamma=2.0).to(device)

optimizer = optim.Adam(model.parameters(), lr=0.0001)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.3, patience=2  # 更激进
)
# scheduler = optim.lr_scheduler.ReduceLROnPlateau(
#     optimizer, mode='min', factor=0.5, patience=3
# )

print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")

num_epochs = 50
best_val_loss = float('inf')
best_val_acc = 0
patience_counter = 0
early_stop_patience = 5
history_cls = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

for epoch in range(num_epochs):
    train_loss, train_acc = train_classification(
        model, train_loader, criterion, optimizer, device, epoch
    )
    val_loss, val_acc = evaluate_classification(
        model, val_loader, criterion, device
    )

    history_cls['train_loss'].append(train_loss)
    history_cls['train_acc'].append(train_acc)
    history_cls['val_loss'].append(val_loss)
    history_cls['val_acc'].append(val_acc)

    scheduler.step(val_loss)

    print(f"Epoch {epoch+1}/{num_epochs}: "
          f"Train Loss={train_loss:.4f}, Train Acc={train_acc*100:.2f}%\n"
          f"Val Loss={val_loss:.4f}, Val Acc={val_acc*100:.2f}%, LR={optimizer.param_groups[0]['lr']:.6f}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        patience_counter = 0
        torch.save(model.state_dict(), 'best_classification_model.pth')
        print(f"  ✓ Best model saved (acc: {best_val_acc*100:.2f}%)")

    else:
        patience_counter += 1

    if patience_counter >= early_stop_patience:
        print(f"Early stopping at epoch {epoch+1}")
        break

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

ax1.plot(history_cls['train_loss'], 'b-', label='Train')
ax1.plot(history_cls['val_loss'], 'r-', label='Val')
ax1.set_title('Loss')
ax1.set_xlabel('Epoch')
ax1.legend()
ax1.grid(True)

ax2.plot(history_cls['train_acc'], 'b-', label='Train')
ax2.plot(history_cls['val_acc'], 'r-', label='Val')
ax2.set_title('Accuracy')
ax2.set_xlabel('Epoch')
ax2.legend()
ax2.grid(True)

plt.tight_layout()
plt.savefig('classification_history.png', dpi=300, bbox_inches='tight')
plt.show()

"""### Test"""

model.load_state_dict(torch.load('best_classification_model.pth'))
evaluate_classification(
    model, test_loader, criterion, device,
    detailed=True, label_mapping=label_mapping
)

"""## Multitask

### Train
"""

train_loader, val_loader, test_loader = create_dataloaders(
    train_h5=BASE_DIR + 'train_data.h5',
    test_h5=BASE_DIR + 'test_data.h5',
    task='multitask',
    batch_size=128,
    num_workers=4,
    val_ratio=0.1
)

# model_mt = MultitaskUNet(
#     in_channels=3, out_channels=1, num_classes=n_classes,
#     base_channels=32, dropout=0.1
# ).to(device)

model_mt = DilatedMultitaskNet(
    in_channels=3, out_channels=1, num_classes=n_classes,
    base_channels=128, dropout=0.2
).to(device)

print(f"\nMultitaskUNet parameters: {sum(p.numel() for p in model_mt.parameters()):,}")

criterion = MultitaskLoss(reg_weight=1.0, cls_weight=3.0)
optimizer = optim.AdamW(model_mt.parameters(), lr=0.001, weight_decay=1e-4)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=3,
)

num_epochs_mt = 150
best_val_loss_mt = float('inf')

history_mt = {
    'train_loss': [], 'train_reg_loss': [], 'train_cls_loss': [],
    'train_r2': [], 'train_acc': [],
    'val_loss': [], 'val_reg_loss': [], 'val_cls_loss': [],
    'val_r2': [], 'val_acc': []
}

print(f"\nTraining for {num_epochs_mt} epochs...")

for epoch in range(num_epochs_mt):
    # Training
    train_loss, train_reg_loss, train_cls_loss, train_r2, train_acc = train_multitask(
        model_mt, train_loader, criterion, optimizer, device, epoch
    )

    # Validation
    val_loss, val_reg_loss, val_cls_loss, val_r2, val_acc = evaluate_multitask(
        model_mt, val_loader, criterion, device
    )

    # Save history
    history_mt['train_loss'].append(train_loss)
    history_mt['train_reg_loss'].append(train_reg_loss)
    history_mt['train_cls_loss'].append(train_cls_loss)
    history_mt['train_r2'].append(train_r2)
    history_mt['train_acc'].append(train_acc)

    history_mt['val_loss'].append(val_loss)
    history_mt['val_reg_loss'].append(val_reg_loss)
    history_mt['val_cls_loss'].append(val_cls_loss)
    history_mt['val_r2'].append(val_r2)
    history_mt['val_acc'].append(val_acc)

    scheduler.step(val_loss)

    print(f"Epoch {epoch+1}/{num_epochs_mt}:")
    print(f"  Train: Loss={train_loss:.4f} (Reg={train_reg_loss:.4f}, Cls={train_cls_loss:.4f})")
    print(f"         R²={train_r2:.3f}, Acc={train_acc*100:.1f}%")
    print(f"  Val:   Loss={val_loss:.4f} (Reg={val_reg_loss:.4f}, Cls={val_cls_loss:.4f})")
    print(f"         R²={val_r2:.3f}, Acc={val_acc*100:.1f}%")
    print(f"         LR={optimizer.param_groups[0]['lr']:.6f}")

    if val_loss < best_val_loss_mt:
        best_val_loss_mt = val_loss
        torch.save(model_mt.state_dict(), 'best_multitask_model.pth')
        print(f"  ✓ Saved (loss: {best_val_loss_mt:.4f})")

# Plot training history
fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# Total Loss
axes[0, 0].plot(history_mt['train_loss'], 'b-', label='Train')
axes[0, 0].plot(history_mt['val_loss'], 'r-', label='Val')
axes[0, 0].set_title('Total Loss')
axes[0, 0].set_xlabel('Epoch')
axes[0, 0].legend()
axes[0, 0].grid(True)

# Regression Loss
axes[0, 1].plot(history_mt['train_reg_loss'], 'b-', label='Train')
axes[0, 1].plot(history_mt['val_reg_loss'], 'r-', label='Val')
axes[0, 1].set_title('Regression Loss (RMSE)')
axes[0, 1].set_xlabel('Epoch')
axes[0, 1].legend()
axes[0, 1].grid(True)

# Classification Loss
axes[0, 2].plot(history_mt['train_cls_loss'], 'b-', label='Train')
axes[0, 2].plot(history_mt['val_cls_loss'], 'r-', label='Val')
axes[0, 2].set_title('Classification Loss')
axes[0, 2].set_xlabel('Epoch')
axes[0, 2].legend()
axes[0, 2].grid(True)

# R² Score
axes[1, 0].plot(history_mt['train_r2'], 'b-', label='Train')
axes[1, 0].plot(history_mt['val_r2'], 'r-', label='Val')
axes[1, 0].set_title('R² Score')
axes[1, 0].set_xlabel('Epoch')
axes[1, 0].legend()
axes[1, 0].grid(True)

# Accuracy
axes[1, 1].plot(history_mt['train_acc'], 'b-', label='Train')
axes[1, 1].plot(history_mt['val_acc'], 'r-', label='Val')
axes[1, 1].set_title('Classification Accuracy')
axes[1, 1].set_xlabel('Epoch')
axes[1, 1].legend()
axes[1, 1].grid(True)

# Task Loss Comparison
axes[1, 2].plot(history_mt['val_reg_loss'], 'b-', label='Regression', linewidth=2)
axes[1, 2].plot(history_mt['val_cls_loss'], 'r-', label='Classification', linewidth=2)
axes[1, 2].set_title('Task Loss Comparison (Val)')
axes[1, 2].set_xlabel('Epoch')
axes[1, 2].legend()
axes[1, 2].grid(True)

plt.tight_layout()
plt.savefig('multitask_history.png', dpi=300, bbox_inches='tight')
plt.show()

"""### Test"""

model_mt.load_state_dict(torch.load('best_multitask_model.pth'))

test_loss, test_reg_loss, test_cls_loss, test_r2, test_acc = evaluate_multitask(
    model_mt, test_loader, criterion, device
)

print(f"\nTest Results:")
print(f"  Total Loss:    {test_loss:.4f}")
print(f"  Regression:    RMSE={test_reg_loss:.4f}, R²={test_r2:.3f}")
print(f"  Classification: Loss={test_cls_loss:.4f}, Acc={test_acc*100:.2f}%")

model_mt.eval()
all_reg_preds = []
all_reg_targets = []

with torch.no_grad():
    for inputs, (reg_target, _) in test_loader:
        inputs = inputs.to(device)
        reg_target = reg_target.to(device)

        reg_output, _ = model_mt(inputs)

        mask = create_mask(reg_output, reg_target)
        if mask.sum() > 0:
            all_reg_preds.extend(reg_output[mask].cpu().numpy())
            all_reg_targets.extend(reg_target[mask].cpu().numpy())

all_reg_preds = np.array(all_reg_preds)
all_reg_targets = np.array(all_reg_targets)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

rmse = np.sqrt(mean_squared_error(all_reg_targets, all_reg_preds))
mae = mean_absolute_error(all_reg_targets, all_reg_preds)
r2 = r2_score(all_reg_targets, all_reg_preds)

print(f"RMSE: {rmse:.4f}")
print(f"MAE:  {mae:.4f}")
print(f"R²:   {r2:.4f}")

all_cls_preds = []
all_cls_targets = []

with torch.no_grad():
    for inputs, (_, cls_target) in test_loader:
        inputs = inputs.to(device)
        _, cls_output = model_mt(inputs)

        preds = torch.argmax(cls_output, dim=1)
        all_cls_preds.extend(preds.cpu().numpy())
        all_cls_targets.extend(cls_target.numpy())

all_cls_preds = np.array(all_cls_preds)
all_cls_targets = np.array(all_cls_targets)

# Use the classification evaluation utility
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(all_cls_targets, all_cls_preds)
print(f"\nOverall Accuracy: {accuracy*100:.2f}%")

# Per-class accuracy using label names
idx_to_label = label_mapping['idx_to_label']
print("\nPer-Class Accuracy:")
for i in range(n_classes):
    mask = all_cls_targets == i
    if mask.sum() > 0:
        class_acc = (all_cls_preds[mask] == i).sum() / mask.sum()
        class_name = idx_to_label[str(i)]
        print(f"  {class_name:15s}: {class_acc*100:5.2f}% ({mask.sum():4d} samples)")

# Classification report
print("\nClassification Report:")
target_names = [idx_to_label[str(i)] for i in range(n_classes)]
print(classification_report(
    all_cls_targets, all_cls_preds,
    target_names=target_names,
    zero_division=0
))

# Confusion matrix
cm = confusion_matrix(all_cls_targets, all_cls_preds)
print("\nConfusion Matrix:")
print(cm)

print("\n" + "="*70)
print("MULTITASK TRAINING AND TESTING COMPLETED")
print("="*70)


