# -*- coding: utf-8 -*-
"""“baseline_clf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hUpI2o72B4JrJck2i20zOg9mGFKemm5Z
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import h5py
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
from torch.utils.data import Dataset, DataLoader, random_split
from torch.optim.lr_scheduler import OneCycleLR
import json
from torch.optim.lr_scheduler import CosineAnnealingLR
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                            f1_score, classification_report, average_precision_score,
                            confusion_matrix)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

from google.colab import drive
drive.mount('/content/drive')
BASE_DIR = "/content/drive/MyDrive/data/"

"""## Data Preprocessing

### Label
"""

def load_label_mapping(mapping_path):
    with open(mapping_path, 'r') as f:
        mapping = json.load(f)

    print(f"mapping: {mapping_path}")
    print(f"  classes: {mapping['n_classes']}")
    print(f"  labels: {list(mapping['label_to_idx'].items())[:]}")

    return mapping

label_mapping = load_label_mapping(BASE_DIR+'label_mapping.json')
n_classes = label_mapping['n_classes']

"""### Augmentation"""

class D4Augmentation:
    TRANSFORMS = [
        lambda x: x,                                              # 0: identity
        lambda x: torch.rot90(x, k=-1, dims=(-2, -1)),           # 1: 90° CW
        lambda x: torch.rot90(x, k=2, dims=(-2, -1)),            # 2: 180°
        lambda x: torch.rot90(x, k=1, dims=(-2, -1)),            # 3: 270° CW
        lambda x: torch.flip(x, dims=[-1]),                      # 4: horizontal flip
        lambda x: torch.flip(x, dims=[-2]),                      # 5: vertical flip
        lambda x: torch.transpose(x, -2, -1),                    # 6: transpose
        lambda x: torch.rot90(torch.transpose(x, -2, -1), k=2, dims=(-2, -1))  # 7: anti-transpose
    ]

    @staticmethod
    def apply_transform(image: torch.Tensor, transform_idx: int) -> torch.Tensor:
        return D4Augmentation.TRANSFORMS[transform_idx](image)

class H5Dataset(Dataset):
    def __init__(self, h5_path: str):
        self.h5f = h5py.File(h5_path, 'r')
        self.images = self.h5f['images']
        self.labels = self.h5f['labels']
        self.valid_indices = self._filter_nan_samples()
        self.n_samples = len(self.valid_indices)

        print(f"H5Dataset initialized: {h5_path}")
        print(f"  Total samples: {len(self.labels)}")
        print(f"  Valid samples: {self.n_samples}")

    def _filter_nan_samples(self):
        valid_indices = []
        for idx in range(len(self.h5f['labels'])):
            img = self.images[idx].astype(np.float32)
            input_bands = img[1:3]  # VV, VH
            if not np.isnan(input_bands).any():
                valid_indices.append(idx)
        return valid_indices

    def __len__(self):
        return self.n_samples

    def __getitem__(self, idx):
        actual_idx = self.valid_indices[idx]
        img = self.images[actual_idx].astype(np.float32).copy()
        input_bands = img[1:3]  # VV, VH
        label = int(self.labels[actual_idx])

        vv = torch.from_numpy(input_bands[0])  # [H, W]
        vh = torch.from_numpy(input_bands[1])  # [H, W]
        image = torch.stack([vv, vh], dim=0)   # [2, H, W]

        label = torch.tensor(label, dtype=torch.long)
        return image, label

    def get_filename(self, idx):
        actual_idx = self.valid_indices[idx]
        return self.images.file['filenames'][actual_idx].decode('utf-8')

    def get_label_name(self, idx):
        actual_idx = self.valid_indices[idx]
        return self.images.file['label_names'][actual_idx].decode('utf-8')

    def close(self):
        if hasattr(self, 'h5f'):
            self.h5f.close()

    def __del__(self):
        self.close()

class ExplicitD4Dataset(Dataset):
    def __init__(self, base_dataset: Dataset):
        self.base_dataset = base_dataset
        self.n_transforms = 8
        self.original_size = len(base_dataset)
        self.total_size = self.original_size * self.n_transforms

        print(f"  原始样本数: {self.original_size:,}")
        print(f"  扩展后样本数: {self.total_size:,}")

    def __len__(self):
        return self.total_size

    def __getitem__(self, idx):
        original_idx = idx // self.n_transforms
        transform_idx = idx % self.n_transforms
        image, label = self.base_dataset[original_idx]
        image = D4Augmentation.apply_transform(image, transform_idx)
        return image, label

def create_dataloaders_with_explicit_d4(
    train_h5: str,
    test_h5: str,
    batch_size: int = 128,
    num_workers: int = 4,
    val_ratio: float = 0.1
):
    base_train_dataset = H5Dataset(train_h5)
    test_dataset = H5Dataset(test_h5)

    original_train_size = len(base_train_dataset)
    val_size = int(original_train_size * val_ratio)
    train_size = original_train_size - val_size

    print(f"  原始训练集: {original_train_size:,} samples")
    print(f"  验证集比例: {val_ratio:.1%}")
    print(f"  划分后训练集: {train_size:,} samples ({train_size/original_train_size:.1%})")
    print(f"  划分后验证集: {val_size:,} samples ({val_size/original_train_size:.1%})")

    random_seed = 42
    torch.manual_seed(random_seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(random_seed)
        torch.cuda.manual_seed_all(random_seed)

    train_indices, val_indices = random_split(
        range(original_train_size),
        [train_size, val_size]
    )

    train_subset_base = torch.utils.data.Subset(base_train_dataset, train_indices.indices)
    train_dataset_8x = ExplicitD4Dataset(train_subset_base)
    print(f"  扩展后训练集: {len(train_dataset_8x):,} samples")
    val_dataset = torch.utils.data.Subset(base_train_dataset, val_indices.indices)
    print(f"  验证集: {len(val_dataset):,} samples (无D4扩展)")

    train_loader = DataLoader(
        train_dataset_8x,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    # ============ 7. 打印摘要 ============
    print(f"\n{'='*70}")
    print("数据加载器创建完成！")
    print(f"{'='*70}")
    print(f"\n训练集:")
    print(f"  原始样本: {train_size:,}")
    print(f"  扩展后样本: {len(train_dataset_8x):,} (8x)")
    print(f"  批次数: {len(train_loader):,}")
    print(f"  增强方式: 显式D4扩展（每个样本→8个版本）")

    print(f"\n验证集:")
    print(f"  样本数: {len(val_dataset):,}")
    print(f"  批次数: {len(val_loader):,}")
    print(f"  增强方式: 无增强")

    print(f"\n测试集:")
    print(f"  样本数: {len(test_dataset):,}")
    print(f"  批次数: {len(test_loader):,}")
    print(f"  增强方式: 无增强")

    print(f"\n训练效率:")
    print(f"  每个epoch迭代次数: {len(train_loader):,}")
    print(f"  相比无增强提升: {len(train_dataset_8x) / train_size:.1f}x")
    print(f"  预计训练时间: 约为原来的 8 倍")

    print(f"\n{'='*70}\n")

    return train_loader, val_loader, test_loader

import h5py
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, random_split

class H5Dataset(Dataset):
    def __init__(self, h5_path: str, compute_stats: bool = False):
        self.h5f = h5py.File(h5_path, 'r')
        self.images = self.h5f['images']
        self.labels = self.h5f['labels']
        self.valid_indices = self._filter_nan_samples()
        self.n_samples = len(self.valid_indices)

        # 归一化参数（将在外部设置）
        self.mean = None
        self.std = None

        if compute_stats:
            self._compute_normalization_stats()

        print(f"H5Dataset: {h5_path}")
        print(f"  Valid samples: {self.n_samples:,}")

    def _filter_nan_samples(self):
        """过滤包含NaN的样本"""
        valid_indices = []
        for idx in range(len(self.h5f['labels'])):
            img = self.images[idx].astype(np.float32)
            input_bands = img[1:3]  # VV, VH
            if not np.isnan(input_bands).any():
                valid_indices.append(idx)
        return valid_indices

    def _compute_normalization_stats(self):
        """计算整个数据集的均值和标准差"""
        print("  Computing normalization statistics...")

        # 采样计算（如果数据集太大）
        sample_size = min(self.n_samples, 10000)
        sample_indices = np.random.choice(self.n_samples, sample_size, replace=False)

        all_vv = []
        all_vh = []

        for i in sample_indices:
            actual_idx = self.valid_indices[i]
            img = self.images[actual_idx].astype(np.float32)
            input_bands = img[1:3]
            all_vv.append(input_bands[0].flatten())
            all_vh.append(input_bands[1].flatten())

        all_vv = np.concatenate(all_vv)
        all_vh = np.concatenate(all_vh)

        # 计算每个通道的均值和标准差
        mean_vv, std_vv = np.mean(all_vv), np.std(all_vv)
        mean_vh, std_vh = np.mean(all_vh), np.std(all_vh)

        self.mean = torch.tensor([mean_vv, mean_vh], dtype=torch.float32).view(2, 1, 1)
        self.std = torch.tensor([std_vv, std_vh], dtype=torch.float32).view(2, 1, 1)

        # 防止除零
        self.std = torch.clamp(self.std, min=1e-6)

        print(f"  Normalization stats computed:")
        print(f"    VV - mean: {mean_vv:.4f}, std: {std_vv:.4f}")
        print(f"    VH - mean: {mean_vh:.4f}, std: {std_vh:.4f}")

    def set_normalization(self, mean, std):
        """设置归一化参数（用于验证集/测试集）"""
        self.mean = mean
        self.std = std

    def __len__(self):
        return self.n_samples

    def __getitem__(self, idx):
        actual_idx = self.valid_indices[idx]
        img = self.images[actual_idx].astype(np.float32).copy()
        input_bands = img[1:3]  # VV, VH
        label = int(self.labels[actual_idx])

        vv = torch.from_numpy(input_bands[0])  # [H, W]
        vh = torch.from_numpy(input_bands[1])  # [H, W]
        image = torch.stack([vv, vh], dim=0)   # [2, H, W]

        # 归一化
        if self.mean is not None and self.std is not None:
            image = (image - self.mean) / self.std

        label = torch.tensor(label, dtype=torch.long)
        return image, label

    def close(self):
        if hasattr(self, 'h5f'):
            self.h5f.close()

    def __del__(self):
        self.close()


class D4Augmentation:
    """D4群增强（旋转+翻转的8种组合）"""

    @staticmethod
    def apply_transform(image, transform_idx):
        """
        应用D4变换
        transform_idx: 0-7
          0: 原始
          1-3: 旋转 90°, 180°, 270°
          4: 水平翻转
          5-7: 水平翻转 + 旋转 90°, 180°, 270°
        """
        if transform_idx == 0:
            return image
        elif transform_idx <= 3:
            # 旋转 k*90度
            return torch.rot90(image, k=transform_idx, dims=[1, 2])
        else:
            # 先水平翻转，再旋转
            image = torch.flip(image, dims=[2])
            if transform_idx > 4:
                image = torch.rot90(image, k=transform_idx-4, dims=[1, 2])
            return image


class ExplicitD4Dataset(Dataset):
    """显式D4扩展数据集"""

    def __init__(self, base_dataset: Dataset):
        self.base_dataset = base_dataset
        self.n_transforms = 8
        self.original_size = len(base_dataset)
        self.total_size = self.original_size * self.n_transforms

    def __len__(self):
        return self.total_size

    def __getitem__(self, idx):
        original_idx = idx // self.n_transforms
        transform_idx = idx % self.n_transforms
        image, label = self.base_dataset[original_idx]
        image = D4Augmentation.apply_transform(image, transform_idx)
        return image, label


def create_dataloaders_with_explicit_d4(
    train_h5: str,
    test_h5: str,
    batch_size: int = 128,
    num_workers: int = 4,
    val_ratio: float = 0.1
):
    """
    创建带归一化和D4增强的数据加载器
    """
    print(f"\n{'='*70}")
    print("Creating DataLoaders with Normalization & D4 Augmentation")
    print(f"{'='*70}\n")

    # 1. 加载训练集并计算归一化参数
    print("Step 1: Loading training set and computing normalization stats...")
    base_train_dataset = H5Dataset(train_h5, compute_stats=True)

    # 2. 加载测试集并应用训练集的归一化参数
    print("\nStep 2: Loading test set...")
    test_dataset = H5Dataset(test_h5, compute_stats=False)
    test_dataset.set_normalization(base_train_dataset.mean, base_train_dataset.std)

    # 3. 划分训练集和验证集
    print(f"\nStep 3: Splitting train/val with ratio {val_ratio:.1%}...")
    original_train_size = len(base_train_dataset)
    val_size = int(original_train_size * val_ratio)
    train_size = original_train_size - val_size

    torch.manual_seed(42)
    train_indices, val_indices = random_split(
        range(original_train_size),
        [train_size, val_size]
    )

    # 4. 创建子集
    train_subset_base = torch.utils.data.Subset(base_train_dataset, train_indices.indices)
    val_dataset = torch.utils.data.Subset(base_train_dataset, val_indices.indices)

    # 5. 对训练集应用D4扩展
    print("\nStep 4: Applying D4 augmentation to training set...")
    train_dataset_8x = ExplicitD4Dataset(train_subset_base)
    print(f"  Train samples: {train_size:,} → {len(train_dataset_8x):,} (8x)")
    print(f"  Val samples: {len(val_dataset):,} (no augmentation)")

    # 6. 创建数据加载器
    print("\nStep 5: Creating DataLoaders...")
    train_loader = DataLoader(
        train_dataset_8x,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    # 7. 验证归一化效果
    print("\nStep 6: Verifying normalization...")
    _verify_normalization(train_loader)

    # 8. 打印摘要
    print(f"\n{'='*70}")
    print("DataLoaders Created Successfully!")
    print(f"{'='*70}")
    print(f"Train: {len(train_dataset_8x):,} samples ({len(train_loader):,} batches)")
    print(f"Val:   {len(val_dataset):,} samples ({len(val_loader):,} batches)")
    print(f"Test:  {len(test_dataset):,} samples ({len(test_loader):,} batches)")
    print(f"{'='*70}\n")

    return train_loader, val_loader, test_loader


def _verify_normalization(dataloader, num_batches=5):
    """验证归一化是否正确应用"""
    print("  Verifying normalization on sample batches...")

    all_data = []
    for i, (data, _) in enumerate(dataloader):
        if i >= num_batches:
            break
        all_data.append(data)

    all_data = torch.cat(all_data, dim=0)  # [N, 2, H, W]

    # 统计
    vv_channel = all_data[:, 0, :, :]
    vh_channel = all_data[:, 1, :, :]

    print(f"  Normalized data statistics:")
    print(f"    VV channel - mean: {vv_channel.mean():.6f}, std: {vv_channel.std():.6f}, "
          f"min: {vv_channel.min():.6f}, max: {vv_channel.max():.6f}")
    print(f"    VH channel - mean: {vh_channel.mean():.6f}, std: {vh_channel.std():.6f}, "
          f"min: {vh_channel.min():.6f}, max: {vh_channel.max():.6f}")

    # 检查是否归一化
    if abs(vv_channel.mean()) < 0.1 and abs(vh_channel.mean()) < 0.1:
        if 0.8 < vv_channel.std() < 1.2 and 0.8 < vh_channel.std() < 1.2:
            print(f"  ✓ Normalization verified: data is properly normalized")
            return True

    print(f"  ⚠️  Warning: data may not be properly normalized")
    return False

"""### Dataloader"""

train_loader, val_loader, test_loader = create_dataloaders_with_explicit_d4(
    train_h5=BASE_DIR + 'train_data.h5',
    test_h5=BASE_DIR + 'test_data.h5',
    batch_size=128,
    num_workers=4,
    val_ratio=0.1  # 10%验证集，90%训练集
)

"""### Model"""

import torch
import torch.nn as nn
import torch.nn.functional as F


class ImprovedResidualBlock(nn.Module):
    """PreActivation 残差块 - ResNet V2 风格，梯度更稳定"""

    def __init__(self, in_channels, out_channels, stride=1, dropout=0.2):
        super().__init__()

        # PreActivation: BN → Activation → Conv
        self.bn1 = nn.BatchNorm2d(in_channels)
        self.conv1 = nn.Conv2d(in_channels, out_channels, 3, stride=stride, padding=1, bias=False)

        self.bn2 = nn.BatchNorm2d(out_channels)
        self.conv2 = nn.Conv2d(out_channels, out_channels, 3, padding=1, bias=False)

        self.dropout = nn.Dropout2d(dropout) if dropout > 0 else nn.Identity()
        self.activation = nn.GELU()

        # Shortcut
        self.shortcut = nn.Identity()
        if stride != 1 or in_channels != out_channels:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_channels, out_channels, 1, stride=stride, bias=False),
                nn.BatchNorm2d(out_channels)
            )

    def forward(self, x):
        # PreActivation 风格
        out = self.bn1(x)
        out = self.activation(out)
        out = self.conv1(out)

        out = self.bn2(out)
        out = self.activation(out)
        out = self.dropout(out)
        out = self.conv2(out)

        # 残差连接（无缩放）
        residual = self.shortcut(x)
        out = out + residual

        return out


class OptimizedCNN(nn.Module):
    """优化后的 CNN - 针对梯度流问题"""

    def __init__(self, in_channels=2, num_classes=15, base_channels=64, dropout=0.3):
        super().__init__()

        # Stem - 减少第一层的学习率（通过初始化）
        self.stem = nn.Sequential(
            nn.Conv2d(in_channels, base_channels, 3, padding=1, bias=False),
            nn.BatchNorm2d(base_channels, momentum=0.01),
            nn.GELU()
        )

        # 残差块 - 使用改进版本
        self.layer1 = ImprovedResidualBlock(
            base_channels, base_channels*2,
            stride=1, dropout=dropout
        )

        self.layer2 = ImprovedResidualBlock(
            base_channels*2, base_channels*4,
            stride=2, dropout=dropout * 0.7  # ← 降低 stride 层的 dropout
        )

        self.layer3 = ImprovedResidualBlock(
            base_channels*4, base_channels*8,
            stride=1, dropout=dropout * 0.5  # ← 深层更少 dropout
        )

        # 全局池化 - 简化（去掉额外卷积）
        self.global_pool = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten()
        )

        # 分类器 - 增强学习能力
        self.classifier = nn.Sequential(
            nn.Linear(base_channels*8, base_channels*4),  # ← 增加中间层宽度
            nn.BatchNorm1d(base_channels*4, momentum=0.01),
            nn.GELU(),
            nn.Dropout(dropout * 1.2),

            nn.Linear(base_channels*4, base_channels*2),
            nn.BatchNorm1d(base_channels*2, momentum=0.01),
            nn.GELU(),
            nn.Dropout(dropout),

            nn.Linear(base_channels*2, num_classes)
        )

        # 初始化
        self._initialize_weights()

    def _initialize_weights(self):
        """改进的权重初始化"""
        for name, m in self.named_modules():
            if isinstance(m, nn.Conv2d):
                # Stem 使用较小的初始化
                if 'stem' in name:
                    nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                    m.weight.data *= 0.5  # ← 减少第一层初始权重
                else:
                    nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')

            elif isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)

            elif isinstance(m, (nn.BatchNorm2d, nn.BatchNorm1d)):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        x = self.stem(x)
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.global_pool(x)
        x = self.classifier(x)
        return x

class CNN(nn.Module):
    def __init__(self, in_channels=2, num_classes=15, base_channels=64, dropout=0.1):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(in_channels, base_channels, 3, padding=1),
            nn.BatchNorm2d(base_channels),
            nn.ReLU(inplace=True),
            nn.Dropout2d(dropout),

            nn.Conv2d(base_channels, base_channels*2, 3, padding=1),
            nn.BatchNorm2d(base_channels*2),
            nn.ReLU(inplace=True),
            nn.Dropout2d(dropout),
            nn.MaxPool2d(2, 2),  # 6×6 → 3×3

            nn.Conv2d(base_channels*2, base_channels*4, 3, padding=1),
            nn.BatchNorm2d(base_channels*4),
            nn.ReLU(inplace=True),
            nn.Dropout2d(dropout),

            nn.Conv2d(base_channels*4, base_channels*8, 3, padding=0),
            nn.BatchNorm2d(base_channels*8),
            nn.ReLU(inplace=True),
            nn.AdaptiveAvgPool2d(1)
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Dropout(dropout),
            nn.Linear(base_channels*8, num_classes)
        )

    def forward(self, x):
        x = self.features(x)      # [B, base_channels*8, 1, 1]
        x = self.classifier(x)    # [B, num_classes]
        return x

"""### Loss"""

class ClassificationLoss(nn.Module):
    def __init__(self, weight=None):
        super(ClassificationLoss, self).__init__()
        self.criterion = nn.CrossEntropyLoss()

    def forward(self, pred, target):
        return self.criterion(pred, target)

class PseudoHuberLoss(nn.Module):
    """
    Pseudo-Huber Loss for Classification
    PH(x) = δ² * (√(1 + (x/δ)²) - 1)

    更平滑、对异常值更鲁棒的损失函数

    Args:
        delta: 控制损失曲线形状的参数 (default: 1.0)
               - delta→0: 接近L1 loss (更鲁棒)
               - delta→∞: 接近L2 loss (更平滑)
        alpha: Per-class weights tensor [num_classes] or None
        reduction: 'mean', 'sum', or 'none'

    特性:
        - 在|x|<δ时类似L2 (平滑，易优化)
        - 在|x|>δ时类似L1 (鲁棒，对异常值不敏感)
        - 处处可微，优化友好
    """
    def __init__(self, delta=1.0, alpha=None, reduction='mean'):
        super(PseudoHuberLoss, self).__init__()
        self.delta = delta
        self.reduction = reduction

        if alpha is None:
            self.alpha = None
        elif isinstance(alpha, (float, int)):
            self.alpha = torch.tensor([alpha])
        else:
            self.alpha = alpha if isinstance(alpha, torch.Tensor) else torch.tensor(alpha)

    def forward(self, inputs, targets):
        """
        Args:
            inputs: [B, C] logits
            targets: [B] class indices
        """
        # 先计算交叉熵作为基础误差
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')  # [B]

        # 应用Pseudo-Huber变换: δ² * (√(1 + (x/δ)²) - 1)
        delta_sq = self.delta ** 2
        normalized_loss = ce_loss / self.delta
        ph_loss = delta_sq * (torch.sqrt(1 + normalized_loss ** 2) - 1)

        # 应用类别权重
        if self.alpha is not None:
            if self.alpha.device != inputs.device:
                self.alpha = self.alpha.to(inputs.device)
            alpha_t = self.alpha[targets]
            ph_loss = alpha_t * ph_loss

        # 应用reduction
        if self.reduction == 'mean':
            return ph_loss.mean()
        elif self.reduction == 'sum':
            return ph_loss.sum()
        else:
            return ph_loss

def compute_class_weights(dataloader, num_classes, method='effective', beta=0.9999):
    """
    计算类别权重以处理不平衡数据

    Args:
        dataloader: 训练数据加载器
        num_classes: 类别数量
        method: 权重计算方法
            - 'inverse': 逆频率 weight = 1 / count
            - 'balanced': 平衡权重 weight = total / (n_classes * count)
            - 'effective': 有效样本数方法 weight = (1-beta) / (1-beta^count)
        beta: effective方法的超参数，默认0.9999

    Returns:
        torch.Tensor: 归一化的类别权重 [num_classes]
    """
    class_counts = torch.zeros(num_classes, dtype=torch.long)

    print(f"\n{'='*70}")
    print("统计训练集标签分布...")
    print(f"{'='*70}")

    for _, labels in tqdm(dataloader, desc="Counting labels"):
        for label in labels:
            class_counts[label.item()] += 1

    total_samples = class_counts.sum().item()

    # 计算权重
    if method == 'inverse':
        # 逆频率: w_i = 1 / count_i
        weights = 1.0 / class_counts.float()
    elif method == 'balanced':
        # 平衡权重: w_i = total / (n_classes * count_i)
        weights = total_samples / (num_classes * class_counts.float())
    elif method == 'effective':
        # 有效样本数: w_i = (1 - beta) / (1 - beta^count_i)
        effective_num = 1.0 - torch.pow(beta, class_counts.float())
        weights = (1.0 - beta) / effective_num
    else:
        raise ValueError(f"Unknown method: {method}")

    # 归一化权重，使平均权重为1
    weights = weights / weights.mean()

    # 打印标签分布和权重
    print(f"\n类别分布与权重统计:")
    print(f"{'Class':<6} {'Count':>10} {'Percentage':>12} {'Weight':>12}")
    print(f"{'-'*70}")

    for i in range(num_classes):
        count = class_counts[i].item()
        percentage = 100.0 * count / total_samples
        weight = weights[i].item()
        print(f"{i:<6} {count:>10,} {percentage:>11.2f}% {weight:>12.4f}")

    print(f"{'-'*70}")
    print(f"Total: {total_samples:>10,} {'100.00%':>12}")
    print(f"\n权重统计:")
    print(f"  Method: {method}")
    if method == 'effective':
        print(f"  Beta: {beta}")
    print(f"  Min weight: {weights.min().item():.4f}")
    print(f"  Max weight: {weights.max().item():.4f}")
    print(f"  Mean weight: {weights.mean().item():.4f}")
    print(f"  Weight ratio (max/min): {(weights.max() / weights.min()).item():.2f}x")
    print(f"{'='*70}\n")

    return weights

# 计算类别权重
class_weights = compute_class_weights(
    train_loader,
    num_classes=n_classes,
    method='effective',  # 推荐使用有效样本数方法
    beta=0.9999
)

class FocalLoss(nn.Module):
    """
    Focal Loss with per-class weights
    FL(p_t) = -α_t * w_c * (1 - p_t)^γ * log(p_t)

    Args:
        alpha: Per-class weights tensor [num_classes] or None
        gamma: Focusing parameter (default: 2.0)
               - gamma=0: equivalent to weighted CrossEntropyLoss
               - gamma=2: recommended (from RetinaNet paper)
        reduction: 'mean', 'sum', or 'none'
    """
    def __init__(self, alpha=None, gamma=2.0, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.reduction = reduction

        if alpha is None:
            self.alpha = None
        elif isinstance(alpha, (float, int)):
            self.alpha = torch.tensor([alpha])
        else:
            self.alpha = alpha if isinstance(alpha, torch.Tensor) else torch.tensor(alpha)

    def forward(self, inputs, targets):
        """
        Args:
            inputs: [B, C] logits
            targets: [B] class indices
        """
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        p_t = torch.exp(-ce_loss)
        focal_term = (1 - p_t) ** self.gamma

        if self.alpha is not None:
            if self.alpha.device != inputs.device:
                self.alpha = self.alpha.to(inputs.device)
            alpha_t = self.alpha[targets]
            focal_loss = alpha_t * focal_term * ce_loss
        else:
            focal_loss = focal_term * ce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        else:
            return focal_loss

"""### Functions"""

def warmup_lr_scheduler(optimizer, warmup_epochs, base_lr):
    def lr_lambda(epoch):
        if epoch < warmup_epochs:
            return (epoch + 1) / warmup_epochs
        return 1.0
    return optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)

def compute_accuracy(pred, target):
    pred_labels = torch.argmax(pred, dim=1)  # [B]
    correct = (pred_labels == target).float()  # [B]
    total = target.size(0)
    accuracy = correct.sum().item() / total if total > 0 else 0.0
    return accuracy

def compute_map(pred, target, num_classes):
    probs = torch.softmax(pred, dim=1).cpu().numpy()  # [B, num_classes]
    target_np = target.cpu().numpy()  # [B]
    if len(target_np) == 0:
        return 0.0
    target_onehot = np.eye(num_classes)[target_np]  # [B, num_classes]
    aps = []
    for i in range(num_classes):
        if target_onehot[:, i].sum() > 0:
            try:
                ap = average_precision_score(target_onehot[:, i], probs[:, i])
                aps.append(ap)
            except:
                continue
    return np.mean(aps) if len(aps) > 0 else 0.0

class GradientScaler:
    """在反向传播后、优化器更新前缩放梯度"""

    def __init__(self, layer_scales):
        """
        layer_scales: dict, 例如 {'features.0': 0.1}
        表示 features.0 的梯度缩放到 10%
        """
        self.layer_scales = layer_scales

    def scale_gradients(self, model):
        """缩放模型梯度"""
        for name, param in model.named_parameters():
            if param.grad is not None:
                for layer_key, scale in self.layer_scales.items():
                    if layer_key in name:
                        param.grad.data.mul_(scale)
                        break

def train_classification(model, train_loader, criterion, optimizer, device, epoch=0):
    model.train()
    total_loss = 0
    total_acc = 0
    n_batches = 0

    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}")

    for batch_idx, batch_data in enumerate(pbar):
        data, target = batch_data
        data = data.to(device)
        target = target.to(device)

        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        gradient_scaler = GradientScaler({
            'features.0': 0.05,  # ← 第一层梯度缩放到 5%
            'features.1': 0.3,   # ← 第二层缩放到 30%
        })
        gradient_scaler.scale_gradients(model)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        if batch_idx == len(train_loader) - 1:
            plot_gradient_flow(model)
        optimizer.step()
        scheduler.step()
        with torch.no_grad():
            acc = compute_accuracy(output, target)

        total_loss += loss.item()
        total_acc += acc
        n_batches += 1

        pbar.set_postfix({
            'Loss': f'{loss.item():.4f}',
            'Acc': f'{acc*100:.1f}%'
        })

    avg_loss = total_loss / n_batches
    avg_acc = total_acc / n_batches

    return avg_loss, avg_acc

def evaluate_classification(model, loader, criterion, device, num_classes):
    model.eval()

    total_loss = 0
    total_acc = 0
    all_preds = []
    all_targets = []
    n_batches = 0

    with torch.no_grad():
        pbar = tqdm(loader, desc="Evaluating")
        for batch_data in pbar:
            data, target = batch_data
            data = data.to(device)
            target = target.to(device)

            output = model(data)
            loss = criterion(output, target)
            acc = compute_accuracy(output, target)
            total_loss += loss.item()
            total_acc += acc
            n_batches += 1

            all_preds.append(output)
            all_targets.append(target)
            pbar.set_postfix({
                'Loss': f'{loss.item():.4f}',
                'Acc': f'{acc*100:.1f}%'
            })

    avg_loss = total_loss / n_batches
    avg_acc = total_acc / n_batches

    all_preds = torch.cat(all_preds, dim=0)
    all_targets = torch.cat(all_targets, dim=0)
    mAP = compute_map(all_preds, all_targets, num_classes)

    return avg_loss, avg_acc, mAP

"""### Train"""

model = OptimizedCNN(in_channels=2, num_classes=n_classes, base_channels=32, dropout=0.2).to(device)
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")

# criterion = ClassificationLoss()
criterion = FocalLoss(alpha=class_weights, gamma=2.0)
# criterion = PseudoHuberLoss(delta=0.5, alpha=class_weights)



optimizer = optim.AdamW(
    model.parameters(),
    lr=5e-5,              # Base learning rate
    betas=(0.9, 0.999),
    weight_decay=5e-5     # Weight decay
)

num_epochs = 100
warmup_epochs = 8
from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts
# scheduler = CosineAnnealingWarmRestarts(
#     optimizer,
#     T_0=10,        # 第一次重启周期
#     T_mult=2,      # 周期倍数（1=保持不变，2=每次翻倍）
#     eta_min=1e-7   # 最小学习率
# )
steps_per_epoch = len(train_loader)
total_steps = num_epochs * steps_per_epoch
scheduler = OneCycleLR(optimizer, max_lr=1e-4, total_steps=total_steps, pct_start=0.3)
warmup_scheduler = warmup_lr_scheduler(optimizer, warmup_epochs, 1e-8)

def plot_gradient_flow(model):
    """
    绘制梯度流图，检测梯度消失/爆炸
    横轴：层名称
    纵轴：梯度的平均绝对值
    """
    ave_grads = []
    max_grads = []
    layers = []

    for name, param in model.named_parameters():
        if param.grad is not None and "bias" not in name:  # 排除 bias
            layers.append(name)
            ave_grads.append(param.grad.abs().mean().cpu().item())
            max_grads.append(param.grad.abs().max().cpu().item())

    plt.figure(figsize=(14, 6))
    plt.bar(np.arange(len(max_grads)), max_grads, alpha=0.5, lw=1, color="c", label="max")
    plt.bar(np.arange(len(ave_grads)), ave_grads, alpha=0.5, lw=1, color="b", label="mean")

    plt.hlines(0, 0, len(ave_grads)+1, lw=2, color="k")
    plt.xticks(range(0, len(ave_grads), 1), layers, rotation=90, fontsize=8)
    plt.xlim(left=0, right=len(ave_grads))
    plt.ylim(bottom=-0.001, top=max(max_grads)*1.1)
    plt.xlabel("Layers")
    plt.ylabel("Average Gradient")
    plt.title("Gradient Flow Across Layers")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()

    # 检测问题
    if max(ave_grads) < 1e-5:
        plt.text(len(ave_grads)/2, max(max_grads)/2,
                "WARNING: Gradient Vanishing!",
                fontsize=16, color='red', weight='bold',
                bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7))
    elif max(ave_grads) > 1.0:
        plt.text(len(ave_grads)/2, max(max_grads)/2,
                "WARNING: Gradient Explosion!",
                fontsize=16, color='red', weight='bold',
                bbox=dict(boxstyle='round', facecolor='yellow', alpha=0.7))

    plt.savefig('gradient_flow.png', dpi=150, bbox_inches='tight')
    plt.show()

best_val_loss = float('inf')
best_val_acc = 0.0
best_val_map = 0.0
patience_counter = 0
early_stop_patience = 20

history = {
    'train_loss': [], 'train_acc': [],
    'val_loss': [], 'val_acc': [], 'val_map': [], 'lr': []
}

for epoch in range(num_epochs):
    train_loss, train_acc = train_classification(
        model, train_loader, criterion, optimizer, device, epoch
    )
    val_loss, val_acc, val_map = evaluate_classification(
        model, val_loader, criterion, device, n_classes
    )

    current_lr = optimizer.param_groups[0]['lr']
    if epoch < warmup_epochs:
        warmup_scheduler.step()
    else:
        scheduler.step()

    history['train_loss'].append(train_loss)
    history['train_acc'].append(train_acc)
    history['val_loss'].append(val_loss)
    history['val_acc'].append(val_acc)
    history['val_map'].append(val_map)
    history['lr'].append(current_lr)

    print(f"  Train Loss: {train_loss:.4f} | Train Acc: {train_acc*100:.2f}%")
    print(f"  Val Loss:   {val_loss:.4f} | Val Acc:   {val_acc*100:.2f}% | Val mAP: {val_map:.4f} | LR: {current_lr:.2e}")

    if val_loss < best_val_loss:
        best_val_map = val_map
        best_val_acc = val_acc
        best_val_loss = val_loss
        patience_counter = 0

        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'val_loss': val_loss,
            'val_acc': val_acc,
            'val_map': val_map,
            'history': history
        }, 'best_classification_model.pth')

        print(f" *Best model | mAP: {best_val_map:.4f}, Acc: {best_val_acc*100:.2f}%, Loss: {best_val_loss:.4f}\n")
    else:
        patience_counter += 1
        print(f"Patience: {patience_counter}/{early_stop_patience}\n")

    if patience_counter >= early_stop_patience:
        print(f"Early stopping triggered at epoch {epoch+1}")
        print(f"Best validation mAP: {best_val_map:.4f}")
        break

def plot_training_history(history):
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))

    axes[0, 0].plot(history['train_loss'], label='Train Loss')
    axes[0, 0].plot(history['val_loss'], label='Val Loss')
    axes[0, 0].set_xlabel('Epoch')
    axes[0, 0].set_ylabel('Loss')
    axes[0, 0].set_title('Training and Validation Loss')
    axes[0, 0].legend()
    axes[0, 0].grid(True)

    axes[0, 1].plot([x*100 for x in history['train_acc']], label='Train Acc')
    axes[0, 1].plot([x*100 for x in history['val_acc']], label='Val Acc')
    axes[0, 1].set_xlabel('Epoch')
    axes[0, 1].set_ylabel('Accuracy (%)')
    axes[0, 1].set_title('Training and Validation Accuracy')
    axes[0, 1].legend()
    axes[0, 1].grid(True)

    axes[1, 0].plot(history['val_map'], label='Val mAP', color='green')
    axes[1, 0].set_xlabel('Epoch')
    axes[1, 0].set_ylabel('mAP')
    axes[1, 0].set_title('Validation mAP')
    axes[1, 0].legend()
    axes[1, 0].grid(True)

    axes[1, 1].plot(history['lr'], label='Learning Rate', color='orange')
    axes[1, 1].set_xlabel('Epoch')
    axes[1, 1].set_ylabel('Learning Rate')
    axes[1, 1].set_title('Learning Rate Schedule')
    axes[1, 1].set_yscale('log')
    axes[1, 1].legend()
    axes[1, 1].grid(True)

    plt.tight_layout()
    plt.show()

plot_training_history(history)

"""### Test"""

print(f"\n{'='*70}")
print("Training Complete!")
print(f"{'='*70}")
print(f"Best Validation Results:")
print(f"  mAP: {best_val_map:.4f}")
print(f"  Accuracy: {best_val_acc*100:.2f}%")
print(f"  Loss: {best_val_loss:.4f}")
print(f"{'='*70}\n")

"""### Test Evaluation with Per-Class Analysis"""

def evaluate_with_per_class_analysis(model, loader, criterion, device, label_mapping=None):
    """
    Comprehensive evaluation with per-class analysis and confusion matrix
    """
    model.eval()
    total_loss = 0
    total_acc = 0
    n_batches = 0

    all_preds = []
    all_labels = []

    with torch.no_grad():
        pbar = tqdm(loader, desc="Evaluating on Test Set")
        for data, target in pbar:
            data, target = data.to(device), target.to(device)
            output = model(data)

            loss = criterion(output, target)
            acc = compute_accuracy(output, target)

            total_loss += loss.item()
            total_acc += acc
            n_batches += 1

            preds = torch.argmax(output, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(target.cpu().numpy())

            pbar.set_postfix({
                'Loss': f'{loss.item():.4f}',
                'Acc': f'{acc*100:.1f}%'
            })

    avg_loss = total_loss / n_batches
    avg_acc = total_acc / n_batches

    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)

    # Get label names
    if label_mapping and 'idx_to_label' in label_mapping:
        idx_to_label = label_mapping['idx_to_label']
        if isinstance(list(idx_to_label.keys())[0], str):
            idx_to_label = {int(k): v for k, v in idx_to_label.items()}
        target_names = [idx_to_label.get(i, f'Class_{i}') for i in range(len(idx_to_label))]
    else:
        target_names = None

    # === Print Overall Results ===
    print(f"\n{'='*70}")
    print(f"TEST SET EVALUATION RESULTS")
    print(f"{'='*70}")
    print(f"Overall Loss: {avg_loss:.4f}")
    print(f"Overall Accuracy: {avg_acc*100:.2f}%")
    print(f"Total Samples: {len(all_labels):,}")

    # === Confusion Matrix ===
    cm = confusion_matrix(all_labels, all_preds)

    plt.figure(figsize=(12, 10))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=target_names if target_names else 'auto',
                yticklabels=target_names if target_names else 'auto',
                cbar_kws={'label': 'Count'})
    plt.title('Confusion Matrix', fontsize=14, fontweight='bold')
    plt.ylabel('True Label', fontsize=12)
    plt.xlabel('Predicted Label', fontsize=12)
    if target_names:
        plt.xticks(rotation=45, ha='right')
        plt.yticks(rotation=0)
    plt.tight_layout()
    plt.savefig('confusion_matrix.png', dpi=300, bbox_inches='tight')
    print(f"\n✓ Confusion matrix saved to 'confusion_matrix.png'")
    plt.show()

    # === Classification Report ===
    print(f"\n{'='*70}")
    print("SKLEARN CLASSIFICATION REPORT")
    print(f"{'='*70}")
    print(classification_report(all_labels, all_preds,
                                target_names=target_names,
                                zero_division=0))

    # === Per-Class Analysis ===
    class_acc = cm.diagonal() / cm.sum(axis=1)
    class_counts = cm.sum(axis=1)
    pred_counts = cm.sum(axis=0)

    print(f"\n{'='*70}")
    print("PER-CLASS DETAILED ANALYSIS")
    print(f"{'='*70}")
    print(f"{'Class':<20} {'Accuracy':>10} {'True':>8} {'Pred':>8} {'Correct':>8}")
    print(f"{'-'*70}")

    for i in range(len(class_acc)):
        label_name = target_names[i] if target_names else f'Class_{i}'
        true_count = int(class_counts[i])
        pred_count = int(pred_counts[i])
        correct_count = int(cm[i, i])
        accuracy = class_acc[i] * 100

        print(f"{label_name:<20} {accuracy:>9.2f}% {true_count:>8} {pred_count:>8} {correct_count:>8}")

    # === Summary Statistics ===
    print(f"\n{'='*70}")
    print("SUMMARY STATISTICS")
    print(f"{'='*70}")
    print(f"Overall Accuracy:      {avg_acc*100:.2f}%")
    print(f"Mean Per-Class Acc:    {class_acc.mean()*100:.2f}%")
    print(f"Std Per-Class Acc:     {class_acc.std()*100:.2f}%")

    if target_names:
        best_idx = class_acc.argmax()
        worst_idx = class_acc.argmin()
        print(f"\nBest Performing Class:  {target_names[best_idx]:<20} ({class_acc[best_idx]*100:.2f}%)")
        print(f"Worst Performing Class: {target_names[worst_idx]:<20} ({class_acc[worst_idx]*100:.2f}%)")

    # === Check for Issues ===
    unique_preds = set(all_preds)
    unique_labels = set(all_labels)
    never_predicted = unique_labels - unique_preds

    if never_predicted:
        print(f"\n⚠️ WARNING: Classes never predicted: {sorted(never_predicted)}")
        if target_names:
            never_pred_names = [target_names[i] for i in sorted(never_predicted)]
            print(f"   Labels: {', '.join(never_pred_names)}")

    # Classes with very low accuracy (<20%)
    low_acc_classes = [(i, class_acc[i]) for i in range(len(class_acc)) if class_acc[i] < 0.2]
    if low_acc_classes:
        print(f"\n⚠️ WARNING: {len(low_acc_classes)} class(es) with accuracy < 20%:")
        for idx, acc in low_acc_classes:
            label_name = target_names[idx] if target_names else f'Class_{idx}'
            print(f"   {label_name}: {acc*100:.2f}%")

    print(f"\n{'='*70}\n")

    return avg_loss, avg_acc, all_preds, all_labels, cm

# === Load Best Model and Evaluate ===
print("Loading best model for test evaluation...")
checkpoint = torch.load('best_classification_model.pth', weights_only=False)
model.load_state_dict(checkpoint['model_state_dict'])
print(f"Loaded model from epoch {checkpoint['epoch']+1}")
print(f"  Validation mAP: {checkpoint['val_map']:.4f}")
print(f"  Validation Acc: {checkpoint['val_acc']*100:.2f}%\n")

test_loss, test_acc, test_preds, test_labels, test_cm = evaluate_with_per_class_analysis(
    model, test_loader, criterion, device, label_mapping=label_mapping
)

