# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKhokwsnSguwANIWklsp1puWgurUgme9

# New
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import h5py
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from torch.utils.data import Dataset, DataLoader, random_split
from torch.optim.lr_scheduler import OneCycleLR
import timm
from timm.models.swin_transformer import SwinTransformer

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

# Colab环境配置
try:
from google.colab import drive
drive.mount('/content/drive')
BASE_DIR = "/content/drive/MyDrive/data/val_ready/"
except:
    # Local environment
    BASE_DIR = "/Users/siyux1927/local/thesis0926/task_data/split/"

"""### Data Preprocessing"""

class H5Dataset(Dataset):
    """Dataset for regression task, adapted from baseline_clf.py"""
    def __init__(self, h5_path: str):
        self.h5f = h5py.File(h5_path, 'r')
        self.images = self.h5f['images']
        self.valid_indices = self._filter_nan_samples()
        self.n_samples = len(self.valid_indices)
        print(f"H5Dataset initialized: {h5_path}")
        print(f"Total samples: {len(self.images)}")
        print(f"Valid samples: {self.n_samples}")

    def _filter_nan_samples(self):
        """Filter samples with NaN in VV or VH bands"""
        valid_indices = []
        for idx in range(len(self.images)):
            img = self.images[idx].astype(np.float32)
            input_bands = img[1:3]  # VV, VH
            if not np.isnan(input_bands).any():
                valid_indices.append(idx)
        return valid_indices

    def __len__(self):
        return self.n_samples

    def __getitem__(self, idx):
        actual_idx = self.valid_indices[idx]
        img = self.images[actual_idx].astype(np.float32).copy()

        # Input: VV, VH bands
        input_bands = img[1:3]  # VV, VH
        vv = torch.from_numpy(input_bands[0])  # [H, W]
        vh = torch.from_numpy(input_bands[1])  # [H, W]
        image = torch.stack([vv, vh], dim=0)   # [2, H, W]

        # Target: CHM (first channel)
        target = torch.from_numpy(img[0:1])  # [1, H, W]
        # Set invalid values (< 1.0) to NaN
        target[target < 1.0] = float('nan')

        return image, target

    def close(self):
        if hasattr(self, 'h5f'):
            self.h5f.close()

    def __del__(self):
        self.close()

def create_dataloaders(
    train_h5: str,
    test_h5: str,
    batch_size: int = 128,
    num_workers: int = 4,
    val_ratio: float = 0.1
):
    train_dataset = H5Dataset(train_h5)
    test_dataset = H5Dataset(test_h5)

    original_train_size = len(train_dataset)
    val_size = int(original_train_size * val_ratio)
    train_size = original_train_size - val_size

    torch.manual_seed(42)
    train_indices, val_indices = random_split(
        range(original_train_size),
        [train_size, val_size]
    )

    train_subset = torch.utils.data.Subset(train_dataset, train_indices.indices)
    val_dataset = torch.utils.data.Subset(train_dataset, val_indices.indices)

    train_loader = DataLoader(
        train_subset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    return train_loader, val_loader, test_loader, train_dataset

"""### Dataloader - val ready"""

class H5Dataset(Dataset):
    """Dataset for regression task"""

    def __init__(self, h5_path: str):
        self.h5f = h5py.File(h5_path, 'r')
        self.images = self.h5f['images']
        self.valid_indices = self._filter_nan_samples()
        self.n_samples = len(self.valid_indices)

        print(f"H5Dataset initialized: {h5_path}")
        print(f"Total samples: {len(self.images)}")
        print(f"Valid samples: {self.n_samples}")

    def _filter_nan_samples(self):
        """Filter samples with NaN in VV or VH bands"""
        valid_indices = []
        for idx in range(len(self.images)):
            img = self.images[idx].astype(np.float32)
            input_bands = img[1:3]  # VV, VH
            if not np.isnan(input_bands).any():
                valid_indices.append(idx)
        return valid_indices

    def __len__(self):
        return self.n_samples

    def __getitem__(self, idx):
        actual_idx = self.valid_indices[idx]
        img = self.images[actual_idx].astype(np.float32).copy()

        # Input: VV, VH bands
        input_bands = img[1:3]  # VV, VH
        vv = torch.from_numpy(input_bands[0])  # [H, W]
        vh = torch.from_numpy(input_bands[1])  # [H, W]
        image = torch.stack([vv, vh], dim=0)   # [2, H, W]

        # Target: CHM (first channel)
        target = torch.from_numpy(img[0:1])  # [1, H, W]
        # Set invalid values (< 1.0) to NaN
        target[target < 1.0] = float('nan')

        return image, target

    def get_filename(self, idx):
        """Get filename for sample"""
        actual_idx = self.valid_indices[idx]
        if 'filenames' in self.h5f:
            return self.h5f['filenames'][actual_idx].decode('utf-8')
        return None

    def close(self):
        if hasattr(self, 'h5f'):
            self.h5f.close()

    def __del__(self):
        self.close()

def create_dataloaders(
    train_h5: str,
    val_h5: str,
    test_h5: str,
    batch_size: int = 128,
    num_workers: int = 4,
    pin_memory: bool = True
):
    """
    Create dataloaders for train, val, and test sets

    Args:
        train_h5: Training set HDF5 file path
        val_h5: Validation set HDF5 file path
        test_h5: Test set HDF5 file path
        batch_size: Batch size
        num_workers: Number of workers for data loading
        pin_memory: Whether to use pin_memory

    Returns:
        train_loader, val_loader, test_loader, train_dataset
    """
    train_dataset = H5Dataset(train_h5)
    val_dataset = H5Dataset(val_h5)
    test_dataset = H5Dataset(test_h5)

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=pin_memory,
        drop_last=False
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory,
        drop_last=False
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory,
        drop_last=False
    )

    return train_loader, val_loader, test_loader, train_dataset

"""### Model - Swin Transformer Regression"""

class InputPreprocessing(nn.Module):
    """
    输入预处理层：
    1. Depthwise Convolution: 2通道 → 48通道
    2. Pointwise Convolution: 48通道 → 3通道
    """
    def __init__(self, in_channels=2, mid_channels=48, out_channels=3):
        super().__init__()
        # Depthwise Convolution: 每个输入通道独立卷积
        self.depthwise = nn.Conv2d(
            in_channels, mid_channels, 
            kernel_size=3, padding=1, 
            groups=in_channels, bias=False
        )
        self.dw_bn = nn.BatchNorm2d(mid_channels)
        self.dw_act = nn.GELU()
        
        # Pointwise Convolution: 1x1卷积整合通道
        self.pointwise = nn.Conv2d(mid_channels, out_channels, kernel_size=1, bias=False)
        self.pw_bn = nn.BatchNorm2d(out_channels)
        self.pw_act = nn.GELU()
    
    def forward(self, x):
        # x: [B, 2, 6, 6]
        x = self.depthwise(x)  # [B, 48, 6, 6]
        x = self.dw_bn(x)
        x = self.dw_act(x)
        
        x = self.pointwise(x)  # [B, 3, 6, 6]
        x = self.pw_bn(x)
        x = self.pw_act(x)
        
        return x

class ChannelAttention(nn.Module):
    """通道注意力模块"""
    def __init__(self, channels, reduction=16):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        
        self.fc = nn.Sequential(
            nn.Linear(channels, channels // reduction, bias=False),
            nn.ReLU(),
            nn.Linear(channels // reduction, channels, bias=False)
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # x: [B, C, H, W]
        b, c, _, _ = x.size()
        
        # 平均池化和最大池化
        avg_out = self.fc(self.avg_pool(x).view(b, c))
        max_out = self.fc(self.max_pool(x).view(b, c))
        
        # 相加并通过sigmoid
        out = avg_out + max_out
        out = self.sigmoid(out).view(b, c, 1, 1)
        
        return x * out

class SpatialAttention(nn.Module):
    """空间注意力模块"""
    def __init__(self, kernel_size=7):
        super().__init__()
        self.conv = nn.Conv2d(
            2, 1, kernel_size=kernel_size, 
            padding=kernel_size // 2, bias=False
        )
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        # x: [B, C, H, W]
        # 在通道维度上做平均池化和最大池化
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        
        # 拼接并卷积
        out = torch.cat([avg_out, max_out], dim=1)
        out = self.conv(out)
        out = self.sigmoid(out)
        
        return x * out

class CBAMC(nn.Module):
    """
    CBAMC注意力模块：Channel Attention + Spatial Attention
    公式：X5 = M_c × X4 × M_s
    """
    def __init__(self, channels, reduction=16, kernel_size=7):
        super().__init__()
        self.channel_attention = ChannelAttention(channels, reduction)
        self.spatial_attention = SpatialAttention(kernel_size)
    
    def forward(self, x):
        # 先应用通道注意力
        x = self.channel_attention(x)
        # 再应用空间注意力
        x = self.spatial_attention(x)
        return x

class PatchEmbedding(nn.Module):
    """Patch Embedding for 6x6 input"""
    def __init__(self, img_size=6, patch_size=2, in_chans=3, embed_dim=96):
        super().__init__()
        self.img_size = img_size
        self.patch_size = patch_size
        self.n_patches = (img_size // patch_size) ** 2
        self.embed_dim = embed_dim
        
        self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=patch_size)
        self.norm = nn.LayerNorm(embed_dim)
    
    def forward(self, x):
        # x: [B, C, H, W]
        x = self.proj(x)  # [B, embed_dim, H/patch_size, W/patch_size]
        B, C, H, W = x.shape
        x = x.flatten(2).transpose(1, 2)  # [B, N, embed_dim]
        x = self.norm(x)
        return x, (H, W)

class WindowAttention(nn.Module):
    """Window-based Multi-head Self Attention"""
    def __init__(self, dim, window_size, num_heads, qkv_bias=True, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.dim = dim
        self.window_size = window_size
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = head_dim ** -0.5
        
        self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)
    
    def forward(self, x):
        B, N, C = x.shape
        qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        q, k, v = qkv[0], qkv[1], qkv[2]
        
        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)
        
        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x)
        x = self.proj_drop(x)
        return x

class SwinTransformerBlock(nn.Module):
    """Swin Transformer Block"""
    def __init__(self, dim, num_heads, window_size=2, mlp_ratio=4., qkv_bias=True,
                 drop=0., attn_drop=0., drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = WindowAttention(dim, window_size, num_heads, qkv_bias, attn_drop, drop)
        self.drop_path = nn.Identity()  # 简化，不使用drop_path
        self.norm2 = norm_layer(dim)
        mlp_hidden_dim = int(dim * mlp_ratio)
        self.mlp = nn.Sequential(
            nn.Linear(dim, mlp_hidden_dim),
            act_layer(),
            nn.Dropout(drop),
            nn.Linear(mlp_hidden_dim, dim),
            nn.Dropout(drop)
        )
    
    def forward(self, x):
        x = x + self.drop_path(self.attn(self.norm1(x)))
        x = x + self.drop_path(self.mlp(self.norm2(x)))
        return x

class SwinStage(nn.Module):
    """Swin Transformer Stage"""
    def __init__(self, dim, depth, num_heads, window_size=2, mlp_ratio=4., drop=0., attn_drop=0.):
        super().__init__()
        self.blocks = nn.ModuleList([
            SwinTransformerBlock(dim, num_heads, window_size, mlp_ratio, 
                                drop=drop, attn_drop=attn_drop)
            for _ in range(depth)
        ])
    
    def forward(self, x):
        for block in self.blocks:
            x = block(x)
        return x

class SimplifiedSwinTransformer(nn.Module):
    """简化的 Swin Transformer，适配 6x6 输入"""
    def __init__(self, img_size=6, patch_size=2, in_chans=3, embed_dim=96,
                 depths=[2, 2, 6, 2], num_heads=[3, 6, 12, 24], window_size=2,
                 mlp_ratio=4., drop=0., attn_drop=0.):
        super().__init__()
        self.num_layers = len(depths)
        self.embed_dim = embed_dim
        
        # Patch embedding
        self.patch_embed = PatchEmbedding(img_size, patch_size, in_chans, embed_dim)
        num_patches = self.patch_embed.n_patches
        
        # Stages with dimension expansion
        self.stages = nn.ModuleList()
        dim = embed_dim
        for i, (depth, num_head) in enumerate(zip(depths, num_heads)):
            # 创建stage
            stage = SwinStage(dim, depth, num_head, window_size, mlp_ratio, drop, attn_drop)
            self.stages.append(stage)
            
            # 下一层的维度（简化版，不进行下采样，只扩展维度）
            if i < len(depths) - 1:
                dim_next = dim * 2  # 维度翻倍
                # 添加维度扩展层
                expand_layer = nn.Linear(dim, dim_next)
                self.stages.append(expand_layer)
                dim = dim_next
        
        self.norm = nn.LayerNorm(dim)
        self.feature_dim = dim
    
    def forward(self, x):
        # x: [B, C, H, W]
        x, (H, W) = self.patch_embed(x)  # [B, N, embed_dim]
        
        for module in self.stages:
            if isinstance(module, nn.Linear):
                # 维度扩展
                x = module(x)
            else:
                # SwinStage
                x = module(x)
        
        x = self.norm(x)  # [B, N, dim]
        return x

class SwinTransformerRegression(nn.Module):
    """
    基于 Swin Transformer 的回归模型
    架构：
    1. Input Preprocessing (Depthwise + Pointwise Conv)
    2. Simplified Swin Transformer (特征提取，适配6x6输入)
    3. CBAMC Attention (通道+空间注意力)
    4. Regression Head (Flatten + FC)
    """
    def __init__(self, 
                 in_channels=2,
                 img_size=6,
                 embed_dim=96,
                 depths=[2, 2, 6, 2],
                 num_heads=[3, 6, 12, 24],
                 window_size=2,  # 适配6x6输入
                 pretrained=True):
        super().__init__()
        
        # 输入预处理层
        self.input_preprocessing = InputPreprocessing(
            in_channels=in_channels,
            mid_channels=48,
            out_channels=3
        )
        
        # 简化的 Swin Transformer（适配6x6输入）
        self.swin = SimplifiedSwinTransformer(
            img_size=img_size,
            patch_size=2,  # 6x6 -> 3x3 patches
            in_chans=3,
            embed_dim=embed_dim,
            depths=depths,
            num_heads=num_heads,
            window_size=window_size,
        )
        
        # 获取特征维度
        feature_dim = self.swin.feature_dim
        # 对于6x6输入，patch_size=2，得到3x3=9个patches
        num_patches = (img_size // 2) ** 2  # 9
        
        # CBAMC注意力模块
        # 将 [B, N, C] 转换为 [B, C, H, W] 格式后应用注意力
        self.cbamc = CBAMC(channels=feature_dim, reduction=16)
        
        # 回归头
        # 使用全局平均池化 + 全连接层
        self.regression_head = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),  # [B, C, 1, 1]
            nn.Flatten(),  # [B, C]
            nn.Linear(feature_dim, feature_dim // 2),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(feature_dim // 2, feature_dim // 4),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(feature_dim // 4, 1)  # 输出单个回归值
        )
        
        self.num_patches = num_patches
        self.feature_dim = feature_dim
        self._initialize_weights()
    
    def _initialize_weights(self):
        """初始化权重"""
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            elif isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
    
    def forward(self, x):
        # x: [B, 2, 6, 6]
        
        # 1. 输入预处理
        x = self.input_preprocessing(x)  # [B, 3, 6, 6]
        
        # 2. Swin Transformer特征提取
        features = self.swin(x)  # [B, N, C] = [B, 9, feature_dim]
        
        # 转换为 [B, C, H, W] 格式以便应用CBAMC
        B, N, C = features.shape
        # 对于6x6输入，patch_size=2，得到3x3=9个patches
        H = W = int(np.sqrt(N))  # 3
        if H * W == N:
            features = features.transpose(1, 2).reshape(B, C, H, W)  # [B, C, 3, 3]
        else:
            # 如果不是完全平方，使用全局池化
            features = features.mean(dim=1, keepdim=True)  # [B, 1, C]
            features = features.transpose(1, 2).unsqueeze(-1)  # [B, C, 1, 1]
        
        # 3. CBAMC注意力
        features = self.cbamc(features)  # [B, C, H, W]
        
        # 4. 回归头
        output = self.regression_head(features)  # [B, 1]
        
        # 为了保持与原有代码兼容，将输出reshape为 [B, 1, 6, 6]
        # 这里使用插值将输出扩展到原始空间大小
        B = output.shape[0]
        output = output.view(B, 1, 1, 1)
        output = F.interpolate(output, size=(6, 6), mode='bilinear', align_corners=True)
        
        return output  # [B, 1, 6, 6]

class UNetPlusPlusRegression(nn.Module):
    """
    UNet++ for regression tasks, adapted from baseline_clf.py
    Input: (B, 2, 6, 6) - VV, VH bands
    Output: (B, 1, 6, 6) - CHM prediction
    """
    def __init__(self, in_channels=2, out_channels=1, base_channels=32, dropout=0.3):
        super().__init__()

        # configure the number of channels
        nb_filter = [base_channels, base_channels*2, base_channels*4]
        self.pool = nn.MaxPool2d(2, 2)

        self.conv0_0 = ConvBlock(in_channels, nb_filter[0], dropout)
        self.conv1_0 = ConvBlock(nb_filter[0], nb_filter[1], dropout)
        self.conv0_1 = ConvBlock(nb_filter[0] + nb_filter[1], nb_filter[0], dropout)
        self.conv2_0 = ConvBlock(nb_filter[1], nb_filter[2], dropout)
        self.conv1_1 = ConvBlock(nb_filter[1] + nb_filter[2], nb_filter[1], dropout)
        self.conv0_2 = ConvBlock(nb_filter[0]*2 + nb_filter[1], nb_filter[0], dropout)

        # Regression head: output same spatial size as input
        self.regression_head = nn.Sequential(
            nn.Conv2d(nb_filter[0], nb_filter[0] // 2, 3, padding=1, bias=False),
            nn.BatchNorm2d(nb_filter[0] // 2, momentum=0.01),
            nn.GELU(),
            nn.Dropout2d(dropout * 0.5),
            nn.Conv2d(nb_filter[0] // 2, out_channels, 1)
        )

        self._initialize_weights()

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            elif isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        # encoder
        x0_0 = self.conv0_0(x)  # (B, 32, 6, 6)
        x1_0 = self.conv1_0(self.pool(x0_0))  # (B, 64, 3, 3)

        # nested nodes
        x0_1 = self.conv0_1(torch.cat([x0_0, F.interpolate(x1_0, size=x0_0.shape[2:], mode='bilinear', align_corners=True)], 1))  # (B, 32, 6, 6)

        # bottleneck
        x2_0 = self.conv2_0(self.pool(x1_0))  # (B, 128, 1, 1)

        # decoder
        x1_1 = self.conv1_1(torch.cat([x1_0, F.interpolate(x2_0, size=x1_0.shape[2:], mode='bilinear', align_corners=True)], 1))  # (B, 64, 3, 3)
        x0_2 = self.conv0_2(torch.cat([x0_0, x0_1, F.interpolate(x1_1, size=x0_0.shape[2:], mode='bilinear', align_corners=True)], 1))  # (B, 32, 6, 6)

        # Regression output
        output = self.regression_head(x0_2)  # (B, 1, 6, 6)

        return output

"""### Loss and Data Augmentation"""

def create_mask(pred, target):
    """Create mask for valid pixels (not NaN)"""
    return ~torch.isnan(target) & ~torch.isnan(pred)

def mixup_data(x, y, alpha=1.0):
    """
    MixUp数据增强
    Args:
        x: 输入数据 [B, C, H, W]
        y: 目标数据 [B, 1, H, W]
        alpha: MixUp参数（α=1.0）
    Returns:
        mixed_x: 混合后的输入
        y_a, y_b: 两个目标
        lam: 混合系数
    """
    if alpha > 0:
        lam = np.random.beta(alpha, alpha)
    else:
        lam = 1
    
    batch_size = x.size(0)
    index = torch.randperm(batch_size).to(x.device)
    
    mixed_x = lam * x + (1 - lam) * x[index, :]
    y_a, y_b = y, y[index]
    
    return mixed_x, y_a, y_b, lam

def mixup_criterion(criterion, pred, y_a, y_b, lam):
    """
    MixUp损失计算
    Args:
        criterion: 损失函数
        pred: 预测值
        y_a, y_b: 两个目标
        lam: 混合系数
    Returns:
        loss: 混合损失
    """
    return lam * criterion(pred, y_a) + (1 - lam) * criterion(pred, y_b)

class MaskedMSELoss(nn.Module):
    """MSE损失（仅计算有效像素）"""
    def __init__(self):
        super(MaskedMSELoss, self).__init__()

    def forward(self, pred, target):
        """MSE loss computed only on valid pixels"""
        mask = create_mask(pred, target)
        if mask.sum() == 0:
            return torch.tensor(0.0, device=pred.device, requires_grad=True)
        mse = ((pred[mask] - target[mask]) ** 2).mean()
        return mse

class MaskedHuberLoss(nn.Module):
    """Huber损失（仅计算有效像素）"""
    def __init__(self, delta=1.0):
        super(MaskedHuberLoss, self).__init__()
        self.delta = delta

    def forward(self, pred, target):
        """Huber loss computed only on valid pixels"""
        mask = create_mask(pred, target)
        if mask.sum() == 0:
            return torch.tensor(0.0, device=pred.device, requires_grad=True)
        
        error = pred[mask] - target[mask]
        abs_error = torch.abs(error)
        quadratic = torch.clamp(abs_error, max=self.delta)
        linear = abs_error - quadratic
        loss = 0.5 * quadratic ** 2 + self.delta * linear
        return loss.mean()

class MaskedRMSELoss(nn.Module):
    def __init__(self):
        super(MaskedRMSELoss, self).__init__()

    def forward(self, pred, target):
        """RMSE loss computed only on valid pixels"""
        mask = create_mask(pred, target)
        if mask.sum() == 0:
            return torch.tensor(0.0, device=pred.device, requires_grad=True)
        mse = ((pred[mask] - target[mask]) ** 2).mean()
        rmse = torch.sqrt(mse + 1e-8)
        return rmse

def compute_r2(pred, target):
    """Compute R² score"""
    mask = create_mask(pred, target)
    if mask.sum() == 0:
        return 0.0
    pred_valid = pred[mask]
    target_valid = target[mask]
    ss_res = ((target_valid - pred_valid) ** 2).sum()
    ss_tot = ((target_valid - target_valid.mean()) ** 2).sum()
    r2 = (1 - (ss_res / ss_tot)).item() if ss_tot > 0 else 0.0
    return r2

class FocalFrequencyLoss(nn.Module):
    """
    频域损失 - 强调高频细节（对抗过度平滑）
    论文: Jiang et al. "Focal Frequency Loss" (ICCV 2021)
    """
    def __init__(self, alpha=1.0):
        super().__init__()
        self.alpha = alpha

    def forward(self, pred, target):
        # 创建mask，只处理有效像素
        mask = create_mask(pred, target)
        if mask.sum() == 0:
            return torch.tensor(0.0, device=pred.device, requires_grad=True)

        # 对每个样本分别处理（因为mask可能不同）
        batch_size = pred.shape[0]
        losses = []

        for i in range(batch_size):
            pred_i = pred[i:i+1]  # (1, 1, H, W)
            target_i = target[i:i+1]  # (1, 1, H, W)
            mask_i = mask[i:i+1]  # (1, 1, H, W)

            # 只处理有效区域
            if mask_i.sum() == 0:
                continue

            # 将无效值设为0（FFT需要连续数据）
            pred_masked = pred_i.clone()
            target_masked = target_i.clone()
            pred_masked[~mask_i] = 0.0
            target_masked[~mask_i] = 0.0

            # 转到频域
            pred_fft = torch.fft.rfft2(pred_masked)
            target_fft = torch.fft.rfft2(target_masked)

            # 计算频谱差异（使用实部和虚部）
            diff_real = pred_fft.real - target_fft.real
            diff_imag = pred_fft.imag - target_fft.imag
            diff = torch.sqrt(diff_real ** 2 + diff_imag ** 2 + 1e-8)

            # 归一化diff（避免尺度问题）
            diff_normalized = diff / (diff.mean() + 1e-8)

            # Focal 权重：高频分量获得更高权重
            freq_weight = torch.pow(diff_normalized + 1e-8, self.alpha)

            # 加权频域损失（归一化）
            loss = (freq_weight * diff_normalized).mean()
            losses.append(loss)

        if len(losses) == 0:
            return torch.tensor(0.0, device=pred.device, requires_grad=True)

        return torch.stack(losses).mean()

class CombinedLoss(nn.Module):
    """组合空间损失和频域损失"""
    def __init__(self, freq_weight=0.1, alpha=1.0):
        super().__init__()
        self.masked_rmse = MaskedRMSELoss() 
        self.focal_freq = FocalFrequencyLoss(alpha=alpha)
        self.freq_weight = freq_weight

    def forward(self, pred, target):
        spatial_loss = self.masked_rmse(pred, target)
        freq_loss = self.focal_freq(pred, target)
        return spatial_loss + self.freq_weight * freq_loss

"""### Function"""

def collect_layer_gradients(model):
    """Collect mean absolute gradient for each layer"""
    layer_grads = {}
    for name, param in model.named_parameters():
        if param.grad is not None:
            grad_mean_abs = param.grad.abs().mean().item()
            layer_grads[name] = grad_mean_abs
    return layer_grads

def train_regression_swin(model, train_loader, criterion, optimizer, scheduler, device, epoch,
                         use_mixup=True, mixup_alpha=1.0, return_grads=False):
    """
    训练函数（支持MixUp数据增强）
    Args:
        model: 模型
        train_loader: 训练数据加载器
        criterion: 损失函数
        optimizer: 优化器
        scheduler: 学习率调度器
        device: 设备
        epoch: 当前epoch
        use_mixup: 是否使用MixUp
        mixup_alpha: MixUp参数
        return_grads: 是否返回梯度信息
    """
    model.train()
    total_loss = 0
    n_batches = 0
    layer_grads = None

    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}")

    for step, (data, target) in enumerate(pbar):
        data, target = data.to(device), target.to(device)

        # MixUp数据增强
        if use_mixup and model.training:
            mixed_data, target_a, target_b, lam = mixup_data(data, target, alpha=mixup_alpha)
            optimizer.zero_grad()
            output = model(mixed_data)
            loss = mixup_criterion(criterion, output, target_a, target_b, lam)
        else:
            optimizer.zero_grad()
            output = model(data)
            loss = criterion(output, target)

        loss.backward()

        # Gradient clipping for stability
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        # Collect gradients if needed
        if return_grads and step == len(train_loader) - 1:
            layer_grads = collect_layer_gradients(model)

        optimizer.step()
        scheduler.step()  # OneCycleLR需要每个batch更新

        total_loss += loss.item()
        n_batches += 1

        pbar.set_postfix({
            'Loss': f'{loss.item():.4f}',
            'LR': f'{scheduler.get_last_lr()[0]:.2e}'
        })

    avg_loss = total_loss / n_batches

    return avg_loss, layer_grads

def train_regression_paper(model, train_dataset, criterion, optimizer, scheduler, device, epoch,
                           steps_per_epoch=100, batch_size=128, return_grads=False):
    """
    Training function according to paper specifications:
    - Random batch selection
    - Fixed steps per epoch (default: 100 steps)
    Adapted from baseline_clf.py train_classification_paper
    """
    model.train()
    total_loss = 0
    total_valid_ratio = 0
    n_batches = 0

    # Create indices for random batch selection
    total_samples = len(train_dataset)

    pbar = tqdm(range(steps_per_epoch), desc=f"Epoch {epoch+1}")

    for step in pbar:
        # Randomly select batch indices
        indices = torch.randint(0, total_samples, (batch_size,))

        # Get batch data
        batch_data = []
        batch_targets = []
        for idx in indices:
            data, target = train_dataset[idx.item()]
            batch_data.append(data)
            batch_targets.append(target)

        data = torch.stack(batch_data).to(device)
        target = torch.stack(batch_targets).to(device)

        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()

        # Gradient clipping for stability
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        # Collect gradients if needed
        if return_grads and step == steps_per_epoch - 1:
            layer_grads = collect_layer_gradients(model)

        optimizer.step()

        with torch.no_grad():
            mask = create_mask(output, target)
            valid_ratio = mask.sum().item() / target.numel() if target.numel() > 0 else 0.0

        total_loss += loss.item()
        total_valid_ratio += valid_ratio
        n_batches += 1

        pbar.set_postfix({
            'Loss': f'{loss.item():.4f}',
            'Valid': f'{valid_ratio*100:.1f}%'
        })

    avg_loss = total_loss / n_batches
    avg_valid_ratio = total_valid_ratio / n_batches

    if return_grads:
        return avg_loss, avg_valid_ratio, layer_grads
    return avg_loss, avg_valid_ratio

def evaluate_regression(model, loader, criterion, device):
    """Evaluate regression model with comprehensive metrics"""
    model.eval()
    total_loss = 0
    total_rmse = 0
    total_r2 = 0
    n_batches = 0

    with torch.no_grad():
        pbar = tqdm(loader, desc="Evaluating")
        for data, target in pbar:
            data, target = data.to(device), target.to(device)
            output = model(data)

            # 计算损失（MSE）
            loss = criterion(output, target)
            
            # 计算RMSE（用于显示）
            mask = create_mask(output, target)
            if mask.sum() > 0:
                mse = ((output[mask] - target[mask]) ** 2).mean()
                rmse = torch.sqrt(mse + 1e-8)
            else:
                rmse = torch.tensor(0.0)
            
            r2 = compute_r2(output, target)

            total_loss += loss.item()
            total_rmse += rmse.item()
            total_r2 += r2
            n_batches += 1

            pbar.set_postfix({
                'Loss': f'{loss.item():.4f}',
                'RMSE': f'{rmse.item():.4f}',
                'R²': f'{r2:.3f}'
            })

    return total_loss / n_batches, total_r2 / n_batches

"""### Train - Swin Transformer"""

batch_size = 32
train_loader, val_loader, test_loader, train_dataset = create_dataloaders(
    train_h5=BASE_DIR+'train_data.h5',
    val_h5=BASE_DIR+'val_data.h5',
    test_h5=BASE_DIR+'test_data.h5',
    batch_size=batch_size,
    num_workers=4
)

# Initialize Swin Transformer Regression model
model = SwinTransformerRegression(
    in_channels=2,
    img_size=6,
    embed_dim=96,
    depths=[2, 2, 6, 2],
    num_heads=[3, 6, 12, 24],
    window_size=2,
    pretrained=True
).to(device)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")

# 损失函数：MSE或Huber Loss
criterion = MaskedMSELoss()  # 或 MaskedHuberLoss(delta=1.0)

# 优化器：AdamW，不同模块使用不同学习率
# 基础参数：1e-4，CBAMC模块：1e-3
base_params = []
cbamc_params = []

for name, param in model.named_parameters():
    if 'cbamc' in name.lower() or 'channel_attention' in name.lower() or 'spatial_attention' in name.lower():
        cbamc_params.append(param)
    else:
        base_params.append(param)

optimizer = optim.AdamW([
    {'params': base_params, 'lr': 1e-4},
    {'params': cbamc_params, 'lr': 1e-3}
], weight_decay=1e-5)

# OneCycleLR调度器：30% warmup + 70% decay
num_epochs = 100
steps_per_epoch = len(train_loader)
total_steps = num_epochs * steps_per_epoch

scheduler = OneCycleLR(
    optimizer,
    max_lr=[1e-3, 1e-2],  # 对应两个参数组的最大学习率
    total_steps=total_steps,
    pct_start=0.3,  # 30% warmup
    anneal_strategy='cos',  # 余弦退火
    div_factor=10.0,  # 初始学习率 = max_lr / div_factor
    final_div_factor=100.0  # 最终学习率 = max_lr / (div_factor * final_div_factor)
)

best_val_loss = float('inf')
best_val_r2 = 0.0

history = {
    'train_loss': [],
    'val_loss': [], 'val_r2': [], 'lr': [],
    'layer_grads': {}
}

print(f"\nModel: Swin Transformer Regression")
print(f"Epochs: {num_epochs}")
print(f"Batch size: {batch_size}")
print(f"Base LR: 1e-4, CBAMC LR: 1e-3")
print(f"Scheduler: OneCycleLR (30% warmup + 70% decay)")
print(f"Loss: Masked MSE")
print(f"Optimizer: AdamW with weight decay=1e-5")
print(f"MixUp: Enabled (α=1.0)")

for epoch in range(num_epochs):
    train_loss, layer_grads = train_regression_swin(
        model, train_loader, criterion, optimizer, scheduler, device, epoch,
        use_mixup=True, mixup_alpha=1.0, return_grads=(epoch % 10 == 0)
    )
    
    val_loss, val_r2 = evaluate_regression(
        model, val_loader, criterion, device
    )

    # 获取当前学习率（取第一个参数组的学习率）
    current_lr = optimizer.param_groups[0]['lr']

    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['val_r2'].append(val_r2)
    history['lr'].append(current_lr)

    # Store layer gradients
    if layer_grads:
    for layer_name, grad_value in layer_grads.items():
        if layer_name not in history['layer_grads']:
            history['layer_grads'][layer_name] = []
        history['layer_grads'][layer_name].append(grad_value)

    # Print every 10 epochs
    if (epoch + 1) % 10 == 0 or epoch < 5:
        print(f"Epoch {epoch+1}/{num_epochs}")
        print(f"  Train Loss: {train_loss:.4f}")
        print(f"  Val Loss:   {val_loss:.4f} | Val R²:   {val_r2:.4f} | LR: {current_lr:.2e}")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        best_val_r2 = val_r2

        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'scheduler_state_dict': scheduler.state_dict(),
            'val_loss': val_loss,
            'val_r2': val_r2,
            'history': history
        }, 'best_swin_regression_model.pth')

        if (epoch + 1) % 10 == 0 or epoch < 5:
            print(f" *Best model | R²: {best_val_r2:.4f}, Loss: {best_val_loss:.4f}\n")
    else:
        if (epoch + 1) % 10 == 0 or epoch < 5:
            print()

def plot_training_history(history):
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    axes[0].plot(history['train_loss'], label='Train Loss')
    axes[0].plot(history['val_loss'], label='Val Loss')
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Loss (MSE)')
    axes[0].set_title('Training and Validation Loss')
    axes[0].legend()
    axes[0].grid(True)

    axes[1].plot(history['val_r2'], label='Val R²', color='green')
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('R²')
    axes[1].set_title('Validation R²')
    axes[1].legend()
    axes[1].grid(True)

    axes[2].plot(history['lr'], label='Learning Rate', color='orange')
    axes[2].set_xlabel('Epoch')
    axes[2].set_ylabel('Learning Rate')
    axes[2].set_title('Learning Rate Schedule')
    axes[2].set_yscale('log')
    axes[2].legend()
    axes[2].grid(True)

    plt.tight_layout()
    plt.savefig('training_history_regression.png', dpi=300, bbox_inches='tight')
    plt.show()

def plot_gradient_history(history):
    """Plot gradient history"""
    if 'layer_grads' not in history or not history['layer_grads']:
        print("No gradient history found. Skipping gradient plot.")
        return

    epochs = range(1, len(history['lr']) + 1)
    fig, ax = plt.subplots(1, 1, figsize=(12, 6))

    ax.set_xlabel('Epoch')
    ax.set_ylabel('Gradient (mean abs)', color='b')
    ax.tick_params(axis='y', labelcolor='b')
    ax.set_title('Layer Gradients Over Time')
    ax.grid(True, alpha=0.3)

    # Select key layers
    key_layers = []
    for layer_name in history['layer_grads'].keys():
        if 'weight' in layer_name and ('conv' in layer_name or 'regression_head' in layer_name):
            key_layers.append(layer_name)

    if len(key_layers) > 10:
        key_layers = key_layers[:10]

    colors = plt.cm.tab10(np.linspace(0, 1, len(key_layers)))
    for i, layer_name in enumerate(key_layers):
        if layer_name in history['layer_grads']:
            short_name = layer_name.split('.')[-2] if len(layer_name.split('.')) > 2 else layer_name.split('.')[-1]
            ax.plot(epochs, history['layer_grads'][layer_name],
                    label=short_name, color=colors[i], alpha=0.7, linewidth=1.5)

    ax.legend(loc='upper right', fontsize=8)
    ax.set_yscale('log')

    plt.tight_layout()
    plt.savefig('gradient_history_regression.png', dpi=300, bbox_inches='tight')
    plt.show()

plot_training_history(history)
plot_gradient_history(history)

"""### Test"""

print(f"\nBest Validation Results:")
print(f"  R²: {best_val_r2:.4f}")
print(f"  Loss (MSE): {best_val_loss:.4f}")

# Load best model and evaluate on test set
print("\nLoading best model for test evaluation...")
checkpoint = torch.load('best_swin_regression_model.pth', weights_only=False)
model.load_state_dict(checkpoint['model_state_dict'])
print(f"Loaded model from epoch {checkpoint['epoch']+1}")
print(f"  Validation R²: {checkpoint['val_r2']:.4f}")
print(f"  Validation Loss (MSE): {checkpoint['val_loss']:.4f}\n")

test_loss, test_r2 = evaluate_regression(
    model, test_loader, criterion, device
)

print(f"\nTest Results:")
print(f"  Loss (MSE): {test_loss:.4f}")
print(f"  R²: {test_r2:.4f}")

"""### Visualization Functions"""

def plot_scatter_prediction(model, loader, device, loader_name="Train"):
    """Plot scatter plot of true vs predicted CHM"""
    model.eval()
    y_true = []
    y_pred = []

    with torch.no_grad():
        for inputs, targets in tqdm(loader, desc=f"Collecting {loader_name} predictions"):
            inputs, targets = inputs.to(device), targets.to(device)
            preds = model(inputs)

            mask = create_mask(preds, targets)
            y_true.append(targets[mask].cpu().numpy())
            y_pred.append(preds[mask].cpu().numpy())

    y_true = np.concatenate(y_true)
    y_pred = np.concatenate(y_pred)

    plt.figure(figsize=(6, 6))
    plt.scatter(y_true, y_pred, s=1, alpha=0.3)
    plt.xlabel("True CHM", fontsize=10)
    plt.ylabel("Predicted CHM", fontsize=10)
    plt.title(f"{loader_name} Set: True vs Predicted CHM", fontsize=12)

    min_val, max_val = min(y_true.min(), y_pred.min()), max(y_true.max(), y_pred.max())
    plt.plot([min_val, max_val], [min_val, max_val], 'r--', linewidth=2, label='Perfect Prediction')

    plt.legend(fontsize=10)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(f'scatter_plot_{loader_name.lower()}.png', dpi=300, bbox_inches='tight')
    plt.show()

    print(f"\n{loader_name} Set stats:")
    print(f"  True: [{y_true.min():.2f}, {y_true.max():.2f}]")
    print(f"  Pred: [{y_pred.min():.2f}, {y_pred.max():.2f}]")
    print(f"  STD: {y_pred.std():.2f}")
    print(f"  Mean: {y_pred.mean():.2f}")

    return y_true, y_pred

# Generate visualizations
y_true_train, y_pred_train = plot_scatter_prediction(model, train_loader, device, "Train")
y_true_test, y_pred_test = plot_scatter_prediction(model, test_loader, device, "Test")

def visualize_test_samples(model, test_loader, device, num_samples=4, start_index=0):
    """Visualize test samples with predictions - each image has its own colorbar"""
    model.eval()
    samples = []

    with torch.no_grad():
        for i, (inputs, targets) in enumerate(test_loader):
            batch_start = i * test_loader.batch_size
            batch_end = batch_start + inputs.shape[0]

            if batch_end <= start_index or batch_start >= start_index + num_samples:
                continue

            inputs, targets = inputs.to(device), targets.to(device)
            preds = model(inputs)

            for j in range(inputs.shape[0]):
                idx = batch_start + j
                if start_index <= idx < start_index + num_samples:
                    samples.append({
                        'idx': idx,
                        'input': inputs[j].cpu().numpy(),  # (2, H, W) - VV, VH
                        'target': targets[j, 0].cpu().numpy(),
                        'pred': preds[j, 0].cpu().numpy()
                    })

            if len(samples) >= num_samples:
                break

    viridis_nan = cm.get_cmap('viridis').copy()
    viridis_nan.set_bad(color='red')

    # 调整布局：为 colorbar 预留空间
    fig = plt.figure(figsize=(12, 2.5*num_samples))

    # 使用 GridSpec 精细控制布局
    from matplotlib.gridspec import GridSpec
    gs = GridSpec(num_samples, 4, figure=fig,
                  wspace=0.3, hspace=0.4,
                  left=0.05, right=0.95, top=0.95, bottom=0.05)

    for i, s in enumerate(samples):
        # Input bands: VV, VH
        for j, name in enumerate(['VV', 'VH']):
            ax = fig.add_subplot(gs[i, j])
            im = ax.imshow(s['input'][j], cmap='gray', aspect='auto')
            ax.set_title(f"Sample {s['idx']}: {name}", fontsize=8)
            ax.axis('off')

            # 为每个输入通道添加 colorbar
            cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
            cbar.ax.tick_params(labelsize=6)

        # Target CHM
        ax_target = fig.add_subplot(gs[i, 2])
        valid_mask = ~np.isnan(s['target'])
        valid_pct = valid_mask.sum() / valid_mask.size * 100

        im_target = ax_target.imshow(s['target'], cmap=viridis_nan, aspect='auto')
        ax_target.set_title(f"Sample {s['idx']}: True CHM", fontsize=8)
        ax_target.text(0.5, -0.15, f"Valid: {valid_pct:.1f}%",
                       transform=ax_target.transAxes, ha='center', fontsize=6)
        ax_target.axis('off')

        # Target colorbar
        cbar_target = plt.colorbar(im_target, ax=ax_target, fraction=0.046, pad=0.04)
        cbar_target.ax.tick_params(labelsize=6)
        cbar_target.set_label('Height (m)', fontsize=6)

        # Prediction CHM
        ax_pred = fig.add_subplot(gs[i, 3])
        pred_masked = s['pred'].copy()
        pred_masked[~valid_mask] = np.nan

        # 使用与 target 相同的 vmin/vmax 以便对比
        if valid_mask.any():
            vmin = np.nanmin(s['target'])
            vmax = np.nanmax(s['target'])
        else:
            vmin, vmax = None, None

        im_pred = ax_pred.imshow(pred_masked, cmap=viridis_nan, aspect='auto',
                                 vmin=vmin, vmax=vmax)
        ax_pred.set_title(f"Sample {s['idx']}: Predicted CHM", fontsize=8)

        if valid_mask.any():
            rmse = np.sqrt(np.mean((s['target'][valid_mask] - s['pred'][valid_mask]) ** 2))
            mae = np.mean(np.abs(s['target'][valid_mask] - s['pred'][valid_mask]))
            ax_pred.text(0.5, -0.15, f"RMSE: {rmse:.2f}m | MAE: {mae:.2f}m",
                        transform=ax_pred.transAxes, ha='center', fontsize=6, color='red')
        ax_pred.axis('off')

        # Prediction colorbar (与 target 共享范围)
        cbar_pred = plt.colorbar(im_pred, ax=ax_pred, fraction=0.046, pad=0.04)
        cbar_pred.ax.tick_params(labelsize=6)
        cbar_pred.set_label('Height (m)', fontsize=6)

    plt.suptitle(f'Test Predictions (Index {start_index}-{start_index+num_samples-1})',
                 fontsize=10, y=0.998)

    plt.savefig('test_samples_visualization.png', dpi=300, bbox_inches='tight')
    plt.show()

    return samples

_ = visualize_test_samples(model, test_loader, device, num_samples=4, start_index=110)