# -*- coding: utf-8 -*-
"""treesatai-chm-baseline-new

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hYsZ-4K4Qr5_Ee_Cl2NvOqGtPgLMWfP7
"""

import json
from pathlib import Path

import numpy as np
import random
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
    average_precision_score,
    classification_report,
    multilabel_confusion_matrix,
    accuracy_score,
    confusion_matrix,
    r2_score,
)
from sklearn.manifold import TSNE
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

def set_seed(seed: int = 42) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

from google.colab import drive
drive.mount('/content/drive')
BASE_DIR = "/content/drive/MyDrive/data/treesatai-chm-npy-new/"

configs = {
    # fixed
    "val_ratio": 0.1,
    "val_method": "stratify",
    "val_thres": 0.5,

    # data
    "batch_size": 64,

    # model
    "model_type": "MultiTask",
    "base_channels": 96,

    # training
    "epochs": 20,
    "patience": 5,
    "dropout": 0.3,
    "weight_decay": 0.0001,
    "base_lr": 1e-4,
    "max_lr": 1e-4,
    "scheduler": None,
    "optimizer": "AdamW",
    "loss_fn": "class_weights_inv_sqrt_freq_normalized",
    "early_stop_metric": "map_weighted",

    # multitask
    "cls_weight": 1,
    "reg_weight": 1,
}

"""## Load Data"""

CHM_MIN_THRESHOLD = 0
CHM_MAX_THRESHOLD = 999
S1_MIN_THRESHOLD = -999.0
S1_MAX_THRESHOLD = 999

class MultiTaskDataset(Dataset):
    def __init__(self, images: np.ndarray, labels: np.ndarray):
        super().__init__()
        # if images.ndim != 4:
        #     raise ValueError(f"Expected images of shape (N, C, H, W), got {images.shape}")
        # if images.shape[1] < 4:
        #     raise ValueError(
        #         f"Expected at least 4 channels (3 S1 + 1 CHM), got C={images.shape[1]}"
        #     )

        inputs = images[:, 0:3, ...].astype(np.float32)
        inputs = np.clip(inputs, S1_MIN_THRESHOLD, S1_MAX_THRESHOLD)
        self.inputs = torch.from_numpy(inputs)

        chm = images[:, 3, ...].astype(np.float32)
        mask_invalid = (chm < CHM_MIN_THRESHOLD) | (chm > CHM_MAX_THRESHOLD)
        chm[mask_invalid] = np.nan
        self.chm_targets = torch.from_numpy(chm).unsqueeze(1)

        labels_arr = np.asarray(labels).astype(np.float32)
        if labels_arr.ndim != 2:
            raise ValueError(f"Expected labels of shape (N, num_classes) for multi-label, got {labels_arr.shape}")
        self.cls_targets = torch.from_numpy(labels_arr)

    def __len__(self):
        return self.inputs.shape[0]

    def __getitem__(self, idx):
        x = self.inputs[idx]
        y_cls = self.cls_targets[idx]
        y_chm = self.chm_targets[idx]
        return x, y_cls, y_chm

def make_datasets(data_dir):
    data_dir = Path(data_dir)

    train_images = np.load(data_dir / "train_x.npy")
    train_labels = np.load(data_dir / "train_y.npy")
    val_images = np.load(data_dir / "val_x.npy")
    val_labels = np.load(data_dir / "val_y.npy")
    test_images = np.load(data_dir / "test_x.npy")
    test_labels = np.load(data_dir / "test_y.npy")

    train_ds = MultiTaskDataset(train_images, train_labels)
    val_ds = MultiTaskDataset(val_images, val_labels)
    test_ds = MultiTaskDataset(test_images, test_labels)

    print("Train:\t", len(train_ds), "\nTest:\t", len(test_ds), "\nVal:\t", len(val_ds))
    return train_ds, val_ds, test_ds

train_ds, val_ds, test_ds = make_datasets(BASE_DIR)
train_loader = DataLoader(train_ds, batch_size=configs["batch_size"], shuffle=True, num_workers=2)
val_loader = DataLoader(val_ds, batch_size=configs["batch_size"], shuffle=False, num_workers=2)
test_loader = DataLoader(test_ds, batch_size=configs["batch_size"], shuffle=False, num_workers=2)

with Path(f"{BASE_DIR}/classes.json").open("r") as f:
    classes = json.load(f)
with Path(f"{BASE_DIR}/class_weights.json").open("r") as f:
    cw = json.load(f)

"""## Model - MLP"""

class MLPClassifier(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        height: int = 6,
        width: int = 6,
        hidden_dims: tuple[int, ...] = (256, 256),
        dropout: float = 0.3,
    ) -> None:
        super().__init__()
        self.in_channels = in_channels
        self.height = height
        self.width = width
        in_features = in_channels * height * width

        layers = []
        prev_dim = in_features
        for h in hidden_dims:
            layers.append(nn.Linear(prev_dim, h))
            layers.append(nn.BatchNorm1d(h))
            layers.append(nn.ReLU(inplace=True))
            if dropout > 0.0:
                layers.append(nn.Dropout(p=dropout))
            prev_dim = h
        layers.append(nn.Linear(prev_dim, num_classes))
        self.mlp = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if x.dim() == 4:
            x = x.view(x.size(0), -1)
        return self.mlp(x)


class MLPRegressor(nn.Module):
    def __init__(
        self,
        in_channels: int,
        height: int = 6,
        width: int = 6,
        hidden_dims: tuple[int, ...] = (256, 256),
        dropout: float = 0.3,
    ) -> None:
        super().__init__()
        self.in_channels = in_channels
        self.height = height
        self.width = width
        in_features = in_channels * height * width
        out_features = height * width

        layers = []
        prev_dim = in_features
        for h in hidden_dims:
            layers.append(nn.Linear(prev_dim, h))
            layers.append(nn.BatchNorm1d(h))
            layers.append(nn.ReLU(inplace=True))
            if dropout > 0.0:
                layers.append(nn.Dropout(p=dropout))
            prev_dim = h
        layers.append(nn.Linear(prev_dim, out_features))
        self.mlp = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if x.dim() == 4:
            x = x.view(x.size(0), -1)
        out = self.mlp(x)
        batch_size = out.size(0)
        out = out.view(batch_size, 1, self.height, self.width)
        out = F.softplus(out)
        out = torch.clamp(out, 0.0, CHM_MAX_THRESHOLD)
        return out


class MultiTaskMLP(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        height: int = 6,
        width: int = 6,
        hidden_dims_cls: tuple[int, ...] = (256, 256),
        hidden_dims_reg: tuple[int, ...] = (256, 256),
        dropout: float = 0.3,
        use_uncertainty_loss: bool = True,
        cls_weight: float = 1.0,
        reg_weight: float = 0.5,
    ) -> None:
        super().__init__()
        self.use_uncertainty_loss = use_uncertainty_loss
        self.cls_weight = cls_weight
        self.reg_weight = reg_weight
        self.min_task_weight = 0.1
        self.max_task_weight = 5.0
        self.num_classes = num_classes

        self.cls_mlp = MLPClassifier(
            in_channels=in_channels,
            num_classes=num_classes,
            height=height,
            width=width,
            hidden_dims=hidden_dims_cls,
            dropout=dropout,
        )
        self.reg_mlp = MLPRegressor(
            in_channels=in_channels,
            height=height,
            width=width,
            hidden_dims=hidden_dims_reg,
            dropout=dropout,
        )

        if self.use_uncertainty_loss:
            self.log_sigma_cls = nn.Parameter(torch.zeros(1))
            self.log_sigma_reg = nn.Parameter(torch.zeros(1))

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        logits = self.cls_mlp(x)
        chm = self.reg_mlp(x)
        return logits, chm

    def compute_total_loss(
        self,
        loss_cls: torch.Tensor,
        loss_reg: torch.Tensor,
    ) -> torch.Tensor:
        if self.use_uncertainty_loss:
            w_cls = 0.5 * torch.exp(-self.log_sigma_cls)
            w_reg = 0.5 * torch.exp(-self.log_sigma_reg)

            w_min = self.min_task_weight
            w_max = self.max_task_weight
            w_cls = torch.clamp(w_cls, w_min, w_max)
            w_reg = torch.clamp(w_reg, w_min, w_max)

            loss = w_cls * loss_cls + w_reg * loss_reg
            return loss
        return self.cls_weight * loss_cls + self.reg_weight * loss_reg

    def get_task_weights(self) -> tuple[float, float]:
        if self.use_uncertainty_loss:
            w_cls = 0.5 * torch.exp(-self.log_sigma_cls)
            w_reg = 0.5 * torch.exp(-self.log_sigma_reg)

            w_min = self.min_task_weight
            w_max = self.max_task_weight
            w_cls = torch.clamp(w_cls, w_min, w_max)
            w_reg = torch.clamp(w_reg, w_min, w_max)
        else:
            first_param = next(self.parameters())
            device = first_param.device
            w_cls = torch.tensor(self.cls_weight, device=device)
            w_reg = torch.tensor(self.reg_weight, device=device)
        return float(w_cls.item()), float(w_reg.item())

"""## Model - UNet"""

class DoubleConv(nn.Module):
    def __init__(self, in_channels: int, out_channels: int) -> None:
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)


class Down(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: int,
        padding: int,
    ) -> None:
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=kernel_size,
                stride=stride,
                padding=padding,
                bias=False,
            ),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)


class Up(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: int,
    ) -> None:
        super().__init__()
        self.up = nn.ConvTranspose2d(
            in_channels,
            in_channels // 2,
            kernel_size=kernel_size,
            stride=stride,
        )
        # after upsampling, features are concatenated with skip connection
        # so DoubleConv expects in_channels and produces out_channels
        self.conv = DoubleConv(in_channels, out_channels)

    def forward(self, x: torch.Tensor, skip: torch.Tensor) -> torch.Tensor:
        x = self.up(x)
        x = torch.cat([x, skip], dim=1)
        x = self.conv(x)
        return x

"""### clf"""

class UNetClassifier(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        base_channels: int = 32,
        dropout: float = 0.3,
    ) -> None:
        super().__init__()

        self.num_classes = num_classes

        self.enc1 = DoubleConv(in_channels, base_channels)

        self.down1 = Down(
            in_channels=base_channels,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=2,
            padding=1,
        )
        self.enc2 = DoubleConv(base_channels * 2, base_channels * 2)

        self.down2 = Down(
            in_channels=base_channels * 2,
            out_channels=base_channels * 4,
            kernel_size=3,
            stride=3,
            padding=0,
        )

        self.bottleneck = DoubleConv(base_channels * 4, base_channels * 4)

        self.up2 = Up(
            in_channels=base_channels * 4,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=3,
        )
        self.dropout2 = nn.Dropout2d(p=dropout)

        self.up1 = Up(
            in_channels=base_channels * 2,
            out_channels=base_channels,
            kernel_size=2,
            stride=2,
        )

        self.out_conv = nn.Conv2d(base_channels, num_classes, kernel_size=1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x1 = self.enc1(x)
        x2 = self.down1(x1)

        x3 = self.enc2(x2)
        x4 = self.down2(x3)

        x5 = self.bottleneck(x4)

        x6 = self.up2(x5, x3)
        x6 = self.dropout2(x6)

        x7 = self.up1(x6, x1)

        logits_map = self.out_conv(x7)
        logits = logits_map.mean(dim=(2, 3))
        return logits

"""### reg"""

class UNetRegressor(nn.Module):
    def __init__(
        self,
        in_channels: int,
        base_channels: int = 32,
        dropout: float = 0.3,
    ) -> None:
        super().__init__()

        self.enc1 = DoubleConv(in_channels, base_channels)

        self.down1 = Down(
            in_channels=base_channels,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=2,
            padding=1,
        )
        self.enc2 = DoubleConv(base_channels * 2, base_channels * 2)

        self.down2 = Down(
            in_channels=base_channels * 2,
            out_channels=base_channels * 4,
            kernel_size=3,
            stride=3,
            padding=0,
        )

        self.bottleneck = DoubleConv(base_channels * 4, base_channels * 4)

        self.up2 = Up(
            in_channels=base_channels * 4,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=3,
        )
        self.dropout2 = nn.Dropout2d(p=dropout)

        self.up1 = Up(
            in_channels=base_channels * 2,
            out_channels=base_channels,
            kernel_size=2,
            stride=2,
        )

        self.out_conv = nn.Conv2d(base_channels, 1, kernel_size=1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x1 = self.enc1(x)
        x2 = self.down1(x1)

        x3 = self.enc2(x2)
        x4 = self.down2(x3)

        x5 = self.bottleneck(x4)

        x6 = self.up2(x5, x3)
        x6 = self.dropout2(x6)

        x7 = self.up1(x6, x1)

        raw = self.out_conv(x7)
        chm = F.softplus(raw)
        chm = torch.clamp(chm, 0.0, CHM_MAX_THRESHOLD)
        return chm

"""## Model - MTL"""

class MultiTaskUNet(nn.Module):
    """Multi-task U-Net with shared encoder and separate decoders for
    classification (tree species) and regression (CHM).

    The encoder follows the same structure as UNetClassifier/UNetRegressor.
    The classifier head outputs logits of shape (N, num_classes), obtained by
    global average pooling over a logits feature map. The regression head
    outputs a CHM map of shape (N, 1, H, W) with non-negative values.
    """

    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        base_channels: int = 32,
        dropout: float = 0.3,
    ) -> None:
        super().__init__()

        self.num_classes = num_classes

        # Shared encoder
        self.enc1 = DoubleConv(in_channels, base_channels)
        self.down1 = Down(
            in_channels=base_channels,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=2,
            padding=1,
        )
        self.enc2 = DoubleConv(base_channels * 2, base_channels * 2)
        self.down2 = Down(
            in_channels=base_channels * 2,
            out_channels=base_channels * 4,
            kernel_size=3,
            stride=3,
            padding=0,
        )
        self.bottleneck = DoubleConv(base_channels * 4, base_channels * 4)

        # Classification decoder
        self.up2_cls = Up(
            in_channels=base_channels * 4,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=3,
        )
        self.dropout2_cls = nn.Dropout2d(p=dropout)
        self.up1_cls = Up(
            in_channels=base_channels * 2,
            out_channels=base_channels,
            kernel_size=2,
            stride=2,
        )
        self.out_conv_cls = nn.Conv2d(base_channels, num_classes, kernel_size=1)

        # Regression decoder
        self.up2_reg = Up(
            in_channels=base_channels * 4,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=3,
        )
        self.dropout2_reg = nn.Dropout2d(p=dropout)
        self.up1_reg = Up(
            in_channels=base_channels * 2,
            out_channels=base_channels,
            kernel_size=2,
            stride=2,
        )
        self.out_conv_reg = nn.Conv2d(base_channels, 1, kernel_size=1)

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        # Shared encoder forward
        x1 = self.enc1(x)
        x2 = self.down1(x1)
        x3 = self.enc2(x2)
        x4 = self.down2(x3)
        x5 = self.bottleneck(x4)

        # Classification branch
        xc = self.up2_cls(x5, x3)
        xc = self.dropout2_cls(xc)
        xc = self.up1_cls(xc, x1)
        logits_map = self.out_conv_cls(xc)
        logits = logits_map.mean(dim=(2, 3))  # (N, num_classes)

        # Regression branch
        xr = self.up2_reg(x5, x3)
        xr = self.dropout2_reg(xr)
        xr = self.up1_reg(xr, x1)
        raw_chm = self.out_conv_reg(xr)
        chm = F.softplus(raw_chm)
        chm = torch.clamp(chm, 0.0, CHM_MAX_THRESHOLD)

        return logits, chm


class CrossTaskAttention(nn.Module):
    def __init__(self, channels: int, num_heads: int = 4) -> None:
        super().__init__()
        self.channels = channels
        self.num_heads = num_heads

        self.attn_cls = nn.MultiheadAttention(
            embed_dim=channels,
            num_heads=num_heads,
            batch_first=True,
        )
        self.attn_reg = nn.MultiheadAttention(
            embed_dim=channels,
            num_heads=num_heads,
            batch_first=True,
        )

        self.norm_cls = nn.LayerNorm(channels)
        self.norm_reg = nn.LayerNorm(channels)

    def forward(
        self,
        feat_cls: torch.Tensor,
        feat_reg: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        # feat_* shape: (N, C, H, W)
        n, c, h, w = feat_cls.shape
        if feat_reg.shape != feat_cls.shape:
            raise ValueError(
                f"Expected feat_reg with shape {feat_cls.shape}, got {feat_reg.shape}"
            )

        cls_tokens = feat_cls.view(n, c, h * w).transpose(1, 2)  # (N, L, C)
        reg_tokens = feat_reg.view(n, c, h * w).transpose(1, 2)  # (N, L, C)

        cls_q = self.norm_cls(cls_tokens)
        reg_q = self.norm_reg(reg_tokens)

        cls_attended, _ = self.attn_cls(
            query=cls_q,
            key=reg_q,
            value=reg_q,
            need_weights=False,
        )
        reg_attended, _ = self.attn_reg(
            query=reg_q,
            key=cls_q,
            value=cls_q,
            need_weights=False,
        )

        cls_tokens = cls_tokens + cls_attended
        reg_tokens = reg_tokens + reg_attended

        feat_cls_out = cls_tokens.transpose(1, 2).view(n, c, h, w)
        feat_reg_out = reg_tokens.transpose(1, 2).view(n, c, h, w)
        return feat_cls_out, feat_reg_out


class MultiTaskUNetCrossAttention(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        base_channels: int = 32,
        dropout: float = 0.3,
        attn_heads: int = 4,
    ) -> None:
        super().__init__()

        self.num_classes = num_classes

        # Shared encoder (same as MultiTaskUNet)
        self.enc1 = DoubleConv(in_channels, base_channels)
        self.down1 = Down(
            in_channels=base_channels,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=2,
            padding=1,
        )
        self.enc2 = DoubleConv(base_channels * 2, base_channels * 2)
        self.down2 = Down(
            in_channels=base_channels * 2,
            out_channels=base_channels * 4,
            kernel_size=3,
            stride=3,
            padding=0,
        )

        # Task-specific bottlenecks
        self.bottleneck_cls = DoubleConv(base_channels * 4, base_channels * 4)
        self.bottleneck_reg = DoubleConv(base_channels * 4, base_channels * 4)

        # Cross-attention between task-specific bottleneck features
        self.cross_attn = CrossTaskAttention(
            channels=base_channels * 4,
            num_heads=attn_heads,
        )

        # Classification decoder
        self.up2_cls = Up(
            in_channels=base_channels * 4,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=3,
        )
        self.dropout2_cls = nn.Dropout2d(p=dropout)
        self.up1_cls = Up(
            in_channels=base_channels * 2,
            out_channels=base_channels,
            kernel_size=2,
            stride=2,
        )
        self.out_conv_cls = nn.Conv2d(base_channels, num_classes, kernel_size=1)

        # Regression decoder
        self.up2_reg = Up(
            in_channels=base_channels * 4,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=3,
        )
        self.dropout2_reg = nn.Dropout2d(p=dropout)
        self.up1_reg = Up(
            in_channels=base_channels * 2,
            out_channels=base_channels,
            kernel_size=2,
            stride=2,
        )
        self.out_conv_reg = nn.Conv2d(base_channels, 1, kernel_size=1)

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        # Shared encoder forward
        x1 = self.enc1(x)
        x2 = self.down1(x1)
        x3 = self.enc2(x2)
        x4 = self.down2(x3)

        # Task-specific bottleneck features
        b_cls = self.bottleneck_cls(x4)
        b_reg = self.bottleneck_reg(x4)

        # Cross-attention between tasks at bottleneck
        b_cls, b_reg = self.cross_attn(b_cls, b_reg)

        # Classification branch
        xc = self.up2_cls(b_cls, x3)
        xc = self.dropout2_cls(xc)
        xc = self.up1_cls(xc, x1)
        logits_map = self.out_conv_cls(xc)
        logits = logits_map.mean(dim=(2, 3))

        # Regression branch
        xr = self.up2_reg(b_reg, x3)
        xr = self.dropout2_reg(xr)
        xr = self.up1_reg(xr, x1)
        raw_chm = self.out_conv_reg(xr)
        chm = F.softplus(raw_chm)
        chm = torch.clamp(chm, 0.0, CHM_MAX_THRESHOLD)

        return logits, chm


class SharedPrivateConvBlock(nn.Module):
    def __init__(self, in_channels: int, out_channels: int) -> None:
        super().__init__()
        self.shared = DoubleConv(in_channels, out_channels)
        self.cls = DoubleConv(in_channels, out_channels)
        self.reg = DoubleConv(in_channels, out_channels)

        self.alpha = nn.Parameter(torch.ones(out_channels))
        self.beta = nn.Parameter(torch.zeros(out_channels))
        self.gamma = nn.Parameter(torch.ones(out_channels))
        self.delta = nn.Parameter(torch.zeros(out_channels))

        self._last_h_shared: torch.Tensor | None = None
        self._last_h_cls_raw: torch.Tensor | None = None
        self._last_h_reg_raw: torch.Tensor | None = None

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        h_shared = self.shared(x)
        h_cls_raw = self.cls(x)
        h_reg_raw = self.reg(x)

        self._last_h_shared = h_shared
        self._last_h_cls_raw = h_cls_raw
        self._last_h_reg_raw = h_reg_raw

        alpha = self.alpha.view(1, -1, 1, 1)
        beta = self.beta.view(1, -1, 1, 1)
        gamma = self.gamma.view(1, -1, 1, 1)
        delta = self.delta.view(1, -1, 1, 1)

        h_cls = alpha * h_shared + beta * h_cls_raw
        h_reg = gamma * h_shared + delta * h_reg_raw
        return h_shared, h_cls, h_reg

    def orthogonal_loss(self) -> torch.Tensor:
        if self._last_h_shared is None:
            device = self.shared.block[0].weight.device
            return torch.tensor(0.0, device=device)

        h_shared = self._last_h_shared
        h_cls_raw = self._last_h_cls_raw
        h_reg_raw = self._last_h_reg_raw

        n = h_shared.size(0)
        h_s = h_shared.view(n, -1)
        h_c = h_cls_raw.view(n, -1)
        h_r = h_reg_raw.view(n, -1)

        h_s = h_s - h_s.mean(dim=0, keepdim=True)
        h_c = h_c - h_c.mean(dim=0, keepdim=True)
        h_r = h_r - h_r.mean(dim=0, keepdim=True)

        c_sc = torch.matmul(h_s.T, h_c) / max(n, 1)
        c_sr = torch.matmul(h_s.T, h_r) / max(n, 1)
        c_cr = torch.matmul(h_c.T, h_r) / max(n, 1)

        loss = c_sc.pow(2).mean() + c_sr.pow(2).mean() + c_cr.pow(2).mean()
        return loss


class MultiTaskUNetSharedPrivate(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        base_channels: int = 32,
        dropout: float = 0.3,
    ) -> None:
        super().__init__()

        self.num_classes = num_classes

        self.enc1_block = SharedPrivateConvBlock(in_channels, base_channels)
        self.down1 = Down(
            in_channels=base_channels,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=2,
            padding=1,
        )

        self.enc2_cls = DoubleConv(base_channels * 2, base_channels * 2)
        self.down2_cls = Down(
            in_channels=base_channels * 2,
            out_channels=base_channels * 4,
            kernel_size=3,
            stride=3,
            padding=0,
        )
        self.bottleneck_cls = DoubleConv(base_channels * 4, base_channels * 4)

        self.enc2_reg = DoubleConv(base_channels * 2, base_channels * 2)
        self.down2_reg = Down(
            in_channels=base_channels * 2,
            out_channels=base_channels * 4,
            kernel_size=3,
            stride=3,
            padding=0,
        )
        self.bottleneck_reg = DoubleConv(base_channels * 4, base_channels * 4)

        self.up2_cls = Up(
            in_channels=base_channels * 4,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=3,
        )
        self.dropout2_cls = nn.Dropout2d(p=dropout)
        self.up1_cls = Up(
            in_channels=base_channels * 2,
            out_channels=base_channels,
            kernel_size=2,
            stride=2,
        )
        self.out_conv_cls = nn.Conv2d(base_channels, num_classes, kernel_size=1)

        self.up2_reg = Up(
            in_channels=base_channels * 4,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=3,
        )
        self.dropout2_reg = nn.Dropout2d(p=dropout)
        self.up1_reg = Up(
            in_channels=base_channels * 2,
            out_channels=base_channels,
            kernel_size=2,
            stride=2,
        )
        self.out_conv_reg = nn.Conv2d(base_channels, 1, kernel_size=1)

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        x1_shared, x1_cls, x1_reg = self.enc1_block(x)
        x2_shared = self.down1(x1_shared)

        x3_cls = self.enc2_cls(x2_shared)
        x4_cls = self.down2_cls(x3_cls)
        b_cls = self.bottleneck_cls(x4_cls)

        x3_reg = self.enc2_reg(x2_shared)
        x4_reg = self.down2_reg(x3_reg)
        b_reg = self.bottleneck_reg(x4_reg)

        xc = self.up2_cls(b_cls, x3_cls)
        xc = self.dropout2_cls(xc)
        xc = self.up1_cls(xc, x1_cls)
        logits_map = self.out_conv_cls(xc)
        logits = logits_map.mean(dim=(2, 3))

        xr = self.up2_reg(b_reg, x3_reg)
        xr = self.dropout2_reg(xr)
        xr = self.up1_reg(xr, x1_reg)
        raw_chm = self.out_conv_reg(xr)
        chm = F.softplus(raw_chm)
        chm = torch.clamp(chm, 0.0, CHM_MAX_THRESHOLD)

        return logits, chm

    def orthogonal_loss(self) -> torch.Tensor:
        return self.enc1_block.orthogonal_loss()


"""## Functions

### Loss Function
"""

def masked_rmse_loss(preds: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    mask = ~torch.isnan(targets)
    # mask = torch.isfinite(targets) & (targets != 0)
    if not mask.any():
        return (preds * 0.0).sum()
    diff = preds[mask] - targets[mask]
    return torch.sqrt(torch.mean(diff ** 2))

"""### train one epoch - cls"""

def train_one_epoch_cls(model, loader, cls_criterion, optimizer, device, epoch=None, lr_history=None, scheduler=None):
    model.train()
    total_loss = 0.0
    total_samples = 0

    for images, labels_cls, _ in tqdm(loader, desc=f"Train Cls {epoch}" if epoch is not None else "Train Cls"):
        images = images.to(device)
        labels_cls = labels_cls.to(device)

        optimizer.zero_grad()
        out = model(images)
        logits = out[0] if isinstance(out, tuple) else out

        loss = cls_criterion(logits, labels_cls)
        loss.backward()
        optimizer.step()

        if scheduler is not None:
            scheduler.step()

        if lr_history is not None:
            lr_history.append(optimizer.param_groups[0]["lr"])

        batch_size = images.size(0)
        total_loss += float(loss.item()) * batch_size
        total_samples += batch_size

    avg_loss = total_loss / max(total_samples, 1)
    return avg_loss


def evaluate_cls(model, loader, cls_criterion, device, desc="Eval Cls"):
    model.eval()
    total_loss = 0.0
    total_samples = 0

    all_true_cls = []
    all_pred_cls = []
    all_logits_cls = []

    with torch.no_grad():
        for images, labels_cls, _ in tqdm(loader, desc=desc):
            images = images.to(device)
            labels_cls = labels_cls.to(device)

            out = model(images)
            logits = out[0] if isinstance(out, tuple) else out
            loss = cls_criterion(logits, labels_cls)

            batch_size = images.size(0)
            total_loss += float(loss.item()) * batch_size
            total_samples += batch_size

            probs = torch.sigmoid(logits)
            preds_cls = (probs >= configs["val_thres"]).float()

            all_true_cls.append(labels_cls.cpu().numpy())
            all_pred_cls.append(preds_cls.cpu().numpy())
            all_logits_cls.append(logits.cpu().numpy())

    avg_loss = total_loss / max(total_samples, 1)

    y_true_cls = np.concatenate(all_true_cls, axis=0) if all_true_cls else np.array([])
    y_pred_cls = np.concatenate(all_pred_cls, axis=0) if all_pred_cls else np.array([])
    y_logits = np.concatenate(all_logits_cls, axis=0) if all_logits_cls else np.array([])

    if y_true_cls.size > 0:
        y_scores = torch.sigmoid(torch.from_numpy(y_logits)).numpy()

        f1_micro = f1_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
        f1_weighted = f1_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
        precision_micro = precision_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
        precision_weighted = precision_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
        recall_micro = recall_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
        recall_weighted = recall_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
        map_micro = average_precision_score(y_true_cls, y_scores, average="micro")
        map_weighted = average_precision_score(y_true_cls, y_scores, average="weighted")
        accuracy = accuracy_score(y_true_cls, y_pred_cls)
    else:
        accuracy = float("nan")
        f1_micro = float("nan")
        f1_weighted = float("nan")
        precision_micro = float("nan")
        precision_weighted = float("nan")
        recall_micro = float("nan")
        recall_weighted = float("nan")
        map_micro = float("nan")
        map_weighted = float("nan")

    metrics = {
        "loss": avg_loss,
        "accuracy": accuracy,
        "f1_micro": f1_micro,
        "f1_weighted": f1_weighted,
        "precision_micro": precision_micro,
        "precision_weighted": precision_weighted,
        "recall_micro": recall_micro,
        "recall_weighted": recall_weighted,
        "map_micro": map_micro,
        "map_weighted": map_weighted,
    }

    return metrics, y_true_cls, y_pred_cls

"""### train one epoch - reg"""

def train_one_epoch_reg(model, loader, reg_criterion, optimizer, device, epoch=None, lr_history=None, scheduler=None):
    model.train()
    total_loss = 0.0
    total_samples = 0

    for images, _, labels_chm in tqdm(loader, desc=f"Train Reg {epoch}" if epoch is not None else "Train Reg"):
        images = images.to(device)
        labels_chm = labels_chm.to(device)

        optimizer.zero_grad()
        out = model(images)
        if isinstance(out, tuple):
            _, chm_pred = out
        else:
            chm_pred = out

        loss = reg_criterion(chm_pred, labels_chm)
        loss.backward()
        optimizer.step()

        if scheduler is not None:
            scheduler.step()

        if lr_history is not None:
            lr_history.append(optimizer.param_groups[0]["lr"])

        batch_size = images.size(0)
        total_loss += float(loss.item()) * batch_size
        total_samples += batch_size

    avg_loss = total_loss / max(total_samples, 1)
    return avg_loss


def evaluate_reg(model, loader, reg_criterion, device, desc="Eval Reg"):
    model.eval()
    total_loss = 0.0
    total_samples = 0

    all_true_chm = []
    all_pred_chm = []

    with torch.no_grad():
        for images, _, labels_chm in tqdm(loader, desc=desc):
            images = images.to(device)
            labels_chm = labels_chm.to(device)

            out = model(images)
            if isinstance(out, tuple):
                _, chm_pred = out
            else:
                chm_pred = out

            loss = reg_criterion(chm_pred, labels_chm)

            batch_size = images.size(0)
            total_loss += float(loss.item()) * batch_size
            total_samples += batch_size

            mask = ~torch.isnan(labels_chm)
            if mask.any():
                all_true_chm.append(labels_chm[mask].cpu().numpy())
                all_pred_chm.append(chm_pred[mask].cpu().numpy())

    avg_loss = total_loss / max(total_samples, 1)

    if all_true_chm:
        y_true_chm_np = np.concatenate(all_true_chm, axis=0).reshape(-1)
        y_pred_chm_np = np.concatenate(all_pred_chm, axis=0).reshape(-1)

        y_true_chm_t = torch.from_numpy(y_true_chm_np)
        y_pred_chm_t = torch.from_numpy(y_pred_chm_np)
        rmse = float(masked_rmse_loss(y_pred_chm_t, y_true_chm_t).item())
        r2 = float(r2_score(y_true_chm_np, y_pred_chm_np))
    else:
        rmse = float("nan")
        r2 = float("nan")

    metrics = {
        "loss": avg_loss,
        "reg_loss": avg_loss,
        "rmse": rmse,
        "r2": r2,
    }

    return metrics

"""### train one epoch - mtl"""

def train_one_epoch(
    model,
    loader,
    cls_criterion,
    reg_criterion,
    optimizer,
    device,
    epoch=None,
    lr_history=None,
    scheduler=None,
    cls_weight: float = 1.0,
    reg_weight: float = 1.0,
):
    """Train one epoch for multi-task UNet.

    Loss = cls_weight * L_cls + reg_weight * L_reg.
    """
    model.train()
    total_loss = 0.0
    total_cls_loss = 0.0
    total_reg_loss = 0.0
    total_samples = 0

    for images, labels_cls, labels_chm in tqdm(
        loader, desc=f"Train {epoch}" if epoch is not None else "Train"
    ):
        images = images.to(device)
        labels_cls = labels_cls.to(device)
        labels_chm = labels_chm.to(device)

        optimizer.zero_grad()
        logits, chm_pred = model(images)

        loss_cls = cls_criterion(logits, labels_cls)
        loss_reg = reg_criterion(chm_pred, labels_chm)
        loss = cls_weight * loss_cls + reg_weight * loss_reg

        loss.backward()
        optimizer.step()

        if scheduler is not None:
            scheduler.step()

        if lr_history is not None:
            lr_history.append(optimizer.param_groups[0]["lr"])

        batch_size = images.size(0)
        total_loss += float(loss.item()) * batch_size
        total_cls_loss += float(loss_cls.item()) * batch_size
        total_reg_loss += float(loss_reg.item()) * batch_size
        total_samples += batch_size

    avg_loss = total_loss / max(total_samples, 1)
    avg_cls_loss = total_cls_loss / max(total_samples, 1)
    avg_reg_loss = total_reg_loss / max(total_samples, 1)
    return avg_loss, avg_cls_loss, avg_reg_loss


def evaluate(
    model,
    loader,
    cls_criterion,
    reg_criterion,
    device,
    desc: str = "Eval",
    cls_weight: float = 1.0,
    reg_weight: float = 1.0,
):
    """Evaluate multi-task UNet on both classification and regression tasks."""
    model.eval()
    total_loss = 0.0
    total_cls_loss = 0.0
    total_reg_loss = 0.0
    total_samples = 0

    all_true_cls = []   # multi-hot ground truth
    all_pred_cls = []   # multi-hot predictions (after threshold)
    all_logits_cls = [] # raw logits
    all_true_chm = []
    all_pred_chm = []

    with torch.no_grad():
        for images, labels_cls, labels_chm in tqdm(loader, desc=desc):
            images = images.to(device)
            labels_cls = labels_cls.to(device)
            labels_chm = labels_chm.to(device)

            logits, chm_pred = model(images)

            loss_cls = cls_criterion(logits, labels_cls)
            loss_reg = reg_criterion(chm_pred, labels_chm)
            loss = cls_weight * loss_cls + reg_weight * loss_reg

            batch_size = images.size(0)
            total_loss += float(loss.item()) * batch_size
            total_cls_loss += float(loss_cls.item()) * batch_size
            total_reg_loss += float(loss_reg.item()) * batch_size
            total_samples += batch_size

            # Classification predictions
            probs = torch.sigmoid(logits)
            preds_cls = (probs >= configs["val_thres"]).float()

            all_true_cls.append(labels_cls.cpu().numpy())
            all_pred_cls.append(preds_cls.cpu().numpy())
            all_logits_cls.append(logits.cpu().numpy())

            # Regression targets/predictions for valid CHM pixels
            mask = ~torch.isnan(labels_chm)
            if mask.any():
                all_true_chm.append(labels_chm[mask].cpu().numpy())
                all_pred_chm.append(chm_pred[mask].cpu().numpy())

    avg_loss = total_loss / max(total_samples, 1)
    avg_cls_loss = total_cls_loss / max(total_samples, 1)
    avg_reg_loss = total_reg_loss / max(total_samples, 1)

    # Classification metrics
    y_true_cls = np.concatenate(all_true_cls, axis=0) if all_true_cls else np.array([])
    y_pred_cls = np.concatenate(all_pred_cls, axis=0) if all_pred_cls else np.array([])
    y_logits = np.concatenate(all_logits_cls, axis=0) if all_logits_cls else np.array([])

    if y_true_cls.size > 0:
        y_scores = torch.sigmoid(torch.from_numpy(y_logits)).numpy()
        f1_micro = f1_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
        f1_weighted = f1_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
        precision_micro = precision_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
        precision_weighted = precision_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
        recall_micro = recall_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
        recall_weighted = recall_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
        map_micro = average_precision_score(y_true_cls, y_scores, average="micro")
        map_weighted = average_precision_score(y_true_cls, y_scores, average="weighted")
        accuracy = accuracy_score(y_true_cls, y_pred_cls)
    else:
        f1_micro = f1_weighted = precision_micro = precision_weighted = float("nan")
        recall_micro = recall_weighted = map_micro = map_weighted = float("nan")
        accuracy = float("nan")

    # Regression metrics
    if all_true_chm:
        y_true_chm_np = np.concatenate(all_true_chm, axis=0).reshape(-1)
        y_pred_chm_np = np.concatenate(all_pred_chm, axis=0).reshape(-1)

        y_true_chm_t = torch.from_numpy(y_true_chm_np)
        y_pred_chm_t = torch.from_numpy(y_pred_chm_np)
        rmse = float(masked_rmse_loss(y_pred_chm_t, y_true_chm_t).item())
        r2 = float(r2_score(y_true_chm_np, y_pred_chm_np))
    else:
        rmse = float("nan")
        r2 = float("nan")

    metrics = {
        "loss": avg_loss,
        "cls_loss": avg_cls_loss,
        "reg_loss": avg_reg_loss,
        "f1_micro": f1_micro,
        "f1_weighted": f1_weighted,
        "precision_micro": precision_micro,
        "precision_weighted": precision_weighted,
        "recall_micro": recall_micro,
        "recall_weighted": recall_weighted,
        "map_micro": map_micro,
        "map_weighted": map_weighted,
        "accuracy": accuracy,
        "rmse": rmse,
        "r2": r2,
    }

    return metrics, y_true_cls, y_pred_cls

"""### Visualization

#### cm
"""

def plot_cm(model):
  model.eval()
  all_logits = []
  all_labels = []
  with torch.no_grad():
      for images, labels_cls, _ in tqdm(test_loader, desc="Test features for confusion"):
          images = images.to(device)
          out = model(images)
          if isinstance(out, tuple):
              logits = out[0]
          else:
              logits = out
          all_logits.append(logits.cpu().numpy())
          all_labels.append(labels_cls.numpy())

  X_logits = np.concatenate(all_logits, axis=0)
  y_true_multi_full = np.concatenate(all_labels, axis=0)

  y_true_dom = y_true_multi_full.argmax(axis=1)
  y_scores_full = 1.0 / (1.0 + np.exp(-X_logits))
  y_pred_dom = y_scores_full.argmax(axis=1)

  cm_dom = confusion_matrix(y_true_dom, y_pred_dom, labels=np.arange(num_classes))

  plt.figure(figsize=(8, 6))
  ax = sns.heatmap(
      cm_dom,
      annot=True,
      fmt="d",
      cmap="Blues",
      xticklabels=classes,
      yticklabels=classes,
  )
  plt.xlabel("Predicted dominant class")
  plt.ylabel("True dominant class")
  plt.tight_layout()
  plt.show()

"""#### plot samples"""

# def visualize_chm_s1_samples(model, dataset, start_idx: int = 0, num_samples: int = 4) -> None:
#     model.eval()

#     start_idx = int(start_idx)
#     num_samples = int(num_samples)
#     end_idx = min(start_idx + num_samples, len(dataset))
#     if end_idx <= start_idx:
#         print("No samples to visualize.")
#         return

#     n = end_idx - start_idx

#     inputs = dataset.inputs[start_idx:end_idx].to(device)
#     # For MultiTaskDataset, CHM targets are stored as chm_targets
#     targets = dataset.chm_targets[start_idx:end_idx]

#     with torch.no_grad():
#         out = model(inputs)
#         if isinstance(out, tuple):
#             _, preds = out
#         else:
#             preds = out

#     inputs_np = inputs.cpu().numpy()
#     targets_np = targets.cpu().numpy()[:, 0, :, :]
#     preds_np = preds.cpu().numpy()[:, 0, :, :]

#     # 先构造所有需要显示的 band，用于统一计算每组的 vmin/vmax
#     s1_list = []   # (n, 3, H, W)
#     chm_list = []  # (n, 2, H, W)

#     for row in range(n):
#         band1 = inputs_np[row, 0, :, :]
#         band2 = inputs_np[row, 1, :, :]
#         # 如果只有两个 S1 通道，则用 VV/VH 构造第三个通道
#         if inputs_np.shape[1] > 2:
#             band3 = inputs_np[row, 2, :, :]
#         else:
#             denom = np.where(np.abs(band2) < 1e-6, 1e-6, band2)
#             band3 = band1 / denom
#         chm_true = targets_np[row]
#         chm_pred = preds_np[row]

#         s1_list.append(np.stack([band1, band2, band3], axis=0))
#         chm_list.append(np.stack([chm_true, chm_pred], axis=0))

#     # Layout similar to gen-chm/vis.py: per-column width ~3, compact vertical spacing
#     fig, axes = plt.subplots(nrows=n, ncols=5, figsize=(3 * 5, 2.5 * n))
#     if n == 1:
#         axes = axes.reshape(1, -1)

#     for row in range(n):
#         row_axes = axes[row]

#         band1, band2, band3 = s1_list[row]
#         chm_true, chm_pred = chm_list[row]

#         images = [band1, band2, band3, chm_true, chm_pred]
#         titles = [
#             "VV",
#             "VH",
#             "VV/VH",
#             "CHM true",
#             "CHM pred",
#         ]
#         vmin_chm = None
#         vmax_chm = None

#         for col in range(5):
#             ax = row_axes[col]
#             band = images[col]
#             cmap = "gray" if col < 3 else "viridis"

#             im = ax.imshow(band, cmap=cmap)
#             if row < 1:
#                 ax.set_title(titles[col])
#             ax.axis("off")

#             if col < 5:
#                 vmin = float(np.nanmin(band))
#                 vmax = float(np.nanmax(band))
#                 if not np.isfinite(vmin) or not np.isfinite(vmax):
#                     vmin, vmax = 0.0, 1.0
#                 im.set_clim(vmin, vmax)

#                 cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.02)
#                 ticks = np.linspace(vmin, vmax, 5)
#                 cbar.set_ticks(ticks)
#                 cbar.ax.tick_params(labelsize=9)
#                 cbar.ax.yaxis.set_major_formatter(
#                     plt.FuncFormatter(lambda x, _: f"{x:.1f}" if x < 1 else f"{int(x)}")
#                 )
#             # else:
#             #     if vmin_chm is None or vmax_chm is None:
#             #         vmin_chm = float(np.nanmin(chm_true))
#             #         vmax_chm = float(np.nanmax(chm_true))
#             #         if not np.isfinite(vmin_chm) or not np.isfinite(vmax_chm):
#             #             vmin_chm, vmax_chm = 0.0, 1.0

#             #     im.set_clim(vmin_chm, vmax_chm)

#             #     if col >= 3:
#             #         cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.02)
#             #         ticks = np.linspace(vmin_chm, vmax_chm, 5)
#             #         cbar.set_ticks(ticks)
#             #         cbar.ax.tick_params(labelsize=9)
#             #         cbar.ax.yaxis.set_major_formatter(
#             #             plt.FuncFormatter(lambda x, _: f"{x:.1f}" if x < 1 else f"{int(x)}")
#             #         )

#     plt.tight_layout()
#     plt.subplots_adjust(hspace=0.1, wspace=0.001)
#     plt.show()

def visualize_chm_s1_samples(model, dataset, start_idx: int = 0, num_samples: int = 4) -> None:
    model.eval()

    start_idx = int(start_idx)
    num_samples = int(num_samples)
    end_idx = min(start_idx + num_samples, len(dataset))
    if end_idx <= start_idx:
        print("No samples to visualize.")
        return

    n = end_idx - start_idx

    inputs = dataset.inputs[start_idx:end_idx].to(device)
    # For MultiTaskDataset, CHM targets are stored as chm_targets
    targets = dataset.chm_targets[start_idx:end_idx]

    with torch.no_grad():
        out = model(inputs)
        if isinstance(out, tuple):
            _, preds = out
        else:
            preds = out

    inputs_np = inputs.cpu().numpy()
    targets_np = targets.cpu().numpy()[:, 0, :, :]
    preds_np = preds.cpu().numpy()[:, 0, :, :]

    # 先构造所有需要显示的 band，用于统一计算每组的 vmin/vmax
    s1_list = []   # (n, 3, H, W)
    chm_list = []  # (n, 2, H, W)

    for row in range(n):
        band1 = inputs_np[row, 0, :, :]
        band2 = inputs_np[row, 1, :, :]
        # 如果只有两个 S1 通道，则用 VV/VH 构造第三个通道
        if inputs_np.shape[1] > 2:
            band3 = inputs_np[row, 2, :, :]
        else:
            denom = np.where(np.abs(band2) < 1e-6, 1e-6, band2)
            band3 = band1 / denom
        chm_true = targets_np[row]
        chm_pred = preds_np[row]

        s1_list.append(np.stack([band1, band2, band3], axis=0))
        chm_list.append(np.stack([chm_true, chm_pred], axis=0))

    fig, axes = plt.subplots(nrows=n, ncols=5, figsize=(3 * 5, 2.5 * n))
    if n == 1:
        axes = axes.reshape(1, -1)

    for row in range(n):
        row_axes = axes[row]
        band1, band2, band3 = s1_list[row]
        chm_true, chm_pred = chm_list[row]

        images = [band1, band2, band3, chm_true, chm_pred]
        titles = ["VV", "VH", "VV/VH", "CHM true", "CHM pred"]

        # --- 核心修改：计算最后两个 band 的共同范围 ---
        chm_combined = np.concatenate([chm_true, chm_pred])
        vmin_chm = float(np.nanmin(chm_combined))
        vmax_chm = float(np.nanmax(chm_combined))
        if not np.isfinite(vmin_chm) or not np.isfinite(vmax_chm):
            vmin_chm, vmax_chm = 0.0, 1.0
        # ------------------------------------------

        for col in range(5):
            ax = row_axes[col]
            band = images[col]
            cmap = "gray" if col < 3 else "viridis"

            im = ax.imshow(band, cmap=cmap)
            if row < 1:
                ax.set_title(titles[col])
            ax.axis("off")

            # 确定当前列使用的范围
            if col < 3:
                # 前三个 S1 band 使用各自的范围
                curr_vmin = float(np.nanmin(band))
                curr_vmax = float(np.nanmax(band))
                if not np.isfinite(curr_vmin) or not np.isfinite(curr_vmax):
                    curr_vmin, curr_vmax = 0.0, 1.0
            else:
                # 最后两个 CHM band 使用统一计算的范围
                curr_vmin, curr_vmax = vmin_chm, vmax_chm

            im.set_clim(curr_vmin, curr_vmax)

            # 添加 Colorbar
            cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.02)
            ticks = np.linspace(curr_vmin, curr_vmax, 5)
            cbar.set_ticks(ticks)
            cbar.ax.tick_params(labelsize=9)
            cbar.ax.yaxis.set_major_formatter(
                plt.FuncFormatter(lambda x, _: f"{x:.1f}" if x < 1 else f"{int(x)}")
            )

    plt.tight_layout()
    plt.subplots_adjust(hspace=0.1, wspace=0.3) # 稍微增加 wspace 避免 cbar 重叠
    plt.show()

"""#### scatter plot"""

def collect_regression_pairs(model, loader=test_loader, device=device, target_index: int = 0):
    model.eval()
    ys = []
    ps = []
    with torch.no_grad():
        for images, labels_cls, labels_chm in tqdm(loader, desc="Collect reg pairs"):
            images = images.to(device)
            targets = labels_chm.to(device)
            out = model(images)
            # MultiTaskUNet: (logits, chm)，其它只回归的模型：直接是 chm
            if isinstance(out, tuple):
                _, preds = out      # 取回归分支
            else:
                preds = out
            mask = torch.isfinite(targets)
            if mask.any():
                ys.append(targets[mask].detach().cpu().numpy())
                ps.append(preds[mask].detach().cpu().numpy())
    if not ys:
        return np.empty(0, dtype=np.float32), np.empty(0, dtype=np.float32)
    y_true = np.concatenate(ys, axis=0)
    y_pred = np.concatenate(ps, axis=0)
    return y_true, y_pred


def plot_regression_joint_with_hists(
    y_true,
    y_pred,
    xlabel="True CHM",
    ylabel="Predicted CHM",
    max_value=50,
    bins: int = 40,
):
    y_true = np.asarray(y_true).ravel()
    y_pred = np.asarray(y_pred).ravel()
    mask = np.isfinite(y_true) & np.isfinite(y_pred)
    if max_value is not None:
        mask &= y_true <= max_value
    y_true = y_true[mask]
    y_pred = y_pred[mask]
    if y_true.size == 0:
        print("No valid data to plot.")
        return

    rmse = float(np.sqrt(np.mean((y_pred - y_true) ** 2)))
    t_mean = float(y_true.mean())
    ss_res = float(np.sum((y_pred - y_true) ** 2))
    ss_tot = float(np.sum((y_true - t_mean) ** 2))
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else float("nan")

    fig = plt.figure(figsize=(6, 6))
    gs = fig.add_gridspec(
        2,
        2,
        width_ratios=(4, 0.8),
        height_ratios=(0.8, 4),
        wspace=0.05,
        hspace=0.05,
    )

    ax_histx = fig.add_subplot(gs[0, 0])
    ax_joint = fig.add_subplot(gs[1, 0])
    ax_histy = fig.add_subplot(gs[1, 1], sharey=ax_joint)

    ax_histx.hist(y_true, bins=bins, color="#1f77b4")

    ax_histx.hist(
        y_true,
        bins=bins,
        color="#1f77b4",
        edgecolor="black",
        linewidth=0.5,
    )
    ax_histx.set_ylabel("Count")
    ax_histx.tick_params(labelbottom=False)
    ax_histx.ticklabel_format(axis="y", style="sci", scilimits=(0, 0))

    ax_histy.hist(
        y_pred,
        bins=bins,
        orientation="horizontal",
        color="#1f77b4",
        edgecolor="black",
        linewidth=0.5,
    )
    # ax_histy.set_xlabel("Count")
    ax_histy.tick_params(labelleft=False)
    ax_histy.ticklabel_format(axis="x", style="sci", scilimits=(0, 0))

    if max_value is None:
        min_plot = 0.0
        max_plot = max(float(y_true.max()), float(y_pred.max()))
    else:
        min_plot = 0.0
        max_plot = float(max_value)
        ax_histx.set_xlim(min_plot, max_plot)
        ax_histy.set_ylim(min_plot, max_plot)

    ax_joint.hexbin(
        y_true,
        y_pred,
        gridsize=200,
        cmap="turbo",
        mincnt=1,
    )
    ax_joint.plot(
        [min_plot, max_plot],
        [min_plot, max_plot],
        linestyle="--",
        color="k",
        linewidth=1.0,
    )
    ax_joint.set_xlim(min_plot, max_plot)
    ax_joint.set_ylim(min_plot, max_plot)
    ax_joint.set_xlabel(xlabel)
    ax_joint.set_ylabel(ylabel)
    ax_joint.text(
        0.5,
        0.95,
        f"R² = {r2:.3f}, RMSE = {rmse:.3f}",
        transform=ax_joint.transAxes,
        ha="center",
        va="top",
    )




    if max_value is None:
        min_plot = 0.0
        max_plot = max(float(y_true.max()), float(y_pred.max()))
    else:
        min_plot = 0.0
        max_plot = float(max_value)
        ax_histx.set_xlim(min_plot, max_plot)
        ax_histy.set_ylim(min_plot, max_plot)

    # Fit linear regression: y_pred = a + b * y_true
    slope, intercept = np.polyfit(y_true, y_pred, 1)
    x_line = np.linspace(min_plot, max_plot, 100)
    y_reg = slope * x_line + intercept

    ax_joint.hexbin(
        y_true,
        y_pred,
        gridsize=200,
        cmap="turbo",
        mincnt=1,
    )
    # 1:1 reference line
    ax_joint.plot(
        [min_plot, max_plot],
        [min_plot, max_plot],
        linestyle="--",
        color="k",
        linewidth=1.0,
    )
    # Regression line (red dashed)
    ax_joint.plot(
        x_line,
        y_reg,
        linestyle="--",
        color="red",
        linewidth=1.0,
    )

    plt.show()

"""#### curve"""

def plot_curves(history, task="reg"):
    if task == "cls" or task == "mtl":
        fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    else:
        fig, axes = plt.subplots(1, 2, figsize=(10, 4))

    ax = axes[0]
    ax.plot(history["epoch"], history["train_loss"], label="train_loss")
    ax.plot(history["epoch"], history["val_loss"], label="val_loss")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Loss")
    ax.ticklabel_format(axis="y", style="sci", scilimits=(0, 0))
    ax.set_title("Train Curve")
    ax.legend(fontsize=7)
    ax.grid(True)

    ax = axes[1]
    ax.plot(history["lr"])
    ax.set_xlabel("Iteration")
    ax.set_ylabel("Learning rate")
    ax.ticklabel_format(axis="y", style="sci", scilimits=(0, 0))
    ax.set_title("Learning Rate Schedule")
    ax.grid(True)

    if task == "cls" or task == "mtl":
        ax = axes[2]
        ax.plot(history["epoch"], history["val_accuracy"], label="val_accuracy")
        ax.plot(history["epoch"], history["val_accuracy"], label="val_accuracy")
        ax.plot(history["epoch"], history["val_f1_micro"], label="val_f1_micro")
        ax.plot(history["epoch"], history["val_precision_micro"], label="val_precision_micro")
        ax.plot(history["epoch"], history["val_recall_micro"], label="val_recall_micro")
        ax.plot(history["epoch"], history["val_map_micro"], label="val_map_micro")
        ax.set_xlabel("Epoch")
        ax.set_ylabel("Loss")
        ax.legend(fontsize=6)
        ax.grid(True)
        ax.set_title("Train Curve")

    plt.tight_layout()
    plt.show()

"""#### evaluation"""

def inference(model, best_state, task="reg", train_loader=train_loader, val_loader=val_loader, test_loader=test_loader, criterion=None, device=device):
    if best_state is not None:
        model.load_state_dict(best_state)
    if task == "reg":
        train_metrics = evaluate_reg(model, train_loader, criterion, device, desc="Train Eval")
        val_metrics = evaluate_reg(model, val_loader, criterion, device, desc="Val Eval")
        test_metrics = evaluate_reg(model, test_loader, criterion, device, desc="Test Eval")

        print("\ntrain loss: ", f"{train_metrics['loss']:.4f}", "\tr2: ", f"{train_metrics['r2']:.4f}")
        print("val loss: ", f"{val_metrics['loss']:.4f}", "\tr2: ", f"{val_metrics['r2']:.4f}")
        print("test loss: ", f"{test_metrics['loss']:.4f}", "\tr2: ", f"{test_metrics['r2']:.4f}")
    else:
        train_metrics, train_true, train_pred = evaluate_cls(model, train_loader, criterion, device, desc="Train Eval")
        val_metrics, val_true, val_pred = evaluate_cls(model, val_loader, criterion, device, desc="Val Eval")
        test_metrics, test_true, test_pred = evaluate_cls(model, test_loader, criterion, device, desc="Test Eval")
        print("\n", classification_report(test_true, test_pred, zero_division=0, target_names=classes))
        print(
            "\t | micro\t | weighted\t \n",
            "-------", "|", "-------------", "|","-------------",
            f"\nprecision| {test_metrics['precision_micro']*100:.3f}%\t | {test_metrics['precision_weighted']*100:.3f}%\t",
            f"\nrecall\t | {test_metrics['recall_micro']*100:.3f}%\t | {test_metrics['recall_weighted']*100:.3f}%\t"
            f"\nf1\t | {test_metrics['f1_micro']*100:.3f}%\t | {test_metrics['f1_weighted']*100:.3f}%\t"
            f"\nmap\t | {test_metrics['map_micro']*100:.3f}%\t | {test_metrics['map_weighted']*100:.3f}%\t"
            f"\naccuracy | {test_metrics['accuracy']*100:.3f}%\t"
        )

def inference_mtl(model, best_state, train_loader=train_loader, val_loader=val_loader, test_loader=test_loader, cls_criterion=None, reg_criterion=None, device=device):
    if best_state is not None:
        model.load_state_dict(best_state)
    test_metrics, test_true, test_pred = evaluate(model, test_loader, cls_criterion, reg_criterion, device, desc="Test Eval",
                                                  cls_weight=configs["cls_weight"], reg_weight=configs["reg_weight"])
    print(
        "test loss: ", f"{test_metrics['loss']:.4f}",
        "cls loss: ", f"{test_metrics['cls_loss']:.4f}",
        "reg loss: ", f"{test_metrics['reg_loss']:.4f}",
        "r2: ", f"{test_metrics['r2']:.4f}"
        )
    print("\n", classification_report(test_true, test_pred, zero_division=0, target_names=classes))
    print(
        "\t | micro\t | weighted\t \n",
        "-------", "|", "-------------", "|","-------------",
        f"\nprecision| {test_metrics['precision_micro']*100:.3f}%\t | {test_metrics['precision_weighted']*100:.3f}%\t",
        f"\nrecall\t | {test_metrics['recall_micro']*100:.3f}%\t | {test_metrics['recall_weighted']*100:.3f}%\t"
        f"\nf1\t | {test_metrics['f1_micro']*100:.3f}%\t | {test_metrics['f1_weighted']*100:.3f}%\t"
        f"\nmap\t | {test_metrics['map_micro']*100:.3f}%\t | {test_metrics['map_weighted']*100:.3f}%\t"
        f"\naccuracy | {test_metrics['accuracy']*100:.3f}%\t"
    )

"""## Train"""

class_weights = torch.tensor(cw[configs["loss_fn"]], dtype=torch.float32)
num_classes = len(classes)

history_cls = {
    "epoch": [],
    "train_loss": [],
    "train_cls_loss": [],
    "lr": [],
    "val_loss": [],
    "val_cls_loss": [],
    "val_accuracy": [],
    "val_f1_micro": [],
    "val_f1_weighted": [],
    "val_precision_micro": [],
    "val_precision_weighted": [],
    "val_recall_micro": [],
    "val_recall_weighted": [],
    "val_map_micro": [],
    "val_map_weighted": [],
}

def _update_history_cls(history, epoch, train_loss, val_metrics):
    history["epoch"].append(epoch)
    history["train_loss"].append(float(train_loss))
    history["val_loss"].append(float(val_metrics["loss"]))
    history["val_accuracy"].append(float(val_metrics["accuracy"]))
    history["val_f1_micro"].append(float(val_metrics["f1_micro"]))
    history["val_f1_weighted"].append(float(val_metrics["f1_weighted"]))
    history["val_precision_micro"].append(float(val_metrics["precision_micro"]))
    history["val_precision_weighted"].append(float(val_metrics["precision_weighted"]))
    history["val_recall_micro"].append(float(val_metrics["recall_micro"]))
    history["val_recall_weighted"].append(float(val_metrics["recall_weighted"]))
    history["val_map_micro"].append(float(val_metrics["map_micro"]))
    history["val_map_weighted"].append(float(val_metrics["map_weighted"]))
    history["lr"].append(optimizer.param_groups[0]["lr"])

history_reg = {
    "epoch": [],
    "best_epoch": [],
    "train_loss": [],
    "val_loss": [],
    "val_r2": [],
    "lr": [],
}

def _update_history_reg(history, epoch, train_loss, val_metrics):
    history["epoch"].append(epoch)
    history["train_loss"].append(float(train_loss))
    history["val_loss"].append(float(val_metrics["loss"]))
    history["val_r2"].append(float(val_metrics["r2"]))
    history["lr"].append(optimizer.param_groups[0]["lr"])

"""### CLS"""

configs.update(
    max_lr=5e-5,
    weight_decay=1e-4,
    patience=8,
    dropout=0.3,
    epochs=100
)

model = MLPClassifier(in_channels=3, num_classes=num_classes, dropout=configs["dropout"], hidden_dims=(512, 256, 128)).to(device)
criterion = nn.BCEWithLogitsLoss(weight=class_weights.to(device))
optimizer = torch.optim.AdamW(model.parameters(), lr=configs["max_lr"], weight_decay=configs["weight_decay"])
scheduler = None
num_epochs = configs["epochs"]
best_val_accuracy = -1
best_state = None
patience = configs["patience"]
epochs_no_improve = 0
history_cls = {key: [] for key in history_cls}

for epoch in range(1, num_epochs + 1):
    train_loss = train_one_epoch_cls(
        model,
        train_loader,
        criterion,
        optimizer=optimizer,
        device=device,
        epoch=epoch,
        scheduler=scheduler,
    )
    val_metrics, _, _ = evaluate_cls(model, val_loader, criterion, device)
    print(
        f"Epoch {epoch}: train {train_loss:.4f}, ", "val loss: {loss:.4f}, \n\tweighted F1: {f1_weighted:.4f}, weighted mAP: {map_weighted:.4f}, "
        "accuracy: {accuracy:.4f}".format(**val_metrics)
    )
    _update_history_cls(history_cls, epoch, train_loss, val_metrics)

    if val_metrics["accuracy"] > best_val_accuracy:
        best_val_accuracy = val_metrics["accuracy"]
        best_state = model.state_dict()
        print("\tUpdated best model")
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        print(f"Patience {epochs_no_improve}/{patience} ")
    if epochs_no_improve >= patience:
        print("\tEarly stopping triggered after", epoch, "epochs")
        break

plot_curves(history_cls, task="cls")

inference(model, best_state, task="cls", criterion=criterion)

plot_cm(model)

"""### REG"""

configs.update(
    max_lr=5e-5,
    weight_decay=1e-4,
    patience=8,
    dropout=0.3,
    epochs=100,
    scheduler=None
)

model = MLPRegressor(in_channels=3, dropout=configs["dropout"], hidden_dims=(512, 256, 128)).to(device)
criterion = masked_rmse_loss
optimizer = torch.optim.AdamW(model.parameters(), lr=configs["max_lr"], weight_decay=configs["weight_decay"])
num_epochs = configs["epochs"]
best_r2 = -99
best_state = None
patience = configs["patience"]
epochs_no_improve = 0
history_reg = {key: [] for key in history_reg}

steps_per_epoch = max(len(train_loader), 1)
total_steps = steps_per_epoch * configs["epochs"]
if configs["scheduler"] == "CosineAnnealingLR":
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=total_steps,
        eta_min=configs["min_lr"],
    )
elif configs["scheduler"] == "ExponentialLR":
    gamma = (configs["base_lr"] / configs["max_lr"]) ** (1 / total_steps)
    scheduler = torch.optim.lr_scheduler.ExponentialLR(
        optimizer,
        gamma=gamma
    )
else:
    scheduler = None

for epoch in range(1, num_epochs + 1):
    train_loss = train_one_epoch_reg(
        model,
        train_loader,
        criterion,
        optimizer=optimizer,
        device=device,
        epoch=epoch,
        scheduler=scheduler,
    )
    val_metrics = evaluate_reg(model, val_loader, criterion, device)
    print(f"Epoch {epoch}: train {train_loss:.4f}", "val loss: {loss:.4f}, R2: {r2:.4f}".format(**val_metrics), f"lr: {optimizer.param_groups[0]["lr"]}")

    _update_history_reg(history_reg, epoch, train_loss, val_metrics)
    if val_metrics["r2"] > best_r2:
        best_r2 = val_metrics["r2"]
        best_state = model.state_dict()
        print("\tUpdated best model")
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        print(f"Patience {epochs_no_improve}/{patience} ")
    if epochs_no_improve >= patience:
            print("\tEarly stopping triggered after", epoch, "epochs")
            break

plot_curves(history_reg, task="reg")

inference(model, best_state, task="reg", criterion=criterion)

test_true, test_pred = collect_regression_pairs(model)
plot_regression_joint_with_hists(test_true, test_pred, max_value=40)

visualize_chm_s1_samples(model, test_ds, start_idx=42, num_samples=3)

"""## UNet

### CLS
"""

configs.update(
    base_channels=256,
    max_lr=1e-5,
    base_lr=1e-5,
    weight_decay=1e-4,
    patience=8,
    dropout=0.3,
    epochs=100
)

model = UNetClassifier(in_channels=3, num_classes=num_classes, base_channels=configs["base_channels"], dropout=configs["dropout"]).to(device)
criterion = nn.BCEWithLogitsLoss(weight=class_weights.to(device))
optimizer = torch.optim.AdamW(model.parameters(), lr=configs["max_lr"], weight_decay=configs["weight_decay"])
scheduler = None
num_epochs = configs["epochs"]
patience = configs["patience"]
epochs_no_improve = 0
best_val_accuracy = -1
best_state = None
history_cls = {key: [] for key in history}

for epoch in range(1, num_epochs + 1):
    train_loss = train_one_epoch_cls(
        model,
        train_loader,
        criterion,
        optimizer=optimizer,
        device=device,
        epoch=epoch,
        scheduler=scheduler,
    )
    val_metrics, _, _ = evaluate_cls(model, val_loader, criterion, device)
    print(
        f"Epoch {epoch}: train {train_loss:.4f}, ", "val loss: {loss:.4f}, \n\tweighted F1: {f1_weighted:.4f}, weighted mAP: {map_weighted:.4f}, "
        "accuracy: {accuracy:.4f}".format(**val_metrics)
    )
    _update_history_cls(history_cls, epoch, train_loss, val_metrics)

    if val_metrics["accuracy"] > best_val_accuracy:
        best_val_accuracy = val_metrics["accuracy"]
        best_state = model.state_dict()
        print("\tUpdated best model")
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        print(f"Patience {epochs_no_improve}/{patience} ")
    if epochs_no_improve >= patience:
        print("\tEarly stopping triggered after", epoch, "epochs")
        break

plot_curves(history_cls, task="cls")

plot_cm(model)

inference(model, best_state, criterion=criterion, task="cls")

"""### REG"""

configs.update(
  base_channels=256,
  max_lr=3e-5,
  base_lr=9e-6,
  weight_decay=1e-4,
  patience=8,
  dropout=0.3,
  epochs=100,
  scheduler="CosineAnnealingLR"
)

model = UNetRegressor(3, base_channels=configs["base_channels"], dropout=configs["dropout"]).to(device)
criterion = masked_rmse_loss
optimizer = torch.optim.AdamW(model.parameters(), lr=configs["max_lr"], weight_decay=configs["weight_decay"])
num_epochs = configs["epochs"]
patience = configs["patience"]
total_steps = len(train_loader) * num_epochs
epochs_no_improve = 0
best_r2 = -99
best_state = None
history_reg = {key: [] for key in history_reg}

if configs["scheduler"] == "CosineAnnealingLR":
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=total_steps//4,
        eta_min=configs["base_lr"],
    )
elif configs["scheduler"] == "ExponentialLR":
    # gamma = (configs["base_lr"] / configs["max_lr"]) ** (1 / total_steps)
    scheduler = torch.optim.lr_scheduler.ExponentialLR(
        optimizer,
        gamma=0.9999
    )
else:
    scheduler = None

for epoch in range(1, num_epochs + 1):
    train_loss = train_one_epoch_reg(
        model,
        train_loader,
        criterion,
        optimizer=optimizer,
        device=device,
        epoch=epoch,
        scheduler=scheduler,
    )
    val_metrics = evaluate_reg(model, val_loader, criterion, device)
    print(f"Epoch {epoch}: train {train_loss:.4f}", "val loss: {loss:.4f}, R2: {r2:.4f}".format(**val_metrics), f"lr: {optimizer.param_groups[0]["lr"]}")
    _update_history_reg(history_reg, epoch, train_loss, val_metrics)

    if val_metrics["r2"] > best_r2:
        best_r2 = val_metrics["r2"]
        best_state = model.state_dict()
        history.update(best_epoch=epoch)
        print("\tUpdated best model")
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        print(f"\tPatience {epochs_no_improve}/{patience} ")
    if epochs_no_improve >= patience:
        print("\tEarly stopping triggered after", epoch, "epochs")
        break
    if optimizer.param_groups[0]["lr"] < configs["base_lr"]+1e-8:
        scheduler = None

plot_curves(history_reg, task='reg')

inference(model, best_state, criterion=masked_rmse_loss, task="reg")

test_true, test_pred = collect_regression_pairs(model)
plot_regression_joint_with_hists(test_true, test_pred, max_value=42)

visualize_chm_s1_samples(model, test_ds, start_idx=42, num_samples=3)

"""### MTL"""

configs.update(
  base_channels=256,
  max_lr=2e-5,
  base_lr=1e-5,
  weight_decay=1e-4,
  patience=10,
  dropout=0.3,
  epochs=100,
  scheduler="None",
  cls_weight=150,
  reg_weight=0.3,
)

model = MultiTaskUNet(in_channels=3, num_classes=num_classes, base_channels=configs["base_channels"], dropout=configs["dropout"]).to(device)
cls_criterion = nn.BCEWithLogitsLoss(weight=class_weights.to(device))
reg_criterion = masked_rmse_loss
optimizer = torch.optim.AdamW(model.parameters(), lr=configs["max_lr"], weight_decay=configs["weight_decay"])
scheduler = None

num_epochs = configs["epochs"]
best_val_loss = 100
best_state = None
patience = configs["patience"]
epochs_no_improve = 0

history = {
    "epoch": [],
    "train_loss": [],
    "train_cls_loss": [],
    "train_reg_loss": [],
    "val_loss": [],
    "val_cls_loss": [],
    "val_reg_loss": [],
    "val_accuracy": [],
    "val_f1_micro": [],
    "val_f1_weighted": [],
    "val_precision_micro": [],
    "val_precision_weighted": [],
    "val_recall_micro": [],
    "val_recall_weighted": [],
    "val_map_micro": [],
    "val_map_weighted": [],
    "val_rmse": [],
    "val_r2": [],
    "lr": [],
    "w_cls": [],
    "w_reg": [],
}

for epoch in range(1, num_epochs + 1):
    train_loss, train_cls_loss, train_reg_loss = train_one_epoch(
        model, train_loader, cls_criterion, reg_criterion,
        optimizer, device, epoch=epoch, scheduler=scheduler,
        cls_weight=configs["cls_weight"], reg_weight=configs["reg_weight"],
    )

    val_metrics, _, _ = evaluate(
        model, val_loader, cls_criterion, reg_criterion,
        device, desc="Val",
        cls_weight=configs["cls_weight"], reg_weight=configs["reg_weight"],
    )

    print(f"Epoch {epoch}: Train total {train_loss:.4f}, cls: {train_cls_loss:.4f}, reg: {train_reg_loss:.4f}")
    print(
        "\tVal total: {loss:.4f}, cls: {cls_loss:.4f}, reg: {reg_loss:.4f}, \n"
        "\taccuracy: {accuracy:.4f}, r2: {r2:.4f}".format(**val_metrics)
    )

    history["epoch"].append(epoch)
    history["train_loss"].append(float(train_loss))
    history["train_cls_loss"].append(float(train_cls_loss))
    history["train_reg_loss"].append(float(train_reg_loss))
    history["val_loss"].append(float(val_metrics["loss"]))
    history["val_cls_loss"].append(float(val_metrics["cls_loss"]))
    history["val_reg_loss"].append(float(val_metrics["reg_loss"]))
    history["val_accuracy"].append(float(val_metrics["accuracy"]))
    history["val_f1_micro"].append(float(val_metrics["f1_micro"]))
    history["val_f1_weighted"].append(float(val_metrics["f1_weighted"]))
    history["val_precision_micro"].append(float(val_metrics["precision_micro"]))
    history["val_precision_weighted"].append(float(val_metrics["precision_weighted"]))
    history["val_recall_micro"].append(float(val_metrics["recall_micro"]))
    history["val_recall_weighted"].append(float(val_metrics["recall_weighted"]))
    history["val_map_micro"].append(float(val_metrics["map_micro"]))
    history["val_map_weighted"].append(float(val_metrics["map_weighted"]))
    history["val_rmse"].append(float(val_metrics["rmse"]))
    history["val_r2"].append(float(val_metrics["r2"]))
    history["lr"].append(optimizer.param_groups[0]["lr"])

    if val_metrics["loss"] < best_val_loss:
        best_val_loss = val_metrics["loss"]
        best_state = model.state_dict()
        print("\tUpdated best model")
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        print(f"Patience {epochs_no_improve}/{patience} ")
    if epochs_no_improve >= patience:
        print("\tEarly stopping triggered after", epoch, "epochs")
        break

inference_mtl(model, best_state, cls_criterion=cls_criterion, reg_criterion=reg_criterion, device=device)

plot_curves(history, task="mtl")

plot_cm(model)

test_true, test_pred = collect_regression_pairs(model)
plot_regression_joint_with_hists(test_true, test_pred, max_value=40)

visualize_chm_s1_samples(model, test_ds, start_idx=42, num_samples=3)

"""## Export"""

metrics_out = {
    "configs": configs,
    "metrics": {
        "train": train_metrics,
        "val": val_metrics,
        "test": test_metrics
    },
    "classification_report": cls_report,
    "per_class_confusion_accuracy": per_class,
    "history": history,
    "classes": classes,
}

report_path = Path(f"{BASE_DIR}/{configs["model_type"]}_s1_mtl_report.json")
with report_path.open("w", encoding='utf-8') as f:
    json.dump(metrics_out, f, indent=2, ensure_ascii=False)

# Save final/best model weights
out_path = Path(f"{BASE_DIR}/unet_s1_60m_best.pt")
torch.save(model.state_dict(), out_path)
print("Saved best model to", out_path)

