# -*- coding: utf-8 -*-
"""“mtl_unet.ipynb”的副本

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lerws8cSXc9tPczfC4ZBCZOpI663BUUP
"""

import json
from pathlib import Path

import numpy as np
import random
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import (
    f1_score,
    precision_score,
    recall_score,
    average_precision_score,
    classification_report,
    multilabel_confusion_matrix,
    accuracy_score,
    confusion_matrix,
    r2_score,
)
from sklearn.manifold import TSNE
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

def set_seed(seed: int = 42) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

from google.colab import drive
drive.mount('/content/drive')

# Folder on Google Drive that contains the preprocessed numpy arrays
# generated by the data-processing/preprocessing pipeline, e.g.
#   train_x.npy, train_y.npy, val_x.npy, val_y.npy, test_x.npy, test_y.npy
# Adjust this path to where you uploaded `training-data-60m`.
BASE_DIR = "/content/drive/MyDrive/training-data-60m"

configs = {
    # fixed
    "val_ratio": 0.1,
    "val_method": "stratify",
    "val_thres": 0.5,

    # data
    "batch_size": 8,

    # model
    "model_type": "MultiTask",
    "base_channels": 96,

    # training
    "epochs": 20,
    "patience": 5,
    "dropout": 0.3,
    "weight_decay": 0.0001,
    "max_lr": 1e-4,
    "base_lr": 1e-4,
    "scheduler": None,
    "optimizer": "AdamW",
    "loss_fn": "class_weights_inv_sqrt_freq_normalized",
    "early_stop_metric": "map_weighted",

    # multitask
    # "enable_cls_decoder": False,
    # "enable_reg_decoder": True,
    # "uncertainty_loss": False,
    # "use_self_attention": False,
    # "use_cross_attention": False,
    "cls_weight": 1,
    "reg_weight": 1,
}

"""## Data"""

CHM_MIN_THRESHOLD = 2
CHM_MAX_THRESHOLD = 50.0
CHM_PHYSICAL_MAX = CHM_MAX_THRESHOLD
S1_MIN_THRESHOLD = -10.0
S1_MAX_THRESHOLD = 10

class MultiTaskDataset(Dataset):
    def __init__(self, images: np.ndarray, labels: np.ndarray):
        super().__init__()
        if images.ndim != 4:
            raise ValueError(f"Expected images of shape (N, C, H, W), got {images.shape}")
        if images.shape[1] < 4:
            raise ValueError(
                f"Expected at least 4 channels (3 S1 + 1 CHM), got C={images.shape[1]}"
            )

        # Expected channel order from preprocessing: [VV, VH, VV/VH, CHM]
        # S1 inputs: bands 0,1,2 → clamp to [S1_MIN_THRESHOLD, S1_MAX_THRESHOLD]
        inputs = images[:, 0:3, ...].astype(np.float32)
        inputs = np.clip(inputs, S1_MIN_THRESHOLD, S1_MAX_THRESHOLD)
        self.inputs = torch.from_numpy(inputs)

        # CHM: band 3 → mask out-of-range to NaN
        chm = images[:, 3, ...].astype(np.float32)
        mask_invalid = (chm < CHM_MIN_THRESHOLD) | (chm > CHM_MAX_THRESHOLD)
        chm[mask_invalid] = np.nan
        self.chm_targets = torch.from_numpy(chm).unsqueeze(1)

        # Multi-label classification targets
        labels_arr = np.asarray(labels).astype(np.float32)
        if labels_arr.ndim != 2:
            raise ValueError(
                f"Expected labels of shape (N, num_classes) for multi-label, got {labels_arr.shape}"
            )
        self.cls_targets = torch.from_numpy(labels_arr)

    def __len__(self):
        return self.inputs.shape[0]

    def __getitem__(self, idx):
        x = self.inputs[idx]
        y_cls = self.cls_targets[idx]
        y_chm = self.chm_targets[idx]
        return x, y_cls, y_chm

def make_datasets(data_dir):
    data_dir = Path(data_dir)

    # Numpy arrays from data-processing/preprocessing/build_training_arrays.py
    # shapes: (N, 4, H, W) for *_x.npy and (N, num_classes) for *_y.npy
    train_images = np.load(data_dir / "train_x.npy")
    train_labels = np.load(data_dir / "train_y.npy")
    val_images = np.load(data_dir / "val_x.npy")
    val_labels = np.load(data_dir / "val_y.npy")
    test_images = np.load(data_dir / "test_x.npy")
    test_labels = np.load(data_dir / "test_y.npy")

    train_ds = MultiTaskDataset(train_images, train_labels)
    val_ds = MultiTaskDataset(val_images, val_labels)
    test_ds = MultiTaskDataset(test_images, test_labels)

    print(
        "Train:\t", len(train_ds),
        "\nTest:\t", len(test_ds),
        "\nVal:\t", len(val_ds)
    )

    return train_ds, val_ds, test_ds

"""### Visualization"""

def show_s1_stats():
    # Simple data preview: input bands and CHM target
    band_names = ["VV", "VH", "VV/VH"]

    NODATA = -9999

    def _mask_nodata(arr, nodata_value=NODATA):
        arr = np.array(arr, dtype=np.float32)
        arr[arr == nodata_value] = np.nan
        return arr

    # Show 3 rows: one sample from train, val, and test
    splits = [
        ("Train", train_ds),
        ("Val", val_ds),
        ("Test", test_ds),
    ]

    fig, axes = plt.subplots(3, 4, figsize=(10, 6))

    for row, (split_name, ds) in enumerate(splits):
        idx = np.random.randint(0, len(ds))
        x, y_cls, y_chm = ds[idx]
        x_np = _mask_nodata(x.numpy())               # (3, H, W)
        chm_np = _mask_nodata(y_chm.squeeze(0).numpy())  # (H, W)

        # Input bands
        for b in range(3):
            ax = axes[row, b]
            img = x_np[b]
            im = ax.imshow(img, cmap="grey")
            ax.set_title(f"{split_name} idx {idx} {band_names[b]}")
            ax.axis("off")
            fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

        # CHM target
        ax_chm = axes[row, 3]
        im_chm = ax_chm.imshow(chm_np, cmap="viridis")
        ax_chm.set_title(f"{split_name} idx {idx} CHM")
        ax_chm.axis("off")
        fig.colorbar(im_chm, ax=ax_chm, fraction=0.046, pad=0.04)

    plt.tight_layout()
    plt.show()

    # Bandwise statistics over training inputs (nodata masked)
    inputs = train_ds.inputs.numpy().astype(np.float32)  # (N, C, H, W)
    inputs[inputs == NODATA] = np.nan
    C = inputs.shape[1]

    means = np.nanmean(inputs, axis=(0, 2, 3))
    stds = np.nanstd(inputs, axis=(0, 2, 3))
    mins = np.nanmin(inputs, axis=(0, 2, 3))
    maxs = np.nanmax(inputs, axis=(0, 2, 3))

    for c in range(C):
        name = band_names[c] if c < len(band_names) else f"Band {c}"
        print(f"{name}: mean={means[c]:.4f}, std={stds[c]:.4f}, min={mins[c]:.4f}, max={maxs[c]:.4f}")

    # Quantiles for input bands (training set)
    percentiles = [1, 2, 5, 95, 98, 99]
    print("\nInput band quantiles (training set):")
    for c in range(C):
        name = band_names[c] if c < len(band_names) else f"Band {c}"
        band = inputs[:, c, :, :].ravel()
        band = band[~np.isnan(band)]
        if band.size == 0:
            continue
        q_vals = np.percentile(band, percentiles)
        q_str = ", ".join([f"q{p}={v:.4f}" for p, v in zip(percentiles, q_vals)])
        print(f"{name}: {q_str}")

    # Bandwise histograms (training set, nodata masked)
    fig, axes = plt.subplots(1, C, figsize=(4 * C, 3))
    if C == 1:
        axes = [axes]

    for c in range(C):
        ax = axes[c]
        band = inputs[:, c, :, :].ravel()
        band = band[~np.isnan(band)]
        if band.size == 0:
            continue
        ax.hist(band, bins=50, alpha=0.7)
        name = band_names[c] if c < len(band_names) else f"Band {c}"
        ax.set_title(name)

    plt.tight_layout()
    plt.show()

def show_chm_stats():
    # Simple data preview: input bands and CHM target
    band_names = ["VV", "VH", "VV/VH"]

    NODATA = -9999

    def _mask_nodata(arr, nodata_value=NODATA):
        arr = np.array(arr, dtype=np.float32)
        arr[arr == nodata_value] = np.nan
        return arr

    # Show 3 rows: one sample from train, val, and test
    splits = [
        ("Train", train_ds),
        ("Val", val_ds),
        ("Test", test_ds),
    ]
    percentiles = [1, 2, 5, 95, 98, 99]
    # CHM statistics and quantiles (training set)
    chm_all = train_ds.chm_targets.numpy().astype(np.float32)  # (N, 1, H, W)
    chm_vals = chm_all.ravel()
    chm_vals = chm_vals[~np.isnan(chm_vals) & (chm_vals != NODATA)]

    if chm_vals.size > 0:
        chm_mean = float(np.mean(chm_vals))
        chm_std = float(np.std(chm_vals))
        chm_min = float(np.min(chm_vals))
        chm_max = float(np.max(chm_vals))
        print("\nCHM (train): mean={:.4f}, std={:.4f}, min={:.4f}, max={:.4f}".format(chm_mean, chm_std, chm_min, chm_max))

        chm_q = np.percentile(chm_vals, percentiles)
        chm_q_str = ", ".join([f"q{p}={v:.4f}" for p, v in zip(percentiles, chm_q)])
        print(f"CHM quantiles: {chm_q_str}")

        # CHM histogram (training set)
        plt.figure(figsize=(4, 3))
        plt.hist(chm_vals, bins=50, alpha=0.7)
        plt.title("CHM (train)")
        plt.xlabel("CHM")
        plt.ylabel("Count")
        plt.tight_layout()
        plt.show()

"""## Model - MLP"""

class MLPClassifier(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        height: int = 6,
        width: int = 6,
        hidden_dims: tuple[int, ...] = (256, 256),
        dropout: float = 0.3,
    ) -> None:
        super().__init__()
        self.in_channels = in_channels
        self.height = height
        self.width = width
        in_features = in_channels * height * width

        layers = []
        prev_dim = in_features
        for h in hidden_dims:
            layers.append(nn.Linear(prev_dim, h))
            layers.append(nn.BatchNorm1d(h))
            layers.append(nn.ReLU(inplace=True))
            if dropout > 0.0:
                layers.append(nn.Dropout(p=dropout))
            prev_dim = h
        layers.append(nn.Linear(prev_dim, num_classes))
        self.mlp = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if x.dim() == 4:
            x = x.view(x.size(0), -1)
        return self.mlp(x)


class MLPRegressor(nn.Module):
    def __init__(
        self,
        in_channels: int,
        height: int = 6,
        width: int = 6,
        hidden_dims: tuple[int, ...] = (256, 256),
        dropout: float = 0.3,
    ) -> None:
        super().__init__()
        self.in_channels = in_channels
        self.height = height
        self.width = width
        in_features = in_channels * height * width
        out_features = height * width

        layers = []
        prev_dim = in_features
        for h in hidden_dims:
            layers.append(nn.Linear(prev_dim, h))
            layers.append(nn.BatchNorm1d(h))
            layers.append(nn.ReLU(inplace=True))
            if dropout > 0.0:
                layers.append(nn.Dropout(p=dropout))
            prev_dim = h
        layers.append(nn.Linear(prev_dim, out_features))
        self.mlp = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        if x.dim() == 4:
            x = x.view(x.size(0), -1)
        out = self.mlp(x)
        batch_size = out.size(0)
        out = out.view(batch_size, 1, self.height, self.width)
        out = F.softplus(out)
        out = torch.clamp(out, 0.0, CHM_PHYSICAL_MAX)
        return out


class MultiTaskMLP(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        height: int = 6,
        width: int = 6,
        hidden_dims_cls: tuple[int, ...] = (256, 256),
        hidden_dims_reg: tuple[int, ...] = (256, 256),
        dropout: float = 0.3,
        use_uncertainty_loss: bool = True,
        cls_weight: float = 1.0,
        reg_weight: float = 0.5,
    ) -> None:
        super().__init__()
        self.use_uncertainty_loss = use_uncertainty_loss
        self.cls_weight = cls_weight
        self.reg_weight = reg_weight
        self.min_task_weight = 0.1
        self.max_task_weight = 5.0
        self.num_classes = num_classes

        self.cls_mlp = MLPClassifier(
            in_channels=in_channels,
            num_classes=num_classes,
            height=height,
            width=width,
            hidden_dims=hidden_dims_cls,
            dropout=dropout,
        )
        self.reg_mlp = MLPRegressor(
            in_channels=in_channels,
            height=height,
            width=width,
            hidden_dims=hidden_dims_reg,
            dropout=dropout,
        )

        if self.use_uncertainty_loss:
            self.log_sigma_cls = nn.Parameter(torch.zeros(1))
            self.log_sigma_reg = nn.Parameter(torch.zeros(1))

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        logits = self.cls_mlp(x)
        chm = self.reg_mlp(x)
        return logits, chm

    def compute_total_loss(
        self,
        loss_cls: torch.Tensor,
        loss_reg: torch.Tensor,
    ) -> torch.Tensor:
        if self.use_uncertainty_loss:
            w_cls = 0.5 * torch.exp(-self.log_sigma_cls)
            w_reg = 0.5 * torch.exp(-self.log_sigma_reg)

            w_min = self.min_task_weight
            w_max = self.max_task_weight
            w_cls = torch.clamp(w_cls, w_min, w_max)
            w_reg = torch.clamp(w_reg, w_min, w_max)

            loss = w_cls * loss_cls + w_reg * loss_reg
            return loss
        return self.cls_weight * loss_cls + self.reg_weight * loss_reg

    def get_task_weights(self) -> tuple[float, float]:
        if self.use_uncertainty_loss:
            w_cls = 0.5 * torch.exp(-self.log_sigma_cls)
            w_reg = 0.5 * torch.exp(-self.log_sigma_reg)

            w_min = self.min_task_weight
            w_max = self.max_task_weight
            w_cls = torch.clamp(w_cls, w_min, w_max)
            w_reg = torch.clamp(w_reg, w_min, w_max)
        else:
            first_param = next(self.parameters())
            device = first_param.device
            w_cls = torch.tensor(self.cls_weight, device=device)
            w_reg = torch.tensor(self.reg_weight, device=device)
        return float(w_cls.item()), float(w_reg.item())

class DoubleConv(nn.Module):
    def __init__(self, in_channels: int, out_channels: int) -> None:
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)


class Down(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: int,
        padding: int,
    ) -> None:
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(
                in_channels,
                out_channels,
                kernel_size=kernel_size,
                stride=stride,
                padding=padding,
                bias=False,
            ),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)


class Up(nn.Module):
    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        kernel_size: int,
        stride: int,
    ) -> None:
        super().__init__()
        self.up = nn.ConvTranspose2d(
            in_channels,
            in_channels // 2,
            kernel_size=kernel_size,
            stride=stride,
        )
        # after upsampling, features are concatenated with skip connection
        # so DoubleConv expects in_channels and produces out_channels
        self.conv = DoubleConv(in_channels, out_channels)

    def forward(self, x: torch.Tensor, skip: torch.Tensor) -> torch.Tensor:
        x = self.up(x)
        x = torch.cat([x, skip], dim=1)
        x = self.conv(x)
        return x


class UNetRegressor(nn.Module):
    def __init__(
        self,
        in_channels: int,
        base_channels: int = 32,
        dropout: float = 0.3,
    ) -> None:
        super().__init__()

        self.enc1 = DoubleConv(in_channels, base_channels)

        self.down1 = Down(
            in_channels=base_channels,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=2,
            padding=1,
        )
        self.enc2 = DoubleConv(base_channels * 2, base_channels * 2)

        self.down2 = Down(
            in_channels=base_channels * 2,
            out_channels=base_channels * 4,
            kernel_size=3,
            stride=3,
            padding=0,
        )

        self.bottleneck = DoubleConv(base_channels * 4, base_channels * 4)

        self.up2 = Up(
            in_channels=base_channels * 4,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=3,
        )
        self.dropout2 = nn.Dropout2d(p=dropout)

        self.up1 = Up(
            in_channels=base_channels * 2,
            out_channels=base_channels,
            kernel_size=2,
            stride=2,
        )

        self.out_conv = nn.Conv2d(base_channels, 1, kernel_size=1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x1 = self.enc1(x)
        x2 = self.down1(x1)

        x3 = self.enc2(x2)
        x4 = self.down2(x3)

        x5 = self.bottleneck(x4)

        x6 = self.up2(x5, x3)
        x6 = self.dropout2(x6)

        x7 = self.up1(x6, x1)

        raw = self.out_conv(x7)
        chm = F.softplus(raw)
        chm = torch.clamp(chm, 0.0, CHM_PHYSICAL_MAX)
        return chm


class UNetClassifier(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        base_channels: int = 32,
        dropout: float = 0.3,
    ) -> None:
        super().__init__()

        self.num_classes = num_classes

        self.enc1 = DoubleConv(in_channels, base_channels)

        self.down1 = Down(
            in_channels=base_channels,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=2,
            padding=1,
        )
        self.enc2 = DoubleConv(base_channels * 2, base_channels * 2)

        self.down2 = Down(
            in_channels=base_channels * 2,
            out_channels=base_channels * 4,
            kernel_size=3,
            stride=3,
            padding=0,
        )

        self.bottleneck = DoubleConv(base_channels * 4, base_channels * 4)

        self.up2 = Up(
            in_channels=base_channels * 4,
            out_channels=base_channels * 2,
            kernel_size=3,
            stride=3,
        )
        self.dropout2 = nn.Dropout2d(p=dropout)

        self.up1 = Up(
            in_channels=base_channels * 2,
            out_channels=base_channels,
            kernel_size=2,
            stride=2,
        )

        self.out_conv = nn.Conv2d(base_channels, num_classes, kernel_size=1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x1 = self.enc1(x)
        x2 = self.down1(x1)

        x3 = self.enc2(x2)
        x4 = self.down2(x3)

        x5 = self.bottleneck(x4)

        x6 = self.up2(x5, x3)
        x6 = self.dropout2(x6)

        x7 = self.up1(x6, x1)

        logits_map = self.out_conv(x7)
        logits = logits_map.mean(dim=(2, 3))
        return logits

"""## Model - UNet

### Transposed UNet
"""

class MultiTaskTransposedUNet(nn.Module):
    def __init__(
        self,
        in_channels: int,
        num_classes: int,
        base_channels: int = 32,
        dropout: float = 0.3,
        use_uncertainty_loss: bool = True,
        cls_weight: float = 1.0,
        reg_weight: float = 0.5,
        enable_cls_decoder: bool = True,
        enable_reg_decoder: bool = True,
        enable_self_attention: bool = False,
        enable_cross_attention: bool = False,
    ):
        super().__init__()

        self.use_uncertainty_loss = use_uncertainty_loss
        self.cls_weight = cls_weight
        self.reg_weight = reg_weight
        self.min_task_weight = 0.1
        self.max_task_weight = 5.0

        self.enable_cls_decoder = enable_cls_decoder
        self.enable_reg_decoder = enable_reg_decoder
        self.num_classes = num_classes

        self.enable_self_attention = enable_self_attention
        self.enable_cross_attention = enable_cross_attention

        self.enc1 = DoubleConv(in_channels, base_channels)

        self.down1 = nn.Sequential(
            nn.Conv2d(base_channels, base_channels * 2, kernel_size=3, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(base_channels * 2),
            nn.ReLU(inplace=True),
        )
        self.enc2 = DoubleConv(base_channels * 2, base_channels * 2)

        self.down2 = nn.Sequential(
            nn.Conv2d(base_channels * 2, base_channels * 4, kernel_size=3, stride=3, padding=0, bias=False),
            nn.BatchNorm2d(base_channels * 4),
            nn.ReLU(inplace=True),
        )

        self.bottleneck = DoubleConv(base_channels * 4, base_channels * 4)

        if self.enable_cls_decoder:
            self.up2_cls = nn.ConvTranspose2d(
                base_channels * 4,
                base_channels * 2,
                kernel_size=3,
                stride=3,
            )
            self.dec2_cls = DoubleConv(base_channels * 4, base_channels * 2)
            self.dropout2_cls = nn.Dropout2d(p=dropout)

            self.up1_cls = nn.ConvTranspose2d(
                base_channels * 2,
                base_channels,
                kernel_size=2,
                stride=2,
            )
            self.dec1_cls = DoubleConv(base_channels * 2, base_channels)

            if self.enable_self_attention:
                self.self_att_cls = SelfAttentionBlock(base_channels)
            else:
                self.self_att_cls = None

            cls_in_channels = base_channels
            if self.enable_self_attention and self.enable_cross_attention and self.enable_reg_decoder:
                cls_in_channels = base_channels * 2

            self.classifier = nn.Conv2d(cls_in_channels, num_classes, kernel_size=1)
        else:
            self.up2_cls = None
            self.dec2_cls = None
            self.dropout2_cls = None
            self.up1_cls = None
            self.dec1_cls = None
            self.self_att_cls = None
            self.classifier = None

        if self.enable_reg_decoder:
            self.up2_reg = nn.ConvTranspose2d(
                base_channels * 4,
                base_channels * 2,
                kernel_size=3,
                stride=3,
            )
            self.dec2_reg = DoubleConv(base_channels * 4, base_channels * 2)
            self.dropout2_reg = nn.Dropout2d(p=dropout)

            self.up1_reg = nn.ConvTranspose2d(
                base_channels * 2,
                base_channels,
                kernel_size=2,
                stride=2,
            )
            self.dec1_reg = DoubleConv(base_channels * 2, base_channels)

            if self.enable_self_attention:
                self.self_att_reg = SelfAttentionBlock(base_channels)
            else:
                self.self_att_reg = None

            reg_in_channels = base_channels
            if self.enable_self_attention and self.enable_cross_attention and self.enable_cls_decoder:
                reg_in_channels = base_channels * 2

            self.out_conv = nn.Conv2d(reg_in_channels, 1, kernel_size=1)
        else:
            self.up2_reg = None
            self.dec2_reg = None
            self.dropout2_reg = None
            self.up1_reg = None
            self.dec1_reg = None
            self.self_att_reg = None
            self.out_conv = None

        if self.enable_cross_attention and self.enable_cls_decoder and self.enable_reg_decoder:
            self.cross_att = CrossTaskAttentionMultiScale(base_channels)
            self.alpha_cls = nn.Parameter(torch.ones(base_channels))
            self.alpha_reg = nn.Parameter(torch.ones(base_channels))
        else:
            self.cross_att = None
            self.alpha_cls = None
            self.alpha_reg = None

        # ==================== Uncertainty loss parameters ====================
        if self.use_uncertainty_loss:
            self.log_sigma_cls = nn.Parameter(torch.zeros(1))
            self.log_sigma_reg = nn.Parameter(torch.zeros(1))

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        device = x.device
        dtype = x.dtype
        batch_size = x.size(0)
        height, width = x.size(2), x.size(3)

        x1 = self.enc1(x)
        x2 = self.down1(x1)

        x3 = self.enc2(x2)
        x4 = self.down2(x3)

        x5 = self.bottleneck(x4)

        x7_cls = None
        x7_reg = None

        if self.enable_cls_decoder and self.classifier is not None:
            x6_cls = self.up2_cls(x5)
            x6_cls = torch.cat([x6_cls, x3], dim=1)
            x6_cls = self.dec2_cls(x6_cls)
            x6_cls = self.dropout2_cls(x6_cls)

            x7_cls = self.up1_cls(x6_cls)
            x7_cls = torch.cat([x7_cls, x1], dim=1)
            x7_cls = self.dec1_cls(x7_cls)

        if self.enable_reg_decoder and self.out_conv is not None:
            x6_reg = self.up2_reg(x5)
            x6_reg = torch.cat([x6_reg, x3], dim=1)
            x6_reg = self.dec2_reg(x6_reg)
            x6_reg = self.dropout2_reg(x6_reg)

            x7_reg = self.up1_reg(x6_reg)
            x7_reg = torch.cat([x7_reg, x1], dim=1)
            x7_reg = self.dec1_reg(x7_reg)

        f_cls = x7_cls
        f_reg = x7_reg

        if self.enable_self_attention:
            f_cls_self = self.self_att_cls(f_cls) if f_cls is not None and self.self_att_cls is not None else f_cls
            f_reg_self = self.self_att_reg(f_reg) if f_reg is not None and self.self_att_reg is not None else f_reg
        else:
            f_cls_self = f_cls
            f_reg_self = f_reg

        has_cross = (
            self.enable_cross_attention
            and self.cross_att is not None
            and f_cls is not None
            and f_reg is not None
        )

        if has_cross:
            cross_cls, cross_reg = self.cross_att(f_cls, f_reg)

            alpha_cls = self.alpha_cls.view(1, -1, 1, 1)
            alpha_reg = self.alpha_reg.view(1, -1, 1, 1)
            cross_cls_scaled = alpha_cls * cross_cls
            cross_reg_scaled = alpha_reg * cross_reg

            if self.enable_self_attention:
                fused_cls = torch.cat([cross_cls_scaled, f_cls_self], dim=1)
                fused_reg = torch.cat([cross_reg_scaled, f_reg_self], dim=1)
            else:
                fused_cls = cross_cls_scaled
                fused_reg = cross_reg_scaled
        else:
            fused_cls = f_cls_self
            fused_reg = f_reg_self

        if self.enable_cls_decoder and self.classifier is not None and fused_cls is not None:
            logits_map = self.classifier(fused_cls)
            logits = logits_map.mean(dim=(2, 3))
        else:
            logits = torch.zeros(batch_size, self.num_classes, device=device, dtype=dtype)

        if self.enable_reg_decoder and self.out_conv is not None and fused_reg is not None:
            raw = self.out_conv(fused_reg)
            chm = F.softplus(raw)
            chm = torch.clamp(chm, 0.0, CHM_PHYSICAL_MAX)
        else:
            chm = torch.zeros(batch_size, 1, height, width, device=device, dtype=dtype)

        return logits, chm

    def compute_total_loss(
        self,
        loss_cls: torch.Tensor,
        loss_reg: torch.Tensor,
    ) -> torch.Tensor:
        if self.use_uncertainty_loss:
            w_cls = 0.5 * torch.exp(-self.log_sigma_cls)
            w_reg = 0.5 * torch.exp(-self.log_sigma_reg)

            w_min = self.min_task_weight
            w_max = self.max_task_weight
            w_cls = torch.clamp(w_cls, w_min, w_max)
            w_reg = torch.clamp(w_reg, w_min, w_max)

            loss = w_cls * loss_cls + w_reg * loss_reg
            return loss
        return self.cls_weight * loss_cls + self.reg_weight * loss_reg

    def get_task_weights(self) -> tuple[float, float]:
        """获取当前任务权重"""
        if self.use_uncertainty_loss:
            w_cls = 0.5 * torch.exp(-self.log_sigma_cls)
            w_reg = 0.5 * torch.exp(-self.log_sigma_reg)

            w_min = self.min_task_weight
            w_max = self.max_task_weight
            w_cls = torch.clamp(w_cls, w_min, w_max)
            w_reg = torch.clamp(w_reg, w_min, w_max)
        else:
            first_param = next(self.parameters())
            device = first_param.device
            w_cls = torch.tensor(self.cls_weight, device=device)
            w_reg = torch.tensor(self.reg_weight, device=device)
        return float(w_cls.item()), float(w_reg.item())

"""## Functions

### Loss Function
"""

def masked_rmse_loss(preds: torch.Tensor, targets: torch.Tensor) -> torch.Tensor:
    mask = ~torch.isnan(targets)
    if not mask.any():
        return (preds * 0.0).sum()
    diff = preds[mask] - targets[mask]
    return torch.sqrt(torch.mean(diff ** 2))

"""### ind - clf"""

def train_one_epoch_cls(model, loader, cls_criterion, optimizer, device, epoch=None, lr_history=None, scheduler=None):
    model.train()
    total_loss = 0.0
    total_samples = 0

    for images, labels_cls, _ in tqdm(loader, desc=f"Train Cls {epoch}" if epoch is not None else "Train Cls"):
        images = images.to(device)
        labels_cls = labels_cls.to(device)

        optimizer.zero_grad()
        out = model(images)
        logits = out[0] if isinstance(out, tuple) else out

        loss = cls_criterion(logits, labels_cls)
        loss.backward()
        optimizer.step()

        if scheduler is not None:
            scheduler.step()

        if lr_history is not None:
            lr_history.append(optimizer.param_groups[0]["lr"])

        batch_size = images.size(0)
        total_loss += float(loss.item()) * batch_size
        total_samples += batch_size

    avg_loss = total_loss / max(total_samples, 1)
    return avg_loss


def evaluate_cls(model, loader, cls_criterion, device, desc="Eval Cls"):
    model.eval()
    total_loss = 0.0
    total_samples = 0

    all_true_cls = []
    all_pred_cls = []
    all_logits_cls = []

    with torch.no_grad():
        for images, labels_cls, _ in tqdm(loader, desc=desc):
            images = images.to(device)
            labels_cls = labels_cls.to(device)

            out = model(images)
            logits = out[0] if isinstance(out, tuple) else out
            loss = cls_criterion(logits, labels_cls)

            batch_size = images.size(0)
            total_loss += float(loss.item()) * batch_size
            total_samples += batch_size

            probs = torch.sigmoid(logits)
            preds_cls = (probs >= configs["val_thres"]).float()

            all_true_cls.append(labels_cls.cpu().numpy())
            all_pred_cls.append(preds_cls.cpu().numpy())
            all_logits_cls.append(logits.cpu().numpy())

    avg_loss = total_loss / max(total_samples, 1)

    y_true_cls = np.concatenate(all_true_cls, axis=0) if all_true_cls else np.array([])
    y_pred_cls = np.concatenate(all_pred_cls, axis=0) if all_pred_cls else np.array([])
    y_logits = np.concatenate(all_logits_cls, axis=0) if all_logits_cls else np.array([])

    if y_true_cls.size > 0:
        y_scores = torch.sigmoid(torch.from_numpy(y_logits)).numpy()

        f1_micro = f1_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
        f1_weighted = f1_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
        precision_micro = precision_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
        precision_weighted = precision_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
        recall_micro = recall_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
        recall_weighted = recall_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
        map_micro = average_precision_score(y_true_cls, y_scores, average="micro")
        map_weighted = average_precision_score(y_true_cls, y_scores, average="weighted")
        accuracy = accuracy_score(y_true_cls, y_pred_cls)
    else:
        accuracy = float("nan")
        f1_micro = float("nan")
        f1_weighted = float("nan")
        precision_micro = float("nan")
        precision_weighted = float("nan")
        recall_micro = float("nan")
        recall_weighted = float("nan")
        map_micro = float("nan")
        map_weighted = float("nan")

    metrics = {
        "loss": avg_loss,
        "accuracy": accuracy,
        "f1_micro": f1_micro,
        "f1_weighted": f1_weighted,
        "precision_micro": precision_micro,
        "precision_weighted": precision_weighted,
        "recall_micro": recall_micro,
        "recall_weighted": recall_weighted,
        "map_micro": map_micro,
        "map_weighted": map_weighted,
    }

    return metrics, y_true_cls, y_pred_cls

"""### ind -reg"""

def train_one_epoch_reg(model, loader, reg_criterion, optimizer, device, epoch=None, lr_history=None, scheduler=None):
    model.train()
    total_loss = 0.0
    total_samples = 0

    for images, _, labels_chm in tqdm(loader, desc=f"Train Reg {epoch}" if epoch is not None else "Train Reg"):
        images = images.to(device)
        labels_chm = labels_chm.to(device)

        optimizer.zero_grad()
        out = model(images)
        if isinstance(out, tuple):
            _, chm_pred = out
        else:
            chm_pred = out

        loss = reg_criterion(chm_pred, labels_chm)
        loss.backward()
        optimizer.step()

        if scheduler is not None:
            scheduler.step()

        if lr_history is not None:
            lr_history.append(optimizer.param_groups[0]["lr"])

        batch_size = images.size(0)
        total_loss += float(loss.item()) * batch_size
        total_samples += batch_size

    avg_loss = total_loss / max(total_samples, 1)
    return avg_loss


def evaluate_reg(model, loader, reg_criterion, device, desc="Eval Reg"):
    model.eval()
    total_loss = 0.0
    total_samples = 0

    all_true_chm = []
    all_pred_chm = []

    with torch.no_grad():
        for images, _, labels_chm in tqdm(loader, desc=desc):
            images = images.to(device)
            labels_chm = labels_chm.to(device)

            out = model(images)
            if isinstance(out, tuple):
                _, chm_pred = out
            else:
                chm_pred = out

            loss = reg_criterion(chm_pred, labels_chm)

            batch_size = images.size(0)
            total_loss += float(loss.item()) * batch_size
            total_samples += batch_size

            mask = ~torch.isnan(labels_chm)
            if mask.any():
                all_true_chm.append(labels_chm[mask].cpu().numpy())
                all_pred_chm.append(chm_pred[mask].cpu().numpy())

    avg_loss = total_loss / max(total_samples, 1)

    if all_true_chm:
        y_true_chm_np = np.concatenate(all_true_chm, axis=0).reshape(-1)
        y_pred_chm_np = np.concatenate(all_pred_chm, axis=0).reshape(-1)

        y_true_chm_t = torch.from_numpy(y_true_chm_np)
        y_pred_chm_t = torch.from_numpy(y_pred_chm_np)
        rmse = float(masked_rmse_loss(y_pred_chm_t, y_true_chm_t).item())
        r2 = float(r2_score(y_true_chm_np, y_pred_chm_np))
    else:
        rmse = float("nan")
        r2 = float("nan")

    metrics = {
        "loss": avg_loss,
        "reg_loss": avg_loss,
        "rmse": rmse,
        "r2": r2,
    }

    return metrics

"""### Multi"""

def train_one_epoch(model, loader, cls_criterion, reg_criterion, optimizer, device, epoch=None, lr_history=None, scheduler=None):
    model.train()
    total_loss = 0.0
    total_cls_loss = 0.0
    total_reg_loss = 0.0
    total_samples = 0

    for images, labels_cls, labels_chm in tqdm(loader, desc=f"Train {epoch}" if epoch is not None else "Train"):
        images = images.to(device)
        labels_cls = labels_cls.to(device)
        labels_chm = labels_chm.to(device)

        optimizer.zero_grad()
        logits, chm_pred = model(images)

        loss_cls = cls_criterion(logits, labels_cls)
        loss_cls = torch.zeros(1, device=device, dtype=logits.dtype)
        loss_reg = reg_criterion(chm_pred, labels_chm)
        loss_reg = torch.zeros(1, device=device, dtype=chm_pred.dtype)
        loss = model.compute_total_loss(loss_cls, loss_reg)

        loss.backward()
        optimizer.step()

        if scheduler is not None:
            scheduler.step()

        if lr_history is not None:
            lr_history.append(optimizer.param_groups[0]["lr"])

        batch_size = images.size(0)
        total_loss += float(loss.item()) * batch_size
        total_cls_loss += float(loss_cls.item()) * batch_size
        total_reg_loss += float(loss_reg.item()) * batch_size
        total_samples += batch_size

    avg_loss = total_loss / max(total_samples, 1)
    avg_cls_loss = total_cls_loss / max(total_samples, 1)
    avg_reg_loss = total_reg_loss / max(total_samples, 1)
    return avg_loss, avg_cls_loss, avg_reg_loss

def evaluate(model, loader, cls_criterion, reg_criterion, device, desc="Eval"):
    model.eval()
    total_loss = 0.0
    total_cls_loss = 0.0
    total_reg_loss = 0.0
    total_samples = 0

    all_true_cls = []   # multi-hot ground truth
    all_pred_cls = []   # multi-hot predictions (after threshold)
    all_logits_cls = [] # raw logits
    all_true_chm = []
    all_pred_chm = []

    with torch.no_grad():
        for images, labels_cls, labels_chm in tqdm(loader, desc=desc):
            images = images.to(device)
            labels_cls = labels_cls.to(device)
            labels_chm = labels_chm.to(device)

            logits, chm_pred = model(images)

            loss_cls = cls_criterion(logits, labels_cls)
            loss_cls = torch.zeros(1, device=device, dtype=logits.dtype)
            loss_reg = reg_criterion(chm_pred, labels_chm)
            loss_reg = torch.zeros(1, device=device, dtype=chm_pred.dtype)
            loss = model.compute_total_loss(loss_cls, loss_reg)

            batch_size = images.size(0)
            total_loss += float(loss.item()) * batch_size
            total_cls_loss += float(loss_cls.item()) * batch_size
            total_reg_loss += float(loss_reg.item()) * batch_size
            total_samples += batch_size


            probs = torch.sigmoid(logits)
            preds_cls = (probs >= configs["val_thres"]).float()

            all_true_cls.append(labels_cls.cpu().numpy())
            all_pred_cls.append(preds_cls.cpu().numpy())
            all_logits_cls.append(logits.cpu().numpy())

            mask = ~torch.isnan(labels_chm)
            if mask.any():
                all_true_chm.append(labels_chm[mask].cpu().numpy())
                all_pred_chm.append(chm_pred[mask].cpu().numpy())

    avg_loss = total_loss / max(total_samples, 1)
    avg_cls_loss = total_cls_loss / max(total_samples, 1)
    avg_reg_loss = total_reg_loss / max(total_samples, 1)

    y_true_cls = np.concatenate(all_true_cls, axis=0) if all_true_cls else np.array([])
    y_pred_cls = np.concatenate(all_pred_cls, axis=0) if all_pred_cls else np.array([])
    y_logits = np.concatenate(all_logits_cls, axis=0) if all_logits_cls else np.array([])

    if enable_cls and y_true_cls.size > 0:
        # Multi-label metrics
        y_scores = torch.sigmoid(torch.from_numpy(y_logits)).numpy()

    f1_micro = f1_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
    f1_weighted = f1_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
    precision_micro = precision_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
    precision_weighted = precision_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
    recall_micro = recall_score(y_true_cls, y_pred_cls, average="micro", zero_division=0)
    recall_weighted = recall_score(y_true_cls, y_pred_cls, average="weighted", zero_division=0)
    map_micro = average_precision_score(y_true_cls, y_scores, average="micro")
    map_weighted = average_precision_score(y_true_cls, y_scores, average="weighted")
    accuracy = accuracy_score(y_true_cls, y_pred_cls)

    y_true_chm_np = np.concatenate(all_true_chm, axis=0).reshape(-1)
    y_pred_chm_np = np.concatenate(all_pred_chm, axis=0).reshape(-1)

    y_true_chm_t = torch.from_numpy(y_true_chm_np)
    y_pred_chm_t = torch.from_numpy(y_pred_chm_np)
    rmse = float(masked_rmse_loss(y_pred_chm_t, y_true_chm_t).item())

    r2 = float(r2_score(y_true_chm_np, y_pred_chm_np))


    metrics = {
        "loss": avg_loss,
        "cls_loss": avg_cls_loss,
        "reg_loss": avg_reg_loss,
        "f1_micro": f1_micro,
        "f1_weighted": f1_weighted,
        "precision_micro": precision_micro,
        "precision_weighted": precision_weighted,
        "recall_micro": recall_micro,
        "recall_weighted": recall_weighted,
        "map_micro": map_micro,
        "map_weighted": map_weighted,
        "accuracy": accuracy,
        "rmse": rmse,
        "r2": r2,
    }

    return metrics, y_true_cls, y_pred_cls

"""### Visualization"""

def visualize_chm_s1_samples(model, dataset, start_idx: int = 0, num_samples: int = 4) -> None:
    model.eval()

    start_idx = int(start_idx)
    num_samples = int(num_samples)
    end_idx = min(start_idx + num_samples, len(dataset))
    if end_idx <= start_idx:
        print("No samples to visualize.")
        return

    n = end_idx - start_idx

    inputs = dataset.inputs[start_idx:end_idx].to(device)
    # For MultiTaskDataset, CHM targets are stored as chm_targets
    targets = dataset.chm_targets[start_idx:end_idx]

    with torch.no_grad():
        preds = model(inputs)

    inputs_np = inputs.cpu().numpy()
    targets_np = targets.cpu().numpy()[:, 0, :, :]
    preds_np = preds.cpu().numpy()[:, 0, :, :]

    # 先构造所有需要显示的 band，用于统一计算每组的 vmin/vmax
    s1_list = []   # (n, 3, H, W)
    chm_list = []  # (n, 2, H, W)

    for row in range(n):
        band1 = inputs_np[row, 0, :, :]
        band2 = inputs_np[row, 1, :, :]
        # 如果只有两个 S1 通道，则用 VV/VH 构造第三个通道
        if inputs_np.shape[1] > 2:
            band3 = inputs_np[row, 2, :, :]
        else:
            denom = np.where(np.abs(band2) < 1e-6, 1e-6, band2)
            band3 = band1 / denom
        chm_true = targets_np[row]
        chm_pred = preds_np[row]

        s1_list.append(np.stack([band1, band2, band3], axis=0))
        chm_list.append(np.stack([chm_true, chm_pred], axis=0))

    # Layout similar to gen-chm/vis.py: per-column width ~3, compact vertical spacing
    fig, axes = plt.subplots(nrows=n, ncols=5, figsize=(3 * 5, 2.5 * n))
    if n == 1:
        axes = axes.reshape(1, -1)

    for row in range(n):
        row_axes = axes[row]

        band1, band2, band3 = s1_list[row]
        chm_true, chm_pred = chm_list[row]

        images = [band1, band2, band3, chm_true, chm_pred]
        titles = [
            "band1 (VV)",
            "band2 (VH)",
            "band3 (VV/VH)",
            "CHM true (band0)",
            "CHM pred",
        ]
        vmin_chm = None
        vmax_chm = None

        for col in range(5):
            ax = row_axes[col]
            band = images[col]
            cmap = "gray" if col < 3 else "viridis"

            im = ax.imshow(band, cmap=cmap)
            ax.set_title(titles[col])
            ax.axis("off")

            if col < 3:
                vmin = float(np.nanmin(band))
                vmax = float(np.nanmax(band))
                if not np.isfinite(vmin) or not np.isfinite(vmax):
                    vmin, vmax = 0.0, 1.0
                im.set_clim(vmin, vmax)

                cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.02)
                ticks = np.linspace(vmin, vmax, 5)
                cbar.set_ticks(ticks)
                cbar.ax.tick_params(labelsize=9)
                cbar.ax.yaxis.set_major_formatter(
                    plt.FuncFormatter(lambda x, _: f"{x:.1f}" if x < 1 else f"{int(x)}")
                )
            else:
                if vmin_chm is None or vmax_chm is None:
                    vmin_chm = float(np.nanmin(chm_true))
                    vmax_chm = float(np.nanmax(chm_true))
                    if not np.isfinite(vmin_chm) or not np.isfinite(vmax_chm):
                        vmin_chm, vmax_chm = 0.0, 1.0

                im.set_clim(vmin_chm, vmax_chm)

                if col == 4:
                    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.02)
                    ticks = np.linspace(vmin_chm, vmax_chm, 5)
                    cbar.set_ticks(ticks)
                    cbar.ax.tick_params(labelsize=9)
                    cbar.ax.yaxis.set_major_formatter(
                        plt.FuncFormatter(lambda x, _: f"{x:.1f}" if x < 1 else f"{int(x)}")
                    )

    plt.tight_layout()
    plt.subplots_adjust(hspace=0.02, wspace=0.2)
    plt.show()

def collect_regression_pairs(model, loader, device, target_index: int = 0):
    model.eval()
    ys = []
    ps = []
    with torch.no_grad():
        for images, labels_cls, labels_chm in tqdm(loader, desc="Collect reg pairs"):
            images = images.to(device)
            targets = labels_chm.to(device)
            preds = model(images)
            mask = torch.isfinite(targets)
            if mask.any():
                ys.append(targets[mask].detach().cpu().numpy())
                ps.append(preds[mask].detach().cpu().numpy())
    if not ys:
        return np.empty(0, dtype=np.float32), np.empty(0, dtype=np.float32)
    y_true = np.concatenate(ys, axis=0)
    y_pred = np.concatenate(ps, axis=0)
    return y_true, y_pred


def plot_regression_joint_with_hists(
    y_true,
    y_pred,
    xlabel: str,
    ylabel: str,
    max_value: float | None = None,
    bins: int = 60,
):
    y_true = np.asarray(y_true).ravel()
    y_pred = np.asarray(y_pred).ravel()
    mask = np.isfinite(y_true) & np.isfinite(y_pred)
    if max_value is not None:
        mask &= y_true <= max_value
    y_true = y_true[mask]
    y_pred = y_pred[mask]
    if y_true.size == 0:
        print("No valid data to plot.")
        return

    # Subsample points for KDE to speed up plotting on large datasets
    max_points = 50000
    if y_true.size > max_points:
        idx = np.random.choice(y_true.size, max_points, replace=False)
        y_true = y_true[idx]
        y_pred = y_pred[idx]

    rmse = float(np.sqrt(np.mean((y_pred - y_true) ** 2)))
    t_mean = float(y_true.mean())
    ss_res = float(np.sum((y_pred - y_true) ** 2))
    ss_tot = float(np.sum((y_true - t_mean) ** 2))
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else float("nan")

    fig = plt.figure(figsize=(6, 6))
    gs = fig.add_gridspec(
        2,
        2,
        width_ratios=(4, 0.8),
        height_ratios=(0.8, 4),
        wspace=0.05,
        hspace=0.05,
    )

    ax_histx = fig.add_subplot(gs[0, 0])
    ax_joint = fig.add_subplot(gs[1, 0])
    ax_histy = fig.add_subplot(gs[1, 1], sharey=ax_joint)

    ax_histx.hist(
        y_true,
        bins=bins,
        color="#1f77b4",
        edgecolor="black",
        linewidth=0.5,
    )
    ax_histx.set_ylabel("Count")
    ax_histx.tick_params(labelbottom=False)
    # Use ScalarFormatter to get scientific notation on the y-axis without offset text
    y_formatter = mticker.ScalarFormatter(useMathText=True)
    y_formatter.set_powerlimits((0, 0))
    ax_histx.yaxis.set_major_formatter(y_formatter)

    ax_histy.hist(
        y_pred,
        bins=bins,
        orientation="horizontal",
        color="#1f77b4",
        edgecolor="black",
        linewidth=0.5,
    )
    ax_histy.set_xlabel("Count")
    ax_histy.tick_params(labelleft=False)
    x_formatter = mticker.ScalarFormatter(useMathText=True)
    x_formatter.set_powerlimits((0, 0))
    ax_histy.xaxis.set_major_formatter(x_formatter)

    if max_value is None:
        min_plot = 0.0
        max_plot = max(float(y_true.max()), float(y_pred.max()))
    else:
        min_plot = 0.0
        max_plot = float(max_value)
        ax_histx.set_xlim(min_plot, max_plot)
        ax_histy.set_ylim(min_plot, max_plot)

    # KDE density surface (reduced levels for speed)
    sns.kdeplot(
        x=y_true,
        y=y_pred,
        fill=True,
        cmap="jet",
        levels=20,
        thresh=0.0,
        ax=ax_joint,
    )

    # Outer density contour as outline
    sns.kdeplot(
        x=y_true,
        y=y_pred,
        fill=False,
        colors="k",
        linewidths=0.8,
        levels=[0.001],
        ax=ax_joint,
    )
    ax_joint.plot(
        [min_plot, max_plot],
        [min_plot, max_plot],
        linestyle="--",
        color="k",
        linewidth=1.0,
    )
    ax_joint.set_xlim(min_plot, max_plot)
    ax_joint.set_ylim(min_plot, max_plot)
    ax_joint.set_xlabel(xlabel)
    ax_joint.set_ylabel(ylabel)
    ax_joint.text(
        0.5,
        0.95,
        f"R² = {r2:.3f}, RMSE = {rmse:.3f}",
        transform=ax_joint.transAxes,
        ha="center",
        va="top",
    )

    plt.show()

"""## Train

### Data
"""

configs['batch_size'] = 4

with Path(f"{BASE_DIR}/s1_60m_classes.json").open("r") as f:
    classes = json.load(f)

with Path(f"{BASE_DIR}/s1_60m_class_weights.json").open("r") as f:
    cw = json.load(f)

class_weights = torch.tensor(cw[configs["loss_fn"]], dtype=torch.float32)
num_classes = len(classes)

num_classes, class_weights

cw.keys()

train_ds, val_ds, test_ds = make_datasets(BASE_DIR)
train_loader = DataLoader(train_ds, batch_size=configs["batch_size"], shuffle=True, num_workers=2)
val_loader = DataLoader(val_ds, batch_size=configs["batch_size"], shuffle=False, num_workers=2)
test_loader = DataLoader(test_ds, batch_size=configs["batch_size"], shuffle=False, num_workers=2)

show_s1_stats()

show_chm_stats()

"""### Classification"""

configs["enable_cls_decoder"] = True
configs["enable_reg_decoder"] = False
configs["base_channels"] = 96
configs["max_lr"] = 5e-4
configs["weight_decay"] = 1e-5
configs["patience"] = 10
configs["dropout"] = 0.1
configs["epoch"] = 100

model = MLPClassifier(in_channels=train_ds.inputs.shape[1], num_classes=num_classes).to(device)
criterion = nn.BCEWithLogitsLoss(weight=class_weights.to(device))
optimizer = torch.optim.AdamW(model.parameters(), lr=configs["max_lr"], weight_decay=configs["weight_decay"])
scheduler = None
num_epochs = configs["epochs"]
best_val_accuracy = -1
best_state = None
patience = configs["patience"]
epochs_no_improve = 0

history = {
    "epoch": [],
    "train_loss": [],
    "train_cls_loss": [],
    "lr": [],
    "val_loss": [],
    "val_cls_loss": [],
    "val_accuracy": [],
    "val_f1_micro": [],
    "val_f1_weighted": [],
    "val_precision_micro": [],
    "val_precision_weighted": [],
    "val_recall_micro": [],
    "val_recall_weighted": [],
    "val_map_micro": [],
    "val_map_weighted": [],
}

for epoch in range(1, num_epochs + 1):
    train_loss = train_one_epoch_cls(
        model,
        train_loader,
        criterion,
        optimizer=optimizer,
        device=device,
        epoch=epoch,
        scheduler=scheduler,
    )
    val_metrics, _, _ = evaluate_cls(model, val_loader, criterion, device)
    print(
        f"Epoch {epoch}: train {train_loss:.4f}, "
    )
    print(
        "\tval loss: {loss:.4f}, "
        "\tweighted F1: {f1_weighted:.4f}, weighted mAP: {map_weighted:.4f}, "
        "accuracy: {accuracy:.4f}".format(**val_metrics)
    )

    history["epoch"].append(epoch)
    history["train_loss"].append(float(train_loss))
    history["val_loss"].append(float(val_metrics["loss"]))
    history["val_accuracy"].append(float(val_metrics["accuracy"]))
    history["val_f1_micro"].append(float(val_metrics["f1_micro"]))
    history["val_f1_weighted"].append(float(val_metrics["f1_weighted"]))
    history["val_precision_micro"].append(float(val_metrics["precision_micro"]))
    history["val_precision_weighted"].append(float(val_metrics["precision_weighted"]))
    history["val_recall_micro"].append(float(val_metrics["recall_micro"]))
    history["val_recall_weighted"].append(float(val_metrics["recall_weighted"]))
    history["val_map_micro"].append(float(val_metrics["map_micro"]))
    history["val_map_weighted"].append(float(val_metrics["map_weighted"]))

    if val_metrics["accuracy"] > best_val_accuracy:
        best_val_accuracy = val_metrics["accuracy"]
        best_state = model.state_dict()
        print("\tUpdated best model")
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        print(f"Patience {epochs_no_improve}/{patience} ")
    if epochs_no_improve >= patience:
        print("\tEarly stopping triggered after", epoch, "epochs")
        break

plt.figure()
plt.plot(history["epoch"], history["train_loss"], label="train_loss")
plt.plot(history["epoch"], history["val_loss"], label="val_loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Train Curve")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure()
plt.plot(history["epoch"], history["val_accuracy"], label="val_accuracy")
plt.plot(history["epoch"], history["val_f1_micro"], label="val_f1_micro")
plt.plot(history["epoch"], history["val_precision_micro"], label="val_precision_micro")
plt.plot(history["epoch"], history["val_recall_micro"], label="val_recall_micro")
plt.plot(history["epoch"], history["val_map_micro"], label="val_map_micro")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Train Curve")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure()
plt.plot(history["lr"])
plt.xlabel("Iteration")
plt.ylabel("Learning rate")
plt.title("Learning rate schedule")
plt.grid(True)
plt.tight_layout()
plt.show()

if best_state is not None:
    model.load_state_dict(best_state)

train_metrics, train_true, train_pred = evaluate_cls(model, train_loader, criterion, device, desc="Train Eval")
val_metrics, val_true, val_pred = evaluate_cls(model, val_loader, criterion, device, desc="Val Eval")
test_metrics, test_true, test_pred = evaluate_cls(model, test_loader, criterion, device, desc="Test Eval")

print(classification_report(test_true, test_pred, zero_division=0, target_names=classes))
print(
    "\t | micro\t | weighted\t \n",
    "-------", "|", "-------------", "|","-------------",
    f"\nprecision| {test_metrics['precision_micro']*100:.3f}%\t | {test_metrics['precision_weighted']*100:.3f}%\t",
    f"\nrecall\t | {test_metrics['recall_micro']*100:.3f}%\t | {test_metrics['recall_weighted']*100:.3f}%\t"
    f"\nf1\t | {test_metrics['f1_micro']*100:.3f}%\t | {test_metrics['f1_weighted']*100:.3f}%\t"
    f"\nmap\t | {test_metrics['map_micro']*100:.3f}%\t | {test_metrics['map_weighted']*100:.3f}%\t"
    f"\naccuracy | {test_metrics['accuracy']*100:.3f}%\t"
)

model.eval()
all_logits = []
all_labels = []
with torch.no_grad():
    for images, labels_cls, labels_chm in tqdm(test_loader, desc="Test features for t-SNE/confusion"):
        images = images.to(device)
        logits = model(images)
        all_logits.append(logits.cpu().numpy())
        all_labels.append(labels_cls.numpy())

X_logits = np.concatenate(all_logits, axis=0)
y_true_multi_full = np.concatenate(all_labels, axis=0)

# Dominant class (argmax) for multi-label visualization
y_true_dom = y_true_multi_full.argmax(axis=1)
y_scores_full = 1.0 / (1.0 + np.exp(-X_logits))
y_pred_dom = y_scores_full.argmax(axis=1)

cm_dom = confusion_matrix(y_true_dom, y_pred_dom, labels=np.arange(num_classes))

plt.figure(figsize=(8, 6))
ax = sns.heatmap(
    cm_dom,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=classes,
    yticklabels=classes,
)
plt.xlabel("Predicted dominant class")
plt.ylabel("True dominant class")
plt.tight_layout()
plt.show()

"""### Regression"""

configs["base_channels"] = 96
configs["max_lr"] = 1e-4
configs["min_lr"] = 1e-6
configs["weight_decay"] = 1e-5
configs["patience"] = 3
configs["dropout"] = 0.1
configs["epoch"] = 100
configs["patience"] = 6
configs["scheduler"] = "CosineAnnealingLR"

model = UNetRegressor(
    in_channels=train_ds.inputs.shape[1],
    base_channels=configs["base_channels"],
    dropout=configs["dropout"],
).to(device)
criterion = masked_rmse_loss
optimizer = torch.optim.AdamW(model.parameters(), lr=configs["max_lr"], weight_decay=configs["weight_decay"])
num_epochs = configs["epochs"]
best_r2 = -1
best_state = None
patience = configs["patience"]
epochs_no_improve = 0

history = {
    "epoch": [],
    "train_loss": [],
    "val_loss": [],
    "val_r2": [],
    "lr": [],
}

steps_per_epoch = max(len(train_loader), 1)
total_steps = steps_per_epoch * configs["epochs"]
if configs["scheduler"] == "CyclicLR":
    scheduler = torch.optim.lr_scheduler.CyclicLR(
        optimizer,
        base_lr=configs["base_lr"],
        max_lr=configs["max_lr"],
        step_size_up=steps_per_epoch * 2,
        mode="triangular2",
        cycle_momentum=False,
    )
elif configs["scheduler"] == "CosineAnnealingLR":
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=total_steps,
        eta_min=configs["min_lr"],
    )
elif configs["scheduler"] == "ExponentialLR":
    gamma = (configs["base_lr"] / configs["max_lr"]) ** (1 / total_steps)
    scheduler = torch.optim.lr_scheduler.ExponentialLR(
        optimizer,
        gamma=gamma
    )
else:
    scheduler = None

for epoch in range(1, num_epochs + 1):
    train_loss = train_one_epoch_reg(
        model,
        train_loader,
        criterion,
        optimizer=optimizer,
        device=device,
        epoch=epoch,
        scheduler=scheduler,
    )
    val_metrics = evaluate_reg(model, val_loader, criterion, device)
    print(f"Epoch {epoch}: train {train_loss:.4f}", "val loss: {loss:.4f}, R2: {r2:.4f}".format(**val_metrics), f"lr: {optimizer.param_groups[0]["lr"]}")

    history["epoch"].append(epoch)
    history["train_loss"].append(float(train_loss))
    history["val_loss"].append(float(val_metrics["loss"]))
    history["val_r2"].append(float(val_metrics["r2"]))
    history["lr"].append(optimizer.param_groups[0]["lr"])

    if val_metrics["r2"] > best_r2:
        best_r2 = val_metrics["r2"]
        best_state = model.state_dict()
        print("\tUpdated best model")
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        print(f"Patience {epochs_no_improve}/{patience} ")
    if epochs_no_improve >= patience:
            print("\tEarly stopping triggered after", epoch, "epochs")
            break

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

ax = axes[0]
ax.plot(history["epoch"], history["train_loss"], label="train_loss")
ax.plot(history["epoch"], history["val_loss"], label="val_loss")
ax.set_xlabel("Epoch")
ax.set_ylabel("Loss")
ax.set_title("Train Curve")
ax.legend()
ax.grid(True)

ax = axes[1]
ax.plot(history["lr"])
ax.set_xlabel("Iteration")
ax.set_ylabel("Learning rate")
ax.set_title("Learning rate schedule")
ax.grid(True)
plt.tight_layout()
plt.show()

if best_state is not None:
    model.load_state_dict(best_state)

train_metrics = evaluate_reg(model, train_loader, criterion, device, desc="Train Eval")
val_metrics = evaluate_reg(model, val_loader, criterion, device, desc="Val Eval")
test_metrics = evaluate_reg(model, test_loader, criterion, device, desc="Test Eval")

result = test_metrics

print("\ntrain loss: ", f"{train_metrics['loss']:.4f}", "\tr2: ", f"{train_metrics['r2']:.4f}")
print("val loss: ", f"{val_metrics['loss']:.4f}", "\tr2: ", f"{val_metrics['r2']:.4f}")
print("test loss: ", f"{test_metrics['loss']:.4f}", "\tr2: ", f"{test_metrics['r2']:.4f}")

visualize_chm_s1_samples(model, test_ds, start_idx=0, num_samples=3)

test_true, test_pred = collect_regression_pairs(model, test_loader, device)

plot_regression_joint_with_hists(
    test_true,
    test_pred,
    xlabel="True CHM (m)",
    ylabel="Predicted CHM (m)",
    max_value=CHM_MAX_THRESHOLD,
)

"""## Export"""

metrics_out = {
    "configs": configs,
    "metrics": {
        "train": train_metrics,
        "val": val_metrics,
        "test": test_metrics
    },
    "classification_report": cls_report,
    "per_class_confusion_accuracy": per_class,
    "history": history,
    "classes": classes,
}

report_path = Path(f"{BASE_DIR}/{configs["model_type"]}_s1_mtl_report.json")
with report_path.open("w", encoding='utf-8') as f:
    json.dump(metrics_out, f, indent=2, ensure_ascii=False)

# Save final/best model weights
out_path = Path(f"{BASE_DIR}/unet_s1_60m_best.pt")
torch.save(model.state_dict(), out_path)
print("Saved best model to", out_path)

